In [5]:
import sys
import pandas as pd

sys.modules.pop('a20_config.a10_config', None)  # force reload
from a20_config.a10_config import dyr, file, var

In [7]:
# !cd "/sharedata/camm/data/i83_g7__VC_arms_data/inp"

In [8]:
# # cd = proj_data/inp/
# !unzip Pitchbook-Full-Data.zip -d ./Pitchbook_full_data
# !rm Pitchbook-Full-Data.zip

In [9]:
df_funds = pd.read_parquet(file.pb_fund__parq)
print(df_funds.shape)
df_funds

(93355, 43)

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,...,PreferredInvestmentTypes,OtherInvestmentPreferences,PreferredInvestmentAmount,PreferredDealSize,PreferredCompanyValuation,PreferredEBITDA,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated
0,10909-00F,Charterhouse Equity Partners IV,None,5,None,Charterhouse Equity Partners,Charterhouse Equity Partners (www.charterhouse...,2005.0,Liquidated,447.000000,...,"Acquisition Financing, Add-on, Buyout/LBO, Mer...",Will lead on a deal,None,None,None,None,None,None,None,03/24/2023
1,21394-63F,Circular Innovation Fund,None,"1 (Circular Innovation Fund), 7 (Cycle Capital...",None,"Circular Innovation Fund, Cycle Capital Manage...",Circular Innovation Fund (www.circularinnovati...,NaN,Open,180.387735,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Seeks Impact investmen...",None,None,None,None,None,None,None,04/20/2023
2,10909-27F,Brynwood Partners V,None,5,None,Brynwood Partners,Brynwood Partners (www.brynwoodpartners.com),2004.0,Fully Invested,257.000000,...,"Acquisition Financing, Add-on, Bankruptcy: Adm...",Will lead on a deal,None,None,None,None,None,None,None,03/23/2023
3,21394-99F,Sirios Overseas Fund,None,7,None,Sirios Capital Management,Sirios Capital Management (www.sirioslp.com),NaN,Open,1964.759892,...,None,None,None,None,None,None,None,None,None,02/24/2023
4,10909-36F,Cerberus Institutional Partners III,None,6,None,Cerberus Capital Management,Cerberus Capital Management (www.cerberus.com),2003.0,Closed,1500.000000,...,"Acquisition Financing, Add-on, Asset Acquisiti...",Will lead on a deal,None,None,None,None,None,None,None,01/30/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93350,23055-22F,BrandProject Capital Fund II,None,3,None,BrandProject,BrandProject (www.brandproject.com),NaN,Open,NaN,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
93351,23354-47F,Oak Street Investment Grade Net Lease Fund,None,20,None,Oak Street Real Estate Capital,Oak Street Real Estate Capital (www.oakstreetr...,NaN,Open,NaN,...,None,None,None,None,None,None,None,None,None,01/31/2023
93352,23278-87F,Hillhouse Real Asset Opportunities Fund,None,25,None,Hillhouse Capital Group,Hillhouse Capital Group (www.hillhouseinvestme...,NaN,Open,NaN,...,None,None,None,None,None,None,None,None,None,03/16/2023
93353,23168-53F,Aultmore Capital Cre Property I,None,3,None,Altmore Capital,Altmore Capital (www.altmorecap.com),NaN,Open,NaN,...,Buyout/LBO,Prefers majority stake,None,None,None,None,None,None,None,01/30/2023
93354,23400-28F,Kkr Credit Partners,None,208,None,Kohlberg Kravis Roberts,Kohlberg Kravis Roberts (www.kkr.com),NaN,Open,NaN,...,Debt - General,None,None,None,None,None,None,None,None,05/17/2023

In [10]:
inv_1 = ['Ascension Ventures']
msk = df_funds[var.investor].eq(inv_1[0])
df_1 = df_funds[msk]

# next two lines: to see all the columns and values for the filtered data 
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

# sort funds based on the FundNo for a nicer view of the data
df_1 = df_1.sort_values(var.fund_no)
df_1

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,NativeFundSize,NativeFundCurrency,FundSizeGroup,FundCategory,FundType,FundAccessPoint,SBICFund,CloseDate,OpenDate,FundTargetSizeLow,FundTargetSizeHigh,FundTargetSize,Domiciles,FundLocation,FundCity,FundState_Province,FundCountry,TimeTakenToCloseFund,TotalFundInvestments,TotalActiveFundInvestments,PreferredIndustry,PreferredVerticals,PreferredGeography,PreferredInvestmentTypes,OtherInvestmentPreferences,PreferredInvestmentAmount,PreferredDealSize,PreferredCompanyValuation,PreferredEBITDA,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated
1422,11004-85F,Ascension Health Ventures,None,1,Yes (Ascension Ventures),Ascension Ventures,Ascension Ventures (www.ascensionventures.org),2001.0,Closed,125.0,125.0,USD,100M - 249M,Venture Capital,Venture - General,Primary Fund,No,07/01/2001,None,NaN,NaN,None,United States,"Saint Louis, MO",Saint Louis,Missouri,United States,None,33.0,NaN,"Healthcare Devices and Supplies, Healthcare Se...",TMT,United States,"Early Stage VC, Later Stage VC","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
87846,11715-58F,CHV II,None,2,None,Ascension Ventures,Ascension Ventures (www.ascensionventures.org),2007.0,Closed,200.0,200.0,USD,100M - 249M,Venture Capital,Venture - General,Primary Fund,No,07/20/2007,01/01/2007,NaN,200.0,< 200,United States: Delaware,"Saint Louis, MO",Saint Louis,Missouri,United States,200 days,24.0,1.0,"Healthcare Devices and Supplies, Healthcare Se...",None,United States,"Early Stage VC, Later Stage VC","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
62206,13492-36F,CHV III,None,3,None,Ascension Ventures,Ascension Ventures (www.ascensionventures.org),2013.0,Closed,225.0,225.0,USD,100M - 249M,Venture Capital,Venture - General,Primary Fund,No,01/02/2013,05/01/2012,225.0,NaN,> 225,United States: Delaware,"Saint Louis, MO",Saint Louis,Missouri,United States,246 days,29.0,4.0,"Healthcare Devices and Supplies, Healthcare Se...",TMT,United States,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/12/2023
59637,15744-88F,CHV IV,None,4,None,Ascension Ventures,Ascension Ventures (www.ascensionventures.org),2017.0,Closed,255.0,255.0,USD,250M - 499M,Venture Capital,Venture - General,Primary Fund,No,11/23/2016,10/05/2016,NaN,NaN,None,United States: Delaware,"Saint Louis, MO",Saint Louis,Missouri,United States,49 days,44.0,23.0,"Healthcare Devices and Supplies, Healthcare Se...",None,"North America, United States","Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/12/2023
29027,17559-19F,Collaborative Health Ventures V,None,5,None,Ascension Ventures,Ascension Ventures (www.ascensionventures.org),2021.0,Closed,285.0,285.0,USD,250M - 499M,Venture Capital,Venture - General,Primary Fund,No,02/19/2021,05/01/2020,250.0,NaN,> 250,United States: Delaware,"Saint Louis, MO",Saint Louis,Missouri,United States,294 days,NaN,NaN,"Healthcare Devices and Supplies, Information T...",HealthTech,United States,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/12/2023

In [11]:
# the list of fund Ids for 1
fund_ids_dict = {
        1: list(df_1[var.fund_id]),
}
fund_ids_dict[1]

['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F']

In [12]:
fund_investors_dict = {
        1: inv_1
}
fund_investors_dict

{1: ['Ascension Ventures']}

In [13]:
fund_ids_dict[2] = []
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'], 2: []}

In [14]:
fund_investors_dict[2] = []
fund_investors_dict

{1: ['Ascension Ventures'], 2: []}

In [15]:
fund_ids_dict[3] = []

In [16]:
fund_investors_dict[3] = []
fund_investors_dict

{1: ['Ascension Ventures'], 2: [], 3: []}

In [17]:
fund_ids_dict[4] = []

In [18]:
fund_investors_dict[4] = []
fund_investors_dict

{1: ['Ascension Ventures'], 2: [], 3: [], 4: []}

In [19]:
fund_ids_dict[5] = []
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: []}

In [20]:
fund_investors_dict[5] = []
fund_investors_dict

{1: ['Ascension Ventures'], 2: [], 3: [], 4: [], 5: []}

In [21]:
inv_6 = ["Intermountain Ventures"]
msk = df_funds[var.investor].eq(inv_6[0])
df_6 = df_funds[msk]
df_6

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,NativeFundSize,NativeFundCurrency,FundSizeGroup,FundCategory,FundType,FundAccessPoint,SBICFund,CloseDate,OpenDate,FundTargetSizeLow,FundTargetSizeHigh,FundTargetSize,Domiciles,FundLocation,FundCity,FundState_Province,FundCountry,TimeTakenToCloseFund,TotalFundInvestments,TotalActiveFundInvestments,PreferredIndustry,PreferredVerticals,PreferredGeography,PreferredInvestmentTypes,OtherInvestmentPreferences,PreferredInvestmentAmount,PreferredDealSize,PreferredCompanyValuation,PreferredEBITDA,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated
46027,17580-43F,Intermountain Ventures Fund,None,1,Yes (Intermountain Ventures),Intermountain Ventures,Intermountain Ventures (intermountainventures....,NaN,Closed,NaN,NaN,USD,None,Venture Capital,Venture - General,Primary Fund,No,None,None,NaN,NaN,None,United States,"Salt Lake City, UT",Salt Lake City,Utah,United States,None,19.0,6.0,Healthcare,HealthTech,None,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",1.0 - 5.0,None,None,None,None,None,None,05/06/2023

In [22]:
fund_ids_dict[6] = list(df_6[var.fund_id])
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F']}

In [23]:
fund_investors_dict[6] = inv_6
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures']}

In [24]:
fund_ids_dict[7] = []
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: []}

In [25]:
fund_investors_dict[7] = []
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: []}

In [26]:
fund_ids_dict[8] = []
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: [],
 8: []}

In [27]:
fund_investors_dict[8] = []
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: [],
 8: []}

In [28]:
inv_9 = ["Kaiser Permanente Ventures"]
msk = df_funds[var.investor].eq(inv_9[0])
df_9 = df_funds[msk]
df_9

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,NativeFundSize,NativeFundCurrency,FundSizeGroup,FundCategory,FundType,FundAccessPoint,SBICFund,CloseDate,OpenDate,FundTargetSizeLow,FundTargetSizeHigh,FundTargetSize,Domiciles,FundLocation,FundCity,FundState_Province,FundCountry,TimeTakenToCloseFund,TotalFundInvestments,TotalActiveFundInvestments,PreferredIndustry,PreferredVerticals,PreferredGeography,PreferredInvestmentTypes,OtherInvestmentPreferences,PreferredInvestmentAmount,PreferredDealSize,PreferredCompanyValuation,PreferredEBITDA,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated
53466,16929-91F,KPV Fund V,None,8,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2019.0,Closed,141.0,141.0,USD,100M - 249M,Venture Capital,Venture - General,Primary Fund,No,12/05/2019,None,NaN,NaN,None,United States,"Oakland, CA",Oakland,California,United States,None,18.0,17.0,Healthcare,"Digital Health, HealthTech",None,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,03/07/2023
68078,13943-26F,Kaiser Permanente Ventures Fund,None,7,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2011.0,Closed,170.0,170.0,USD,100M - 249M,Venture Capital,Venture - General,Primary Fund,No,08/31/2011,None,NaN,NaN,None,United States,"Oakland, CA",Oakland,California,United States,None,31.0,13.0,Healthcare Technology Systems,None,None,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,03/07/2023
75853,13168-45F,Kaiser Permanente Healthcare Fund V,None,6,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2008.0,Closed,120.0,120.0,USD,100M - 249M,Venture Capital,Venture - General,Primary Fund,No,01/01/2008,None,NaN,NaN,None,United States,"Oakland, CA",Oakland,California,United States,None,30.0,1.0,Healthcare Devices and Supplies,None,United States,"Early Stage VC, Later Stage VC","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
82308,11195-11F,KP Healthcare Fund I,None,1,Yes (Kaiser Permanente Ventures),Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2000.0,Closed,20.0,20.0,USD,0 - 99M,Venture Capital,Venture - General,Primary Fund,No,01/01/2000,None,NaN,NaN,None,United States,"Oakland, CA",Oakland,California,United States,None,NaN,NaN,Healthcare,None,None,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
82310,11195-20F,KP Healthcare Fund II,None,2,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2002.0,Closed,10.0,10.0,USD,0 - 99M,Venture Capital,Venture - General,Primary Fund,No,01/01/2002,None,NaN,NaN,None,United States,"Oakland, CA",Oakland,California,United States,None,3.0,NaN,"Communications and Networking, Healthcare Serv...","EdTech, TMT",None,Later Stage VC,"Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
82312,11195-29F,Kaiser Permanente Healthcare Side Fund,None,3,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2004.0,Closed,20.2,20.2,USD,0 - 99M,Venture Capital,Venture - General,Primary Fund,No,01/01/2004,None,NaN,NaN,None,United States,"Oakland, CA",Oakland,California,United States,None,5.0,NaN,"Healthcare Devices and Supplies, Healthcare Te...",TMT,United States,Later Stage VC,"Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
82314,11195-38F,Kaiser Permanente Healthcare Fund III,None,4,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2005.0,Closed,10.0,10.0,USD,0 - 99M,Venture Capital,Venture - General,Primary Fund,No,01/01/2005,None,NaN,NaN,None,United States,"Oakland, CA",Oakland,California,United States,None,4.0,NaN,Healthcare Devices and Supplies,Manufacturing,None,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
82316,11195-47F,Kaiser Permanente Healthcare Fund IV,None,5,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2006.0,Closed,20.0,20.0,USD,0 - 99M,Venture Capital,Venture - General,Primary Fund,No,01/01/2006,None,NaN,NaN,None,United States,"Oakland, CA",Oakland,California,United States,None,15.0,1.0,Healthcare Devices and Supplies,None,United States,"Early Stage VC, Later Stage VC","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023

In [29]:
fund_ids_dict[9] = list(df_9[var.fund_id])
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: [],
 8: [],
 9: ['16929-91F',
  '13943-26F',
  '13168-45F',
  '11195-11F',
  '11195-20F',
  '11195-29F',
  '11195-38F',
  '11195-47F']}

In [30]:
fund_investors_dict[9] = inv_9
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: [],
 8: [],
 9: ['Kaiser Permanente Ventures']}

In [31]:
inv_10 = ["Ochsner Lafayette General"]
msk = df_funds[var.investor].eq(inv_10[0])
df_10 = df_funds[msk]
df_10

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,NativeFundSize,NativeFundCurrency,FundSizeGroup,FundCategory,FundType,FundAccessPoint,SBICFund,CloseDate,OpenDate,FundTargetSizeLow,FundTargetSizeHigh,FundTargetSize,Domiciles,FundLocation,FundCity,FundState_Province,FundCountry,TimeTakenToCloseFund,TotalFundInvestments,TotalActiveFundInvestments,PreferredIndustry,PreferredVerticals,PreferredGeography,PreferredInvestmentTypes,OtherInvestmentPreferences,PreferredInvestmentAmount,PreferredDealSize,PreferredCompanyValuation,PreferredEBITDA,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated
56241,15463-27F,Healthcare Innovation Fund,None,1,Yes (Ochsner Lafayette General),Ochsner Lafayette General,Ochsner Lafayette General (www.ochsnerlg.org),NaN,Closed,2.5,2.5,USD,0 - 99M,Venture Capital,Venture Capital - Early Stage,Primary Fund,No,None,01/01/2016,NaN,NaN,None,United States,"Lafayette, LA",Lafayette,Louisiana,United States,None,2.0,2.0,"Commercial Services, Healthcare Services, Othe...","Digital Health, TMT",None,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",0.25 - 0.5,None,None,None,None,None,None,05/06/2023

In [32]:
fund_ids_dict[10] = list(df_10[var.fund_id])
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: [],
 8: [],
 9: ['16929-91F',
  '13943-26F',
  '13168-45F',
  '11195-11F',
  '11195-20F',
  '11195-29F',
  '11195-38F',
  '11195-47F'],
 10: ['15463-27F']}

In [33]:
fund_investors_dict[10] = inv_10
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: [],
 8: [],
 9: ['Kaiser Permanente Ventures'],
 10: ['Ochsner Lafayette General']}

In [34]:
inv_11 = ["Mayo Clinic Ventures"]
msk = df_funds[var.investor].eq(inv_11[0])
df_11 = df_funds[msk]
df_11

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,NativeFundSize,NativeFundCurrency,FundSizeGroup,FundCategory,FundType,FundAccessPoint,SBICFund,CloseDate,OpenDate,FundTargetSizeLow,FundTargetSizeHigh,FundTargetSize,Domiciles,FundLocation,FundCity,FundState_Province,FundCountry,TimeTakenToCloseFund,TotalFundInvestments,TotalActiveFundInvestments,PreferredIndustry,PreferredVerticals,PreferredGeography,PreferredInvestmentTypes,OtherInvestmentPreferences,PreferredInvestmentAmount,PreferredDealSize,PreferredCompanyValuation,PreferredEBITDA,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated
59038,16885-63F,Mayo Benefactors Innovation Fund,None,1,Yes (Mayo Clinic Ventures),Mayo Clinic Ventures,Mayo Clinic Ventures (ventures.mayoclinic.org),2020.0,Closed,NaN,NaN,USD,None,Venture Capital,Venture - General,Primary Fund,No,01/01/2020,None,NaN,NaN,None,United States,"Rochester, MN",Rochester,Minnesota,United States,None,9.0,8.0,Healthcare,None,None,"Early Stage VC, Later Stage VC, Seed Round",None,None,None,None,None,None,None,None,02/08/2023

In [35]:
fund_ids_dict[11] = list(df_11[var.fund_id])
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: [],
 8: [],
 9: ['16929-91F',
  '13943-26F',
  '13168-45F',
  '11195-11F',
  '11195-20F',
  '11195-29F',
  '11195-38F',
  '11195-47F'],
 10: ['15463-27F'],
 11: ['16885-63F']}

In [36]:
fund_investors_dict[11] = inv_11
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: [],
 8: [],
 9: ['Kaiser Permanente Ventures'],
 10: ['Ochsner Lafayette General'],
 11: ['Mayo Clinic Ventures']}

In [37]:
inv_12 = ["MemorialCare Innovation Fund"]
msk = df_funds[var.investor].eq(inv_12[0])
df_12 = df_funds[msk]
df_12

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,NativeFundSize,NativeFundCurrency,FundSizeGroup,FundCategory,FundType,FundAccessPoint,SBICFund,CloseDate,OpenDate,FundTargetSizeLow,FundTargetSizeHigh,FundTargetSize,Domiciles,FundLocation,FundCity,FundState_Province,FundCountry,TimeTakenToCloseFund,TotalFundInvestments,TotalActiveFundInvestments,PreferredIndustry,PreferredVerticals,PreferredGeography,PreferredInvestmentTypes,OtherInvestmentPreferences,PreferredInvestmentAmount,PreferredDealSize,PreferredCompanyValuation,PreferredEBITDA,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated
67050,13847-14F,MemorialCare Innovation Fund,None,1,Yes (MemorialCare Innovation Fund),MemorialCare Innovation Fund,MemorialCare Innovation Fund (www.memorialcare...,2013.0,Closed,150.0,150.0,USD,100M - 249M,Venture Capital,Venture - General,Primary Fund,No,01/01/2013,11/01/2012,50.0,NaN,> 50,United States: Delaware,"Long Beach, CA",Long Beach,California,United States,61 days,13.0,12.0,"Healthcare Devices and Supplies, Healthcare Se...","Life Sciences, Oncology, TMT",North America,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,02/04/2023

In [38]:
fund_ids_dict[12] = list(df_12[var.fund_id])
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: [],
 8: [],
 9: ['16929-91F',
  '13943-26F',
  '13168-45F',
  '11195-11F',
  '11195-20F',
  '11195-29F',
  '11195-38F',
  '11195-47F'],
 10: ['15463-27F'],
 11: ['16885-63F'],
 12: ['13847-14F']}

In [39]:
fund_investors_dict[12] = inv_12
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: [],
 8: [],
 9: ['Kaiser Permanente Ventures'],
 10: ['Ochsner Lafayette General'],
 11: ['Mayo Clinic Ventures'],
 12: ['MemorialCare Innovation Fund']}

In [40]:
fund_ids_dict[13] = []
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: [],
 8: [],
 9: ['16929-91F',
  '13943-26F',
  '13168-45F',
  '11195-11F',
  '11195-20F',
  '11195-29F',
  '11195-38F',
  '11195-47F'],
 10: ['15463-27F'],
 11: ['16885-63F'],
 12: ['13847-14F'],
 13: []}

In [41]:
fund_investors_dict[13] = []
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: [],
 8: [],
 9: ['Kaiser Permanente Ventures'],
 10: ['Ochsner Lafayette General'],
 11: ['Mayo Clinic Ventures'],
 12: ['MemorialCare Innovation Fund'],
 13: []}

In [42]:
fund_ids_dict[14] = []
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: [],
 8: [],
 9: ['16929-91F',
  '13943-26F',
  '13168-45F',
  '11195-11F',
  '11195-20F',
  '11195-29F',
  '11195-38F',
  '11195-47F'],
 10: ['15463-27F'],
 11: ['16885-63F'],
 12: ['13847-14F'],
 13: [],
 14: []}

In [43]:
fund_investors_dict[14] = []
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: [],
 8: [],
 9: ['Kaiser Permanente Ventures'],
 10: ['Ochsner Lafayette General'],
 11: ['Mayo Clinic Ventures'],
 12: ['MemorialCare Innovation Fund'],
 13: [],
 14: []}

In [44]:
inv_15 = ["Orlando Health"]
msk = df_funds[var.investor].eq(inv_15[0])
df_15 = df_funds[msk]
df_15

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,NativeFundSize,NativeFundCurrency,FundSizeGroup,FundCategory,FundType,FundAccessPoint,SBICFund,CloseDate,OpenDate,FundTargetSizeLow,FundTargetSizeHigh,FundTargetSize,Domiciles,FundLocation,FundCity,FundState_Province,FundCountry,TimeTakenToCloseFund,TotalFundInvestments,TotalActiveFundInvestments,PreferredIndustry,PreferredVerticals,PreferredGeography,PreferredInvestmentTypes,OtherInvestmentPreferences,PreferredInvestmentAmount,PreferredDealSize,PreferredCompanyValuation,PreferredEBITDA,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated
4524,22073-86F,Orlando Health Ventures II,None,2,None,Orlando Health,Orlando Health (www.orlandohealth.com),NaN,Open,125.00,125.00,USD,100M - 249M,Private Equity,Buyout,Primary Fund,No,None,07/22/2022,NaN,NaN,None,United States: Delaware,"Orlando, FL",Orlando,Florida,United States,None,NaN,NaN,Healthcare,None,None,Buyout/LBO,Prefers majority stake,None,None,None,None,None,None,None,05/06/2023
27983,17324-11F,Orlando Health Ventures I,None,1,Yes (Orlando Health),Orlando Health,Orlando Health (www.orlandohealth.com),NaN,Closed,21.25,21.25,USD,0 - 99M,Private Equity,Buyout,Primary Fund,No,None,03/16/2020,21.25,NaN,> 21.25,United States: Delaware,"Orlando, FL",Orlando,Florida,United States,None,2.0,1.0,Healthcare,None,None,Buyout/LBO,"Prefers majority stake, Seeks Impact investments",None,None,None,None,None,None,None,05/06/2023

In [45]:
fund_ids_dict[15] = list(df_15[var.fund_id])
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: [],
 8: [],
 9: ['16929-91F',
  '13943-26F',
  '13168-45F',
  '11195-11F',
  '11195-20F',
  '11195-29F',
  '11195-38F',
  '11195-47F'],
 10: ['15463-27F'],
 11: ['16885-63F'],
 12: ['13847-14F'],
 13: [],
 14: [],
 15: ['22073-86F', '17324-11F']}

In [46]:
fund_investors_dict[15] = inv_15
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: [],
 8: [],
 9: ['Kaiser Permanente Ventures'],
 10: ['Ochsner Lafayette General'],
 11: ['Mayo Clinic Ventures'],
 12: ['MemorialCare Innovation Fund'],
 13: [],
 14: [],
 15: ['Orlando Health']}

In [47]:
inv_16 = ["OSF Ventures"]
msk = df_funds[var.investor].eq(inv_16[0])
df_16 = df_funds[msk]
df_16

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,NativeFundSize,NativeFundCurrency,FundSizeGroup,FundCategory,FundType,FundAccessPoint,SBICFund,CloseDate,OpenDate,FundTargetSizeLow,FundTargetSizeHigh,FundTargetSize,Domiciles,FundLocation,FundCity,FundState_Province,FundCountry,TimeTakenToCloseFund,TotalFundInvestments,TotalActiveFundInvestments,PreferredIndustry,PreferredVerticals,PreferredGeography,PreferredInvestmentTypes,OtherInvestmentPreferences,PreferredInvestmentAmount,PreferredDealSize,PreferredCompanyValuation,PreferredEBITDA,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated
21845,20618-65F,OSF Ventures III,None,3,None,OSF Ventures,OSF Ventures (www.osfventures.org),NaN,Open,NaN,NaN,USD,None,Venture Capital,Venture - General,Primary Fund,No,None,01/10/2022,100.0,NaN,> 100,United States,"Peoria, IL",Peoria,Illinois,United States,None,NaN,NaN,"Diagnostic Equipment, Therapeutic Devices",HealthTech,None,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/06/2023
50646,16701-67F,OSF Ventures II,None,2,None,OSF Ventures,OSF Ventures (www.osfventures.org),2019.0,Closed,75.0,75.0,USD,0 - 99M,Venture Capital,Venture - General,Primary Fund,No,07/25/2019,None,NaN,NaN,None,United States,"Peoria, IL",Peoria,Illinois,United States,None,8.0,3.0,Healthcare,HealthTech,None,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/06/2023
58344,15958-81F,OSF Ventures Fund,None,1,Yes (OSF Ventures),OSF Ventures,OSF Ventures (www.osfventures.org),2017.0,Closed,NaN,NaN,USD,None,Venture Capital,Venture - General,Primary Fund,No,12/31/2017,None,75.0,NaN,> 75,United States,"Peoria, IL",Peoria,Illinois,United States,None,13.0,5.0,Healthcare,TMT,None,"Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/06/2023

In [48]:
fund_ids_dict[16] = list(df_16[var.fund_id])
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: [],
 8: [],
 9: ['16929-91F',
  '13943-26F',
  '13168-45F',
  '11195-11F',
  '11195-20F',
  '11195-29F',
  '11195-38F',
  '11195-47F'],
 10: ['15463-27F'],
 11: ['16885-63F'],
 12: ['13847-14F'],
 13: [],
 14: [],
 15: ['22073-86F', '17324-11F'],
 16: ['20618-65F', '16701-67F', '15958-81F']}

In [49]:
fund_investors_dict[16] = inv_16
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: [],
 8: [],
 9: ['Kaiser Permanente Ventures'],
 10: ['Ochsner Lafayette General'],
 11: ['Mayo Clinic Ventures'],
 12: ['MemorialCare Innovation Fund'],
 13: [],
 14: [],
 15: ['Orlando Health'],
 16: ['OSF Ventures']}

In [50]:
inv_17 = ["Mass General Brigham Innovation", "Mass General Brigham Ventures"]
fund_ids_17 = ['18303-94F', '16855-39F', '16855-48F', '15786-10F', '13309-75F']
msk = df_funds[var.fund_id].isin(fund_ids_17)
df_17 = df_funds[msk]
df_17

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,NativeFundSize,NativeFundCurrency,FundSizeGroup,FundCategory,FundType,FundAccessPoint,SBICFund,CloseDate,OpenDate,FundTargetSizeLow,FundTargetSizeHigh,FundTargetSize,Domiciles,FundLocation,FundCity,FundState_Province,FundCountry,TimeTakenToCloseFund,TotalFundInvestments,TotalActiveFundInvestments,PreferredIndustry,PreferredVerticals,PreferredGeography,PreferredInvestmentTypes,OtherInvestmentPreferences,PreferredInvestmentAmount,PreferredDealSize,PreferredCompanyValuation,PreferredEBITDA,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated
41711,18303-94F,Mass General Brigham Fund III,None,3,None,Mass General Brigham Ventures,Mass General Brigham Ventures (www.massgeneral...,2021.0,Closed,NaN,NaN,USD,None,Venture Capital,Venture - General,Primary Fund,No,12/31/2021,02/01/2021,250.00,NaN,> 250,United States: Delaware,"Cambridge, MA",Cambridge,Massachusetts,United States,333 days,56.0,22.0,None,None,None,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/06/2023
52426,16855-39F,Artificial Intelligence and Digital Translatio...,None,"1 (Mass General Brigham), 3 (Mass General Brig...",Yes (Mass General Brigham),"Mass General Brigham, Mass General Brigham Inn...",Mass General Brigham (www.massgeneralbrigham.o...,2019.0,Closed,30.0,30.0,USD,0 - 99M,Venture Capital,Venture - General,Primary Fund,No,10/21/2019,None,30.00,NaN,> 30,United States,"Boston, MA",Boston,Massachusetts,United States,None,2.0,2.0,Healthcare,Artificial Intelligence & Machine Learning,None,"Early Stage VC, Later Stage VC, Seed Round",None,None,None,None,None,None,None,None,01/30/2023
52428,16855-48F,Translational Innovation Fund,None,"2 (Mass General Brigham), 4 (Mass General Brig...",None,"Mass General Brigham, Mass General Brigham Inn...",Mass General Brigham (www.massgeneralbrigham.o...,2019.0,Closed,50.0,50.0,USD,0 - 99M,Venture Capital,Venture - General,Primary Fund,No,10/21/2019,10/21/2019,50.00,NaN,> 50,United States,"Boston, MA",Boston,Massachusetts,United States,None,NaN,NaN,Healthcare,None,None,"Early Stage VC, Later Stage VC, Seed Round",None,None,None,None,None,None,None,None,01/30/2023
60157,15786-10F,Partners Innovation Fund II,None,"2 (Mass General Brigham Innovation), 2 (Mass G...",None,"Mass General Brigham Innovation, Mass General ...",Mass General Brigham Innovation (innovation.ma...,2016.0,Closed,171.0,171.0,USD,100M - 249M,Venture Capital,Venture Capital - Early Stage,Primary Fund,No,09/08/2017,10/31/2016,66.08,NaN,> 66.08,United States: Delaware,"Cambridge, MA",Cambridge,Massachusetts,United States,312 days,4.0,3.0,"Financial Services, Healthcare","Life Sciences, Oncology",United States,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/06/2023
78019,13309-75F,Partners Innovation Fund,None,"1 (Mass General Brigham Innovation), 1 (Mass G...",Yes (Mass General Brigham Ventures),"Mass General Brigham Innovation, Mass General ...",Mass General Brigham Innovation (innovation.ma...,2016.0,Closed,171.0,171.0,USD,100M - 249M,Venture Capital,Venture Capital - Early Stage,Primary Fund,No,12/31/2016,01/01/2008,NaN,NaN,None,United States,"Cambridge, MA",Cambridge,Massachusetts,United States,9 years 2 days,4.0,NaN,Pharmaceuticals and Biotechnology,Life Sciences,United States,"Angel (individual), Early Stage VC, Later Stag...",None,None,None,None,None,None,None,None,05/06/2023

In [51]:
fund_ids_dict[17] = fund_ids_17
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: [],
 8: [],
 9: ['16929-91F',
  '13943-26F',
  '13168-45F',
  '11195-11F',
  '11195-20F',
  '11195-29F',
  '11195-38F',
  '11195-47F'],
 10: ['15463-27F'],
 11: ['16885-63F'],
 12: ['13847-14F'],
 13: [],
 14: [],
 15: ['22073-86F', '17324-11F'],
 16: ['20618-65F', '16701-67F', '15958-81F'],
 17: ['18303-94F', '16855-39F', '16855-48F', '15786-10F', '13309-75F']}

In [52]:
fund_investors_dict[17] = inv_17
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: [],
 8: [],
 9: ['Kaiser Permanente Ventures'],
 10: ['Ochsner Lafayette General'],
 11: ['Mayo Clinic Ventures'],
 12: ['MemorialCare Innovation Fund'],
 13: [],
 14: [],
 15: ['Orlando Health'],
 16: ['OSF Ventures'],
 17: ['Mass General Brigham Innovation', 'Mass General Brigham Ventures']}

In [53]:
inv_18 = ["Providence Ventures"]
msk = df_funds[var.investor].eq(inv_18[0])
df_18 = df_funds[msk]
df_18

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,NativeFundSize,NativeFundCurrency,FundSizeGroup,FundCategory,FundType,FundAccessPoint,SBICFund,CloseDate,OpenDate,FundTargetSizeLow,FundTargetSizeHigh,FundTargetSize,Domiciles,FundLocation,FundCity,FundState_Province,FundCountry,TimeTakenToCloseFund,TotalFundInvestments,TotalActiveFundInvestments,PreferredIndustry,PreferredVerticals,PreferredGeography,PreferredInvestmentTypes,OtherInvestmentPreferences,PreferredInvestmentAmount,PreferredDealSize,PreferredCompanyValuation,PreferredEBITDA,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated
41888,16054-75F,Providence Ventures Fund,None,1,Yes (Providence Ventures),Providence Ventures,Providence Ventures (www.providenceventures.org),2014.0,Closed,150.0,150.0,USD,100M - 249M,Venture Capital,Venture - General,Primary Fund,No,12/31/2014,09/19/2014,NaN,NaN,None,United States,"Seattle, WA",Seattle,Washington,United States,103 days,6.0,3.0,"Healthcare Services, Healthcare Technology Sys...","Digital Health, HealthTech, SaaS, TMT",None,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/14/2023
48264,16527-61F,Providence Ventures Fund II,None,2,None,Providence Ventures,Providence Ventures (www.providenceventures.org),2019.0,Closed,150.0,150.0,USD,100M - 249M,Venture Capital,Venture - General,Primary Fund,No,01/08/2019,None,NaN,NaN,None,United States,"Seattle, WA",Seattle,Washington,United States,None,3.0,2.0,"Healthcare Devices and Supplies, Healthcare Se...",HealthTech,None,Early Stage VC,"Prefers minority stake, Seeks Impact investmen...",5.0 - 15.0,None,None,None,None,None,None,05/14/2023

In [54]:
fund_ids_dict[18] = list(df_18[var.fund_id])
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: [],
 8: [],
 9: ['16929-91F',
  '13943-26F',
  '13168-45F',
  '11195-11F',
  '11195-20F',
  '11195-29F',
  '11195-38F',
  '11195-47F'],
 10: ['15463-27F'],
 11: ['16885-63F'],
 12: ['13847-14F'],
 13: [],
 14: [],
 15: ['22073-86F', '17324-11F'],
 16: ['20618-65F', '16701-67F', '15958-81F'],
 17: ['18303-94F', '16855-39F', '16855-48F', '15786-10F', '13309-75F'],
 18: ['16054-75F', '16527-61F']}

In [55]:
fund_investors_dict[18] = inv_18
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: [],
 8: [],
 9: ['Kaiser Permanente Ventures'],
 10: ['Ochsner Lafayette General'],
 11: ['Mayo Clinic Ventures'],
 12: ['MemorialCare Innovation Fund'],
 13: [],
 14: [],
 15: ['Orlando Health'],
 16: ['OSF Ventures'],
 17: ['Mass General Brigham Innovation', 'Mass General Brigham Ventures'],
 18: ['Providence Ventures']}

In [56]:
inv_19 = ["Texas Medical Center"]
msk = df_funds[var.investor].eq(inv_19[0])
df_19 = df_funds[msk]
df_19

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,NativeFundSize,NativeFundCurrency,FundSizeGroup,FundCategory,FundType,FundAccessPoint,SBICFund,CloseDate,OpenDate,FundTargetSizeLow,FundTargetSizeHigh,FundTargetSize,Domiciles,FundLocation,FundCity,FundState_Province,FundCountry,TimeTakenToCloseFund,TotalFundInvestments,TotalActiveFundInvestments,PreferredIndustry,PreferredVerticals,PreferredGeography,PreferredInvestmentTypes,OtherInvestmentPreferences,PreferredInvestmentAmount,PreferredDealSize,PreferredCompanyValuation,PreferredEBITDA,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated
42944,16134-04F,TMC Venture Fund,None,1,Yes (Texas Medical Center),Texas Medical Center,Texas Medical Center (www.tmc.edu),2017.0,Closed,25.0,25.0,USD,0 - 99M,Venture Capital,Venture Capital - Early Stage,Primary Fund,No,11/08/2017,None,NaN,NaN,None,United States,"Houston, TX",Houston,Texas,United States,None,48.0,43.0,"Healthcare Devices and Supplies, Healthcare Te...","Digital Health, HealthTech, Life Sciences",Texas,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/14/2023

In [57]:
fund_ids_dict[19] = list(df_19[var.fund_id])
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: [],
 8: [],
 9: ['16929-91F',
  '13943-26F',
  '13168-45F',
  '11195-11F',
  '11195-20F',
  '11195-29F',
  '11195-38F',
  '11195-47F'],
 10: ['15463-27F'],
 11: ['16885-63F'],
 12: ['13847-14F'],
 13: [],
 14: [],
 15: ['22073-86F', '17324-11F'],
 16: ['20618-65F', '16701-67F', '15958-81F'],
 17: ['18303-94F', '16855-39F', '16855-48F', '15786-10F', '13309-75F'],
 18: ['16054-75F', '16527-61F'],
 19: ['16134-04F']}

In [58]:
fund_investors_dict[19] = inv_19
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: [],
 8: [],
 9: ['Kaiser Permanente Ventures'],
 10: ['Ochsner Lafayette General'],
 11: ['Mayo Clinic Ventures'],
 12: ['MemorialCare Innovation Fund'],
 13: [],
 14: [],
 15: ['Orlando Health'],
 16: ['OSF Ventures'],
 17: ['Mass General Brigham Innovation', 'Mass General Brigham Ventures'],
 18: ['Providence Ventures'],
 19: ['Texas Medical Center']}

In [59]:
fund_ids_dict[20] = []
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: [],
 8: [],
 9: ['16929-91F',
  '13943-26F',
  '13168-45F',
  '11195-11F',
  '11195-20F',
  '11195-29F',
  '11195-38F',
  '11195-47F'],
 10: ['15463-27F'],
 11: ['16885-63F'],
 12: ['13847-14F'],
 13: [],
 14: [],
 15: ['22073-86F', '17324-11F'],
 16: ['20618-65F', '16701-67F', '15958-81F'],
 17: ['18303-94F', '16855-39F', '16855-48F', '15786-10F', '13309-75F'],
 18: ['16054-75F', '16527-61F'],
 19: ['16134-04F'],
 20: []}

In [60]:
fund_investors_dict[20] = []
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: [],
 8: [],
 9: ['Kaiser Permanente Ventures'],
 10: ['Ochsner Lafayette General'],
 11: ['Mayo Clinic Ventures'],
 12: ['MemorialCare Innovation Fund'],
 13: [],
 14: [],
 15: ['Orlando Health'],
 16: ['OSF Ventures'],
 17: ['Mass General Brigham Innovation', 'Mass General Brigham Ventures'],
 18: ['Providence Ventures'],
 19: ['Texas Medical Center'],
 20: []}

In [61]:
inv_21 = ["UnityPoint Health"]
msk = df_funds[var.investor].eq(inv_21[0])
df_21 = df_funds[msk]
df_21

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,NativeFundSize,NativeFundCurrency,FundSizeGroup,FundCategory,FundType,FundAccessPoint,SBICFund,CloseDate,OpenDate,FundTargetSizeLow,FundTargetSizeHigh,FundTargetSize,Domiciles,FundLocation,FundCity,FundState_Province,FundCountry,TimeTakenToCloseFund,TotalFundInvestments,TotalActiveFundInvestments,PreferredIndustry,PreferredVerticals,PreferredGeography,PreferredInvestmentTypes,OtherInvestmentPreferences,PreferredInvestmentAmount,PreferredDealSize,PreferredCompanyValuation,PreferredEBITDA,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated
56020,16624-63F,UnityPoint Health Ventures Innovation Fund,None,1,Yes (UnityPoint Health),UnityPoint Health,UnityPoint Health (www.unitypoint.org),2020.0,Closed,NaN,NaN,USD,None,Venture Capital,Venture Capital - Early Stage,Primary Fund,No,12/31/2020,05/23/2019,100.0,NaN,> 100,United States: Iowa,"West Des Moines, IA",West Des Moines,Iowa,United States,1 year 223 days,1.0,1.0,"Healthcare Services, Medical Supplies, Therape...","Digital Health, HealthTech",None,"Early Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023

In [62]:
fund_ids_dict[21] = list(df_21[var.fund_id])
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: [],
 8: [],
 9: ['16929-91F',
  '13943-26F',
  '13168-45F',
  '11195-11F',
  '11195-20F',
  '11195-29F',
  '11195-38F',
  '11195-47F'],
 10: ['15463-27F'],
 11: ['16885-63F'],
 12: ['13847-14F'],
 13: [],
 14: [],
 15: ['22073-86F', '17324-11F'],
 16: ['20618-65F', '16701-67F', '15958-81F'],
 17: ['18303-94F', '16855-39F', '16855-48F', '15786-10F', '13309-75F'],
 18: ['16054-75F', '16527-61F'],
 19: ['16134-04F'],
 20: [],
 21: ['16624-63F']}

In [63]:
fund_investors_dict[21] = inv_21
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: [],
 8: [],
 9: ['Kaiser Permanente Ventures'],
 10: ['Ochsner Lafayette General'],
 11: ['Mayo Clinic Ventures'],
 12: ['MemorialCare Innovation Fund'],
 13: [],
 14: [],
 15: ['Orlando Health'],
 16: ['OSF Ventures'],
 17: ['Mass General Brigham Innovation', 'Mass General Brigham Ventures'],
 18: ['Providence Ventures'],
 19: ['Texas Medical Center'],
 20: [],
 21: ['UnityPoint Health']}

In [64]:
inv_22 = ["University Hospitals Ventures"]
msk = df_funds[var.investor].eq(inv_22[0])
df_22 = df_funds[msk]
df_22

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,NativeFundSize,NativeFundCurrency,FundSizeGroup,FundCategory,FundType,FundAccessPoint,SBICFund,CloseDate,OpenDate,FundTargetSizeLow,FundTargetSizeHigh,FundTargetSize,Domiciles,FundLocation,FundCity,FundState_Province,FundCountry,TimeTakenToCloseFund,TotalFundInvestments,TotalActiveFundInvestments,PreferredIndustry,PreferredVerticals,PreferredGeography,PreferredInvestmentTypes,OtherInvestmentPreferences,PreferredInvestmentAmount,PreferredDealSize,PreferredCompanyValuation,PreferredEBITDA,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated
7028,22402-36F,Healthcare Collaboration Fund,None,2,None,University Hospitals Ventures,University Hospitals Ventures (ventures.uhhosp...,2021.0,Closed,8.0,8.0,USD,0 - 99M,Venture Capital,Venture Capital - Early Stage,Primary Fund,No,12/31/2021,07/01/2021,8.0,NaN,> 8,United States,"Cleveland, OH",Cleveland,Ohio,United States,183 days,5.0,5.0,"Healthcare Devices and Supplies, Healthcare Se...",None,Great Lakes,"Early Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/06/2023
16048,22402-18F,UH Ventures (off-Balance sheet),None,1,None,University Hospitals Ventures,University Hospitals Ventures (ventures.uhhosp...,NaN,Evergreen,NaN,NaN,USD,None,Venture Capital,Venture - General,Primary Fund,No,None,10/01/2018,NaN,NaN,None,United States,"Cleveland, OH",Cleveland,Ohio,United States,None,NaN,NaN,"Healthcare Devices and Supplies, Healthcare Se...",None,None,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/06/2023

In [65]:
fund_ids_dict[22] = list(df_22[var.fund_id])
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: [],
 8: [],
 9: ['16929-91F',
  '13943-26F',
  '13168-45F',
  '11195-11F',
  '11195-20F',
  '11195-29F',
  '11195-38F',
  '11195-47F'],
 10: ['15463-27F'],
 11: ['16885-63F'],
 12: ['13847-14F'],
 13: [],
 14: [],
 15: ['22073-86F', '17324-11F'],
 16: ['20618-65F', '16701-67F', '15958-81F'],
 17: ['18303-94F', '16855-39F', '16855-48F', '15786-10F', '13309-75F'],
 18: ['16054-75F', '16527-61F'],
 19: ['16134-04F'],
 20: [],
 21: ['16624-63F'],
 22: ['22402-36F', '22402-18F']}

In [66]:
fund_investors_dict[22] = inv_22
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: [],
 8: [],
 9: ['Kaiser Permanente Ventures'],
 10: ['Ochsner Lafayette General'],
 11: ['Mayo Clinic Ventures'],
 12: ['MemorialCare Innovation Fund'],
 13: [],
 14: [],
 15: ['Orlando Health'],
 16: ['OSF Ventures'],
 17: ['Mass General Brigham Innovation', 'Mass General Brigham Ventures'],
 18: ['Providence Ventures'],
 19: ['Texas Medical Center'],
 20: [],
 21: ['UnityPoint Health'],
 22: ['University Hospitals Ventures']}

In [67]:
fund_ids_dict[23] = []
fund_ids_dict

{1: ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['17580-43F'],
 7: [],
 8: [],
 9: ['16929-91F',
  '13943-26F',
  '13168-45F',
  '11195-11F',
  '11195-20F',
  '11195-29F',
  '11195-38F',
  '11195-47F'],
 10: ['15463-27F'],
 11: ['16885-63F'],
 12: ['13847-14F'],
 13: [],
 14: [],
 15: ['22073-86F', '17324-11F'],
 16: ['20618-65F', '16701-67F', '15958-81F'],
 17: ['18303-94F', '16855-39F', '16855-48F', '15786-10F', '13309-75F'],
 18: ['16054-75F', '16527-61F'],
 19: ['16134-04F'],
 20: [],
 21: ['16624-63F'],
 22: ['22402-36F', '22402-18F'],
 23: []}

In [68]:
fund_investors_dict[23] = []
fund_investors_dict

{1: ['Ascension Ventures'],
 2: [],
 3: [],
 4: [],
 5: [],
 6: ['Intermountain Ventures'],
 7: [],
 8: [],
 9: ['Kaiser Permanente Ventures'],
 10: ['Ochsner Lafayette General'],
 11: ['Mayo Clinic Ventures'],
 12: ['MemorialCare Innovation Fund'],
 13: [],
 14: [],
 15: ['Orlando Health'],
 16: ['OSF Ventures'],
 17: ['Mass General Brigham Innovation', 'Mass General Brigham Ventures'],
 18: ['Providence Ventures'],
 19: ['Texas Medical Center'],
 20: [],
 21: ['UnityPoint Health'],
 22: ['University Hospitals Ventures'],
 23: []}

In [69]:
# Total number of funds
all_ids = []
for v in fund_ids_dict.values():
    all_ids += v
len(all_ids)

33