In [1]:
import sys
import pandas as pd
from pathlib import Path

sys.modules.pop('a20_config.a10_config', None)  # force reload
from a20_config.a10_config import dyr, file, const, var

Path.cwd()

PosixPath('/sharedata/camm/c_projects/i100_g7__VC_arms')

# Filter manually founded funds from Fund.csv from PitchBook data

In [2]:
df_funds = pd.read_parquet(file.pb_fund__parq)
print(df_funds.shape)
df_funds

(93355, 43)

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,...,PreferredInvestmentTypes,OtherInvestmentPreferences,PreferredInvestmentAmount,PreferredDealSize,PreferredCompanyValuation,PreferredEBITDA,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated
0,10909-00F,Charterhouse Equity Partners IV,None,5,None,Charterhouse Equity Partners,Charterhouse Equity Partners (www.charterhouse...,2005.0,Liquidated,447.000000,...,"Acquisition Financing, Add-on, Buyout/LBO, Mer...",Will lead on a deal,None,None,None,None,None,None,None,03/24/2023
1,21394-63F,Circular Innovation Fund,None,"1 (Circular Innovation Fund), 7 (Cycle Capital...",None,"Circular Innovation Fund, Cycle Capital Manage...",Circular Innovation Fund (www.circularinnovati...,NaN,Open,180.387735,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Seeks Impact investmen...",None,None,None,None,None,None,None,04/20/2023
2,10909-27F,Brynwood Partners V,None,5,None,Brynwood Partners,Brynwood Partners (www.brynwoodpartners.com),2004.0,Fully Invested,257.000000,...,"Acquisition Financing, Add-on, Bankruptcy: Adm...",Will lead on a deal,None,None,None,None,None,None,None,03/23/2023
3,21394-99F,Sirios Overseas Fund,None,7,None,Sirios Capital Management,Sirios Capital Management (www.sirioslp.com),NaN,Open,1964.759892,...,None,None,None,None,None,None,None,None,None,02/24/2023
4,10909-36F,Cerberus Institutional Partners III,None,6,None,Cerberus Capital Management,Cerberus Capital Management (www.cerberus.com),2003.0,Closed,1500.000000,...,"Acquisition Financing, Add-on, Asset Acquisiti...",Will lead on a deal,None,None,None,None,None,None,None,01/30/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93350,23055-22F,BrandProject Capital Fund II,None,3,None,BrandProject,BrandProject (www.brandproject.com),NaN,Open,NaN,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
93351,23354-47F,Oak Street Investment Grade Net Lease Fund,None,20,None,Oak Street Real Estate Capital,Oak Street Real Estate Capital (www.oakstreetr...,NaN,Open,NaN,...,None,None,None,None,None,None,None,None,None,01/31/2023
93352,23278-87F,Hillhouse Real Asset Opportunities Fund,None,25,None,Hillhouse Capital Group,Hillhouse Capital Group (www.hillhouseinvestme...,NaN,Open,NaN,...,None,None,None,None,None,None,None,None,None,03/16/2023
93353,23168-53F,Aultmore Capital Cre Property I,None,3,None,Altmore Capital,Altmore Capital (www.altmorecap.com),NaN,Open,NaN,...,Buyout/LBO,Prefers majority stake,None,None,None,None,None,None,None,01/30/2023
93354,23400-28F,Kkr Credit Partners,None,208,None,Kohlberg Kravis Roberts,Kohlberg Kravis Roberts (www.kkr.com),NaN,Open,NaN,...,Debt - General,None,None,None,None,None,None,None,None,05/17/2023

In [3]:
fund_ids_dict = {
        1 : ['11004-85F', '11715-58F', '13492-36F', '15744-88F', '17559-19F'],
        2 : [],
        3 : [],
        4 : [],
        5 : [],
        6 : ['17580-43F'],
        7 : [],
        8 : [],
        9 : ['16929-91F', '13943-26F', '13168-45F', '11195-11F', '11195-20F', '11195-29F', '11195-38F', '11195-47F'],
        10: ['15463-27F'],
        11: ['16885-63F'],
        12: ['13847-14F'],
        13: [],
        14: [],
        15: ['22073-86F', '17324-11F'],
        16: ['20618-65F', '16701-67F', '15958-81F'],
        17: ['18303-94F', '16855-39F', '16855-48F', '15786-10F', '13309-75F'],
        18: ['16054-75F', '16527-61F'],
        19: ['16134-04F'],
        20: [],
        21: ['16624-63F'],
        22: ['22402-36F', '22402-18F'],
        23: []
}

In [4]:
all_ids = []
for v in fund_ids_dict.values():
    all_ids += v
len(all_ids)

33

In [5]:
all_ids

['11004-85F',
 '11715-58F',
 '13492-36F',
 '15744-88F',
 '17559-19F',
 '17580-43F',
 '16929-91F',
 '13943-26F',
 '13168-45F',
 '11195-11F',
 '11195-20F',
 '11195-29F',
 '11195-38F',
 '11195-47F',
 '15463-27F',
 '16885-63F',
 '13847-14F',
 '22073-86F',
 '17324-11F',
 '20618-65F',
 '16701-67F',
 '15958-81F',
 '18303-94F',
 '16855-39F',
 '16855-48F',
 '15786-10F',
 '13309-75F',
 '16054-75F',
 '16527-61F',
 '16134-04F',
 '16624-63F',
 '22402-36F',
 '22402-18F']

In [6]:
msk = df_funds[var.fund_id].isin(all_ids)
df_selected_funds = df_funds[msk]
df_selected_funds

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,...,PreferredInvestmentTypes,OtherInvestmentPreferences,PreferredInvestmentAmount,PreferredDealSize,PreferredCompanyValuation,PreferredEBITDA,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated
1422,11004-85F,Ascension Health Ventures,None,1,Yes (Ascension Ventures),Ascension Ventures,Ascension Ventures (www.ascensionventures.org),2001.0,Closed,125.00,...,"Early Stage VC, Later Stage VC","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
4524,22073-86F,Orlando Health Ventures II,None,2,None,Orlando Health,Orlando Health (www.orlandohealth.com),NaN,Open,125.00,...,Buyout/LBO,Prefers majority stake,None,None,None,None,None,None,None,05/06/2023
7028,22402-36F,Healthcare Collaboration Fund,None,2,None,University Hospitals Ventures,University Hospitals Ventures (ventures.uhhosp...,2021.0,Closed,8.00,...,"Early Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/06/2023
16048,22402-18F,UH Ventures (off-Balance sheet),None,1,None,University Hospitals Ventures,University Hospitals Ventures (ventures.uhhosp...,NaN,Evergreen,NaN,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/06/2023
21845,20618-65F,OSF Ventures III,None,3,None,OSF Ventures,OSF Ventures (www.osfventures.org),NaN,Open,NaN,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/06/2023
27983,17324-11F,Orlando Health Ventures I,None,1,Yes (Orlando Health),Orlando Health,Orlando Health (www.orlandohealth.com),NaN,Closed,21.25,...,Buyout/LBO,"Prefers majority stake, Seeks Impact investments",None,None,None,None,None,None,None,05/06/2023
29027,17559-19F,Collaborative Health Ventures V,None,5,None,Ascension Ventures,Ascension Ventures (www.ascensionventures.org),2021.0,Closed,285.00,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/12/2023
41711,18303-94F,Mass General Brigham Fund III,None,3,None,Mass General Brigham Ventures,Mass General Brigham Ventures (www.massgeneral...,2021.0,Closed,NaN,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/06/2023
41888,16054-75F,Providence Ventures Fund,None,1,Yes (Providence Ventures),Providence Ventures,Providence Ventures (www.providenceventures.org),2014.0,Closed,150.00,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/14/2023
42944,16134-04F,TMC Venture Fund,None,1,Yes (Texas Medical Center),Texas Medical Center,Texas Medical Center (www.tmc.edu),2017.0,Closed,25.00,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/14/2023
46027,17580-43F,Intermountain Ventures Fund,None,1,Yes (Intermountain Ventures),Intermountain Ventures,Intermountain Ventures (intermountainventures....,NaN,Closed,NaN,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",1.0 - 5.0,None,None,None,None,None,None,05/06/2023
48264,16527-61F,Providence Ventures Fund II,None,2,None,Providence Ventures,Providence Ventures (www.providenceventures.org),2019.0,Closed,150.00,...,Early Stage VC,"Prefers minority stake, Seeks Impact investmen...",5.0 - 15.0,None,None,None,None,None,None,05/14/2023
50646,16701-67F,OSF Ventures II,None,2,None,OSF Ventures,OSF Ventures (www.osfventures.org),2019.0,Closed,75.00,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/06/2023
52426,16855-39F,Artificial Intelligence and Digital Translatio...,None,"1 (Mass General Brigham), 3 (Mass General Brig...",Yes (Mass General Brigham),"Mass General Brigham, Mass General Brigham Inn...",Mass General Brigham (www.massgeneralbrigham.o...,2019.0,Closed,30.00,...,"Early Stage VC, Later Stage VC, Seed Round",None,None,None,None,None,None,None,None,01/30/2023
52428,16855-48F,Translational Innovation Fund,None,"2 (Mass General Brigham), 4 (Mass General Brig...",None,"Mass General Brigham, Mass General Brigham Inn...",Mass General Brigham (www.massgeneralbrigham.o...,2019.0,Closed,50.00,...,"Early Stage VC, Later Stage VC, Seed Round",None,None,None,None,None,None,None,None,01/30/2023
53466,16929-91F,KPV Fund V,None,8,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2019.0,Closed,141.00,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,03/07/2023
56020,16624-63F,UnityPoint Health Ventures Innovation Fund,None,1,Yes (UnityPoint Health),UnityPoint Health,UnityPoint Health (www.unitypoint.org),2020.0,Closed,NaN,...,"Early Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
56241,15463-27F,Healthcare Innovation Fund,None,1,Yes (Ochsner Lafayette General),Ochsner Lafayette General,Ochsner Lafayette General (www.ochsnerlg.org),NaN,Closed,2.50,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",0.25 - 0.5,None,None,None,None,None,None,05/06/2023
58344,15958-81F,OSF Ventures Fund,None,1,Yes (OSF Ventures),OSF Ventures,OSF Ventures (www.osfventures.org),2017.0,Closed,NaN,...,"Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/06/2023
59038,16885-63F,Mayo Benefactors Innovation Fund,None,1,Yes (Mayo Clinic Ventures),Mayo Clinic Ventures,Mayo Clinic Ventures (ventures.mayoclinic.org),2020.0,Closed,NaN,...,"Early Stage VC, Later Stage VC, Seed Round",None,None,None,None,None,None,None,None,02/08/2023
59637,15744-88F,CHV IV,None,4,None,Ascension Ventures,Ascension Ventures (www.ascensionventures.org),2017.0,Closed,255.00,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/12/2023
60157,15786-10F,Partners Innovation Fund II,None,"2 (Mass General Brigham Innovation), 2 (Mass G...",None,"Mass General Brigham Innovation, Mass General ...",Mass General Brigham Innovation (innovation.ma...,2016.0,Closed,171.00,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/06/2023
62206,13492-36F,CHV III,None,3,None,Ascension Ventures,Ascension Ventures (www.ascensionventures.org),2013.0,Closed,225.00,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,05/12/2023
67050,13847-14F,MemorialCare Innovation Fund,None,1,Yes (MemorialCare Innovation Fund),MemorialCare Innovation Fund,MemorialCare Innovation Fund (www.memorialcare...,2013.0,Closed,150.00,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,02/04/2023
68078,13943-26F,Kaiser Permanente Ventures Fund,None,7,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2011.0,Closed,170.00,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,03/07/2023
75853,13168-45F,Kaiser Permanente Healthcare Fund V,None,6,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2008.0,Closed,120.00,...,"Early Stage VC, Later Stage VC","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
78019,13309-75F,Partners Innovation Fund,None,"1 (Mass General Brigham Innovation), 1 (Mass G...",Yes (Mass General Brigham Ventures),"Mass General Brigham Innovation, Mass General ...",Mass General Brigham Innovation (innovation.ma...,2016.0,Closed,171.00,...,"Angel (individual), Early Stage VC, Later Stag...",None,None,None,None,None,None,None,None,05/06/2023
82308,11195-11F,KP Healthcare Fund I,None,1,Yes (Kaiser Permanente Ventures),Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2000.0,Closed,20.00,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
82310,11195-20F,KP Healthcare Fund II,None,2,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2002.0,Closed,10.00,...,Later Stage VC,"Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
82312,11195-29F,Kaiser Permanente Healthcare Side Fund,None,3,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2004.0,Closed,20.20,...,Later Stage VC,"Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
82314,11195-38F,Kaiser Permanente Healthcare Fund III,None,4,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2005.0,Closed,10.00,...,"Early Stage VC, Later Stage VC, Seed Round","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
82316,11195-47F,Kaiser Permanente Healthcare Fund IV,None,5,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2006.0,Closed,20.00,...,"Early Stage VC, Later Stage VC","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023
87846,11715-58F,CHV II,None,2,None,Ascension Ventures,Ascension Ventures (www.ascensionventures.org),2007.0,Closed,200.00,...,"Early Stage VC, Later Stage VC","Prefers minority stake, Will syndicate",None,None,None,None,None,None,None,01/30/2023

# Are Investor names unique in the investor data?
What do I mean unique? if it is not unique we should have same name but different IDs so we can say investornames are not unique

In [7]:
df_investor = pd.read_parquet(file.pb_investor__parq)
df_investor

,InvestorID,InvestorName,InvestorAlsoKnownAs,InvestorFormerName,InvestorLegalName,Description,InvestorStatus,PrimaryInvestorType,OtherInvestorTypes,AUM,...,LastFinancingDebt,LastFinancingDebtDate,LastInvestmentStatus,LastClosedFundName,LastClosedFundVintage,LastClosedFundSize,LastClosedFundType,LastClosedFundCloseDate,LastClosedFundOpenDate,LastUpdated
0,10010-89,Broadcom (Acquired 2016),None,None,Broadcom Corp.,"Broadcom was a designer, developer and global ...",Acquired/Merged,Corporation,None,NaN,...,Other,11/17/2017,Completed,None,NaN,NaN,None,None,None,01/30/2023
1,56752-21,Invertec,None,None,None,Invertec was a Spain based venture capital fir...,Out of Business,Venture Capital,None,NaN,...,None,04/20/2010,Completed,None,NaN,NaN,None,None,None,01/30/2023
2,10011-79,Charterhouse Equity Partners,Charterhouse,None,"Charterhouse Equity Partners, LLC",Charterhouse Equity Partners was a private equ...,Out of Business,PE/Buyout,Growth/Expansion,NaN,...,None,02/03/2020,Completed,Charterhouse Equity Partners IV,2005.0,447.0,Buyout,12/31/2003,05/02/2003,04/04/2023
3,56853-46,IQ Partners,IQ Partners Sp. z o.o.,None,IQ Partners S.A.,"Founded in 2011, IQ Partners was a venture cap...",Out of Business,Venture Capital,None,NaN,...,None,03/14/2018,Completed,EREMIE fund Seed,2017.0,NaN,Venture Capital - Early Stage,12/31/2017,None,05/18/2023
4,10011-61,Ares Private Equity Group,Ares,None,Ares Capital Management LLC,"Founded in 1997, Ares Private Equity Group is ...",Actively Seeking New Investments,PE/Buyout,"Growth/Expansion, Infrastructure, Real Estate",33400.0,...,None,05/11/2023,Announced/In Progress,None,NaN,NaN,None,None,None,05/17/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385458,58176-82,Jabra,None,None,"GN US, Inc.",Manufacturer of hands-free devices for mobile ...,None,Corporation,None,NaN,...,None,10/27/2000,Completed,None,NaN,NaN,None,None,None,05/12/2023
385459,293866-30,Hancock Daniel,Hancock,None,"Hancock, Daniel & Johnson, P.C.",Hancock Daniel is a full-service law firm foun...,None,Corporation,None,NaN,...,None,06/04/2011,Completed,None,NaN,NaN,None,None,None,05/06/2023
385460,388321-48,PARI,None,None,PARI GmbH,"Pari Respiratory Equipment is a Midlothian, VA...",None,Corporation,None,NaN,...,None,05/11/2023,Completed,None,NaN,NaN,None,None,None,05/17/2023
385461,294023-89,Growlink,"Hydropods, Inc.",None,None,Developer of an agriculture technology applica...,None,Corporation,None,NaN,...,None,05/10/2023,Completed,None,NaN,NaN,None,None,None,05/18/2023
385462,341157-34,Dr. Wolff Group,None,Alcina Wolff Vermögensverwaltungs- Und Beteili...,Dr. Wolff-Gruppe GmbH,Developer of personal care products and pharma...,None,Corporation,None,NaN,...,None,11/12/2021,Completed,None,NaN,NaN,None,None,None,05/12/2023

In [8]:
df_inv_id_inv_name = df_investor[[var.investor_id, var.investor_name]]

In [9]:
df_inv_id_inv_name = df_inv_id_inv_name.drop_duplicates()

In [10]:
df_inv_id_inv_name[var.investor_id].is_unique

True

In [11]:
df_inv_id_inv_name[var.investor_name].is_unique

False

-> so because we have names that has different IDs investor names are not unique in the data

# Finding Investor IDs for the selected Funds from the 'DealInvestorRelation.csv'

In [12]:
df_deal_inv_rel = pd.read_parquet(file.pb_deal_inv_rel__parq)
df_deal_inv_rel

,DealID,InvestorID,InvestorName,InvestorStatus,IsLeadInvestor,InvestorFundID,InvestorFundName,InvestorWebsite,InvestorInvestmentAmount,LeadPartnerID,LeadPartnerName,LeadPartnerEmail,LeadPartnerPhone,LastUpdated
0,10006-75T,10013-32,Audax Group,New Investor,Yes,10947-16F,Audax Private Equity Fund II,www.audaxgroup.com,NaN,15918-58P,Oliver Ewald,oewald@audaxgroup.com,+1 (617) 859-1538,01/30/2023
1,197378-02T,40667-95,Standard Chartered,New Investor,No,None,None,www.sc.com,NaN,None,None,None,None,01/30/2023
2,10006-93T,10073-98,Irving Place Capital,New Investor,Yes,10913-95F,Irving Place Capital Partners II,www.irvingplacecapital.com,130.000,None,None,None,None,05/12/2023
3,197380-81T,57084-40,Calbee Japan,Acquirer,Yes,None,None,www.calbee.co.jp,NaN,None,None,None,None,02/02/2023
4,10007-02T,10012-69,Berkshire Partners,New Investor,Yes,10928-17F,Berkshire Fund VI,www.berkshirepartners.com,NaN,15348-97P,Marni Payne,mpayne@berkshirepartners.com,+1 (617) 227-0050,05/14/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2398255,199399-96T,10123-03,General Catalyst,New Investor,No,None,None,www.generalcatalyst.com,NaN,None,None,None,None,04/28/2023
2398256,199400-05T,501492-79,Chainlink Fall Hackathon,New Investor,Yes,None,None,None,0.015,None,None,None,None,01/30/2023
2398257,199400-14T,490909-06,Robert Brown,New Investor,No,None,None,None,NaN,289376-83P,Robert Brown,None,None,01/30/2023
2398258,199400-14T,501492-34,Craig Cheek,New Investor,No,None,None,None,NaN,308660-23P,Craig Cheek,None,None,01/30/2023
2398259,199400-14T,184234-96,Anthony Tolliver,New Investor,No,None,None,None,NaN,191694-25P,Anthony Tolliver,atolliver@wealthletefunds.com,+1 (417) 217-7057,01/30/2023

In [13]:
# keep only rows that contains any of the fund Ids we have

In [14]:
msk = df_deal_inv_rel[var.investor_fund_id].isin(all_ids)
df_filtered_deal_inv_rel = df_deal_inv_rel[msk]
df_filtered_deal_inv_rel

,DealID,InvestorID,InvestorName,InvestorStatus,IsLeadInvestor,InvestorFundID,InvestorFundName,InvestorWebsite,InvestorInvestmentAmount,LeadPartnerID,LeadPartnerName,LeadPartnerEmail,LeadPartnerPhone,LastUpdated
14202,198863-38T,56040-94,MemorialCare Innovation Fund,New Investor,No,13847-14F,MemorialCare Innovation Fund,www.memorialcareinnovationfund.com,NaN,38944-99P,Brant Heise,bheise@memorialcare.org,+1 (562) 432-0051,02/04/2023
75278,192822-67T,56040-94,MemorialCare Innovation Fund,New Investor,No,13847-14F,MemorialCare Innovation Fund,www.memorialcareinnovationfund.com,NaN,None,None,None,None,01/30/2023
101030,190057-15T,109795-69,Texas Medical Center,New Investor,Yes,16134-04F,TMC Venture Fund,www.tmc.edu,NaN,None,None,None,None,01/30/2023
127280,189081-10T,109795-69,Texas Medical Center,New Investor,Yes,16134-04F,TMC Venture Fund,www.tmc.edu,NaN,None,None,None,None,01/30/2023
132945,189519-58T,433710-46,Mass General Brigham Ventures,New Investor,No,18303-94F,Mass General Brigham Fund III,www.massgeneralbrighamventures.com,NaN,59813-83P,Meredith Fisher Ph.D,meredith@mediartx.com,+1 (617) 349-2000,03/15/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2285647,15892-57T,11114-65,Ascension Ventures,New Investor,No,11004-85F,Ascension Health Ventures,www.ascensionventures.org,2.77,41931-19P,Jeffery Stolte,jstolte@providencehealth.bc.ca,+1 (604) 806-9090,04/26/2023
2288791,15996-97T,11114-65,Ascension Ventures,New Investor,No,11004-85F,Ascension Health Ventures,www.ascensionventures.org,NaN,None,None,None,None,01/30/2023
2292250,15619-96T,11114-65,Ascension Ventures,New Investor,No,11715-58F,CHV II,www.ascensionventures.org,5.51,12822-76P,Ryan Schuler,ryan@ascensionventures.org,+1 (314) 733-8100,01/30/2023
2333996,201160-72T,433943-74,University Hospitals Ventures,New Investor,No,22402-36F,Healthcare Collaboration Fund,ventures.uhhospitals.org,NaN,None,None,None,None,03/03/2023
2392865,10580-41T,11114-65,Ascension Ventures,New Investor,No,11004-85F,Ascension Health Ventures,www.ascensionventures.org,10.00,12822-58P,Matthew Hermann,None,None,01/30/2023

In [15]:
# only keep these columns, I want to add them to the funds spreadsheet later
cols_2_keep = {
        1: var.investor_id,
        2: var.investor_name,
        3: var.investor_fund_id,
        4: var.investor_fund_name,
}

df_filtered_deal_inv_rel = df_filtered_deal_inv_rel[list(cols_2_keep.values())]
df_filtered_deal_inv_rel

,InvestorID,InvestorName,InvestorFundID,InvestorFundName
14202,56040-94,MemorialCare Innovation Fund,13847-14F,MemorialCare Innovation Fund
75278,56040-94,MemorialCare Innovation Fund,13847-14F,MemorialCare Innovation Fund
101030,109795-69,Texas Medical Center,16134-04F,TMC Venture Fund
127280,109795-69,Texas Medical Center,16134-04F,TMC Venture Fund
132945,433710-46,Mass General Brigham Ventures,18303-94F,Mass General Brigham Fund III
...,...,...,...,...
2285647,11114-65,Ascension Ventures,11004-85F,Ascension Health Ventures
2288791,11114-65,Ascension Ventures,11004-85F,Ascension Health Ventures
2292250,11114-65,Ascension Ventures,11715-58F,CHV II
2333996,433943-74,University Hospitals Ventures,22402-36F,Healthcare Collaboration Fund
2392865,11114-65,Ascension Ventures,11004-85F,Ascension Health Ventures

In [16]:
# Drop duplicates, because we only want unqiute items to match them
df_filtered_deal_inv_rel = df_filtered_deal_inv_rel.drop_duplicates()
df_filtered_deal_inv_rel

,InvestorID,InvestorName,InvestorFundID,InvestorFundName
14202,56040-94,MemorialCare Innovation Fund,13847-14F,MemorialCare Innovation Fund
101030,109795-69,Texas Medical Center,16134-04F,TMC Venture Fund
132945,433710-46,Mass General Brigham Ventures,18303-94F,Mass General Brigham Fund III
137344,55757-98,Mayo Clinic Ventures,16885-63F,Mayo Benefactors Innovation Fund
175054,11246-23,Kaiser Permanente Ventures,16929-91F,KPV Fund V
186027,11114-65,Ascension Ventures,13492-36F,CHV III
186145,11114-65,Ascension Ventures,15744-88F,CHV IV
198277,11246-23,Kaiser Permanente Ventures,13943-26F,Kaiser Permanente Ventures Fund
271200,160041-88,OSF Ventures,16701-67F,OSF Ventures II
276789,433943-74,University Hospitals Ventures,22402-36F,Healthcare Collaboration Fund
328719,266690-26,Intermountain Ventures,17580-43F,Intermountain Ventures Fund
374885,123677-56,Providence Ventures,16527-61F,Providence Ventures Fund II
451289,123677-56,Providence Ventures,16054-75F,Providence Ventures Fund
453549,50987-17,Mass General Brigham,16855-39F,Artificial Intelligence and Digital Translatio...
474603,433710-46,Mass General Brigham Ventures,15786-10F,Partners Innovation Fund II
497122,118715-50,Mass General Brigham Innovation,15786-10F,Partners Innovation Fund II
515663,61215-67,UnityPoint Health,16624-63F,UnityPoint Health Ventures Innovation Fund
543645,118715-50,Mass General Brigham Innovation,16855-39F,Artificial Intelligence and Digital Translatio...
562513,96517-54,Orlando Health,17324-11F,Orlando Health Ventures I
654121,11114-65,Ascension Ventures,11715-58F,CHV II
849803,151167-52,Ochsner Lafayette General,15463-27F,Healthcare Innovation Fund
917321,11246-23,Kaiser Permanente Ventures,13168-45F,Kaiser Permanente Healthcare Fund V
929440,11114-65,Ascension Ventures,11004-85F,Ascension Health Ventures
961801,160041-88,OSF Ventures,15958-81F,OSF Ventures Fund
1385887,118715-50,Mass General Brigham Innovation,13309-75F,Partners Innovation Fund
1400331,11246-23,Kaiser Permanente Ventures,11195-38F,Kaiser Permanente Healthcare Fund III
1661327,433710-46,Mass General Brigham Ventures,13309-75F,Partners Innovation Fund
1870043,11246-23,Kaiser Permanente Ventures,11195-20F,KP Healthcare Fund II
1870077,11246-23,Kaiser Permanente Ventures,11195-47F,Kaiser Permanente Healthcare Fund IV
1913454,11246-23,Kaiser Permanente Ventures,11195-29F,Kaiser Permanente Healthcare Side Fund

In [17]:
df_filtered_deal_inv_rel.shape

(30, 4)

In [18]:
df_filtered_deal_inv_rel.columns

Index(['InvestorID', 'InvestorName', 'InvestorFundID', 'InvestorFundName'], dtype='object')

In [19]:
# Group by Fund and aggregate Investor info into lists
_df = df_filtered_deal_inv_rel
grouped = _df.groupby([var.investor_fund_id, var.investor_fund_name]).agg(
        {var.investor_id: list, var.investor_name: list}).reset_index()
grouped

,InvestorFundID,InvestorFundName,InvestorID,InvestorName
0,11004-85F,Ascension Health Ventures,[11114-65],[Ascension Ventures]
1,11195-20F,KP Healthcare Fund II,[11246-23],[Kaiser Permanente Ventures]
2,11195-29F,Kaiser Permanente Healthcare Side Fund,[11246-23],[Kaiser Permanente Ventures]
3,11195-38F,Kaiser Permanente Healthcare Fund III,[11246-23],[Kaiser Permanente Ventures]
4,11195-47F,Kaiser Permanente Healthcare Fund IV,[11246-23],[Kaiser Permanente Ventures]
5,11715-58F,CHV II,[11114-65],[Ascension Ventures]
6,13168-45F,Kaiser Permanente Healthcare Fund V,[11246-23],[Kaiser Permanente Ventures]
7,13309-75F,Partners Innovation Fund,"[118715-50, 433710-46]","[Mass General Brigham Innovation, Mass General..."
8,13492-36F,CHV III,[11114-65],[Ascension Ventures]
9,13847-14F,MemorialCare Innovation Fund,[56040-94],[MemorialCare Innovation Fund]
10,13943-26F,Kaiser Permanente Ventures Fund,[11246-23],[Kaiser Permanente Ventures]
11,15463-27F,Healthcare Innovation Fund,[151167-52],[Ochsner Lafayette General]
12,15744-88F,CHV IV,[11114-65],[Ascension Ventures]
13,15786-10F,Partners Innovation Fund II,"[433710-46, 118715-50]","[Mass General Brigham Ventures, Mass General B..."
14,15958-81F,OSF Ventures Fund,[160041-88],[OSF Ventures]
15,16054-75F,Providence Ventures Fund,[123677-56],[Providence Ventures]
16,16134-04F,TMC Venture Fund,[109795-69],[Texas Medical Center]
17,16527-61F,Providence Ventures Fund II,[123677-56],[Providence Ventures]
18,16624-63F,UnityPoint Health Ventures Innovation Fund,[61215-67],[UnityPoint Health]
19,16701-67F,OSF Ventures II,[160041-88],[OSF Ventures]
20,16855-39F,Artificial Intelligence and Digital Translatio...,"[50987-17, 118715-50]","[Mass General Brigham, Mass General Brigham In..."
21,16885-63F,Mayo Benefactors Innovation Fund,[55757-98],[Mayo Clinic Ventures]
22,16929-91F,KPV Fund V,[11246-23],[Kaiser Permanente Ventures]
23,17324-11F,Orlando Health Ventures I,[96517-54],[Orlando Health]
24,17580-43F,Intermountain Ventures Fund,[266690-26],[Intermountain Ventures]
25,18303-94F,Mass General Brigham Fund III,[433710-46],[Mass General Brigham Ventures]
26,22402-36F,Healthcare Collaboration Fund,[433943-74],[University Hospitals Ventures]

In [20]:
# Expand lists into separate column
max_investors = grouped[var.investor_id].apply(len).max()
max_investors

np.int64(2)

In [21]:
for i in range(max_investors):
    grouped[f'{var.investor_id}_{i + 1}'] = grouped[var.investor_id].apply(lambda x: x[i] if i < len(x) else None)
    grouped[f'{var.investor_name}_{i + 1}'] = grouped[var.investor_name].apply(lambda x: x[i] if i < len(x) else None)

# Drop original list columns
grouped = grouped.drop(columns = [var.investor_id, var.investor_name])

In [22]:
grouped

,InvestorFundID,InvestorFundName,InvestorID_1,InvestorName_1,InvestorID_2,InvestorName_2
0,11004-85F,Ascension Health Ventures,11114-65,Ascension Ventures,None,None
1,11195-20F,KP Healthcare Fund II,11246-23,Kaiser Permanente Ventures,None,None
2,11195-29F,Kaiser Permanente Healthcare Side Fund,11246-23,Kaiser Permanente Ventures,None,None
3,11195-38F,Kaiser Permanente Healthcare Fund III,11246-23,Kaiser Permanente Ventures,None,None
4,11195-47F,Kaiser Permanente Healthcare Fund IV,11246-23,Kaiser Permanente Ventures,None,None
5,11715-58F,CHV II,11114-65,Ascension Ventures,None,None
6,13168-45F,Kaiser Permanente Healthcare Fund V,11246-23,Kaiser Permanente Ventures,None,None
7,13309-75F,Partners Innovation Fund,118715-50,Mass General Brigham Innovation,433710-46,Mass General Brigham Ventures
8,13492-36F,CHV III,11114-65,Ascension Ventures,None,None
9,13847-14F,MemorialCare Innovation Fund,56040-94,MemorialCare Innovation Fund,None,None
10,13943-26F,Kaiser Permanente Ventures Fund,11246-23,Kaiser Permanente Ventures,None,None
11,15463-27F,Healthcare Innovation Fund,151167-52,Ochsner Lafayette General,None,None
12,15744-88F,CHV IV,11114-65,Ascension Ventures,None,None
13,15786-10F,Partners Innovation Fund II,433710-46,Mass General Brigham Ventures,118715-50,Mass General Brigham Innovation
14,15958-81F,OSF Ventures Fund,160041-88,OSF Ventures,None,None
15,16054-75F,Providence Ventures Fund,123677-56,Providence Ventures,None,None
16,16134-04F,TMC Venture Fund,109795-69,Texas Medical Center,None,None
17,16527-61F,Providence Ventures Fund II,123677-56,Providence Ventures,None,None
18,16624-63F,UnityPoint Health Ventures Innovation Fund,61215-67,UnityPoint Health,None,None
19,16701-67F,OSF Ventures II,160041-88,OSF Ventures,None,None
20,16855-39F,Artificial Intelligence and Digital Translatio...,50987-17,Mass General Brigham,118715-50,Mass General Brigham Innovation
21,16885-63F,Mayo Benefactors Innovation Fund,55757-98,Mayo Clinic Ventures,None,None
22,16929-91F,KPV Fund V,11246-23,Kaiser Permanente Ventures,None,None
23,17324-11F,Orlando Health Ventures I,96517-54,Orlando Health,None,None
24,17580-43F,Intermountain Ventures Fund,266690-26,Intermountain Ventures,None,None
25,18303-94F,Mass General Brigham Fund III,433710-46,Mass General Brigham Ventures,None,None
26,22402-36F,Healthcare Collaboration Fund,433943-74,University Hospitals Ventures,None,None

In [23]:
grouped.shape

(27, 6)

In [24]:
df_selected_funds_2 = pd.merge(df_selected_funds, grouped, left_on = var.fund_id, right_on = var.investor_fund_id,
                               how = 'outer')
df_selected_funds_2

,FundID,FundName,FundFormerName,FundNo,FirstFund,Investor,InvestorWebsite,Vintage,FundStatus,FundSize,...,PreferredEBIT,PreferredRevenue,PreferredInvestmentHorizon,LastUpdated,InvestorFundID,InvestorFundName,InvestorID_1,InvestorName_1,InvestorID_2,InvestorName_2
0,11004-85F,Ascension Health Ventures,None,1,Yes (Ascension Ventures),Ascension Ventures,Ascension Ventures (www.ascensionventures.org),2001.0,Closed,125.00,...,None,None,None,01/30/2023,11004-85F,Ascension Health Ventures,11114-65,Ascension Ventures,None,None
1,11195-11F,KP Healthcare Fund I,None,1,Yes (Kaiser Permanente Ventures),Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2000.0,Closed,20.00,...,None,None,None,01/30/2023,NaN,NaN,NaN,NaN,NaN,NaN
2,11195-20F,KP Healthcare Fund II,None,2,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2002.0,Closed,10.00,...,None,None,None,01/30/2023,11195-20F,KP Healthcare Fund II,11246-23,Kaiser Permanente Ventures,None,None
3,11195-29F,Kaiser Permanente Healthcare Side Fund,None,3,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2004.0,Closed,20.20,...,None,None,None,01/30/2023,11195-29F,Kaiser Permanente Healthcare Side Fund,11246-23,Kaiser Permanente Ventures,None,None
4,11195-38F,Kaiser Permanente Healthcare Fund III,None,4,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2005.0,Closed,10.00,...,None,None,None,01/30/2023,11195-38F,Kaiser Permanente Healthcare Fund III,11246-23,Kaiser Permanente Ventures,None,None
5,11195-47F,Kaiser Permanente Healthcare Fund IV,None,5,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2006.0,Closed,20.00,...,None,None,None,01/30/2023,11195-47F,Kaiser Permanente Healthcare Fund IV,11246-23,Kaiser Permanente Ventures,None,None
6,11715-58F,CHV II,None,2,None,Ascension Ventures,Ascension Ventures (www.ascensionventures.org),2007.0,Closed,200.00,...,None,None,None,01/30/2023,11715-58F,CHV II,11114-65,Ascension Ventures,None,None
7,13168-45F,Kaiser Permanente Healthcare Fund V,None,6,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2008.0,Closed,120.00,...,None,None,None,01/30/2023,13168-45F,Kaiser Permanente Healthcare Fund V,11246-23,Kaiser Permanente Ventures,None,None
8,13309-75F,Partners Innovation Fund,None,"1 (Mass General Brigham Innovation), 1 (Mass G...",Yes (Mass General Brigham Ventures),"Mass General Brigham Innovation, Mass General ...",Mass General Brigham Innovation (innovation.ma...,2016.0,Closed,171.00,...,None,None,None,05/06/2023,13309-75F,Partners Innovation Fund,118715-50,Mass General Brigham Innovation,433710-46,Mass General Brigham Ventures
9,13492-36F,CHV III,None,3,None,Ascension Ventures,Ascension Ventures (www.ascensionventures.org),2013.0,Closed,225.00,...,None,None,None,05/12/2023,13492-36F,CHV III,11114-65,Ascension Ventures,None,None
10,13847-14F,MemorialCare Innovation Fund,None,1,Yes (MemorialCare Innovation Fund),MemorialCare Innovation Fund,MemorialCare Innovation Fund (www.memorialcare...,2013.0,Closed,150.00,...,None,None,None,02/04/2023,13847-14F,MemorialCare Innovation Fund,56040-94,MemorialCare Innovation Fund,None,None
11,13943-26F,Kaiser Permanente Ventures Fund,None,7,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2011.0,Closed,170.00,...,None,None,None,03/07/2023,13943-26F,Kaiser Permanente Ventures Fund,11246-23,Kaiser Permanente Ventures,None,None
12,15463-27F,Healthcare Innovation Fund,None,1,Yes (Ochsner Lafayette General),Ochsner Lafayette General,Ochsner Lafayette General (www.ochsnerlg.org),NaN,Closed,2.50,...,None,None,None,05/06/2023,15463-27F,Healthcare Innovation Fund,151167-52,Ochsner Lafayette General,None,None
13,15744-88F,CHV IV,None,4,None,Ascension Ventures,Ascension Ventures (www.ascensionventures.org),2017.0,Closed,255.00,...,None,None,None,05/12/2023,15744-88F,CHV IV,11114-65,Ascension Ventures,None,None
14,15786-10F,Partners Innovation Fund II,None,"2 (Mass General Brigham Innovation), 2 (Mass G...",None,"Mass General Brigham Innovation, Mass General ...",Mass General Brigham Innovation (innovation.ma...,2016.0,Closed,171.00,...,None,None,None,05/06/2023,15786-10F,Partners Innovation Fund II,433710-46,Mass General Brigham Ventures,118715-50,Mass General Brigham Innovation
15,15958-81F,OSF Ventures Fund,None,1,Yes (OSF Ventures),OSF Ventures,OSF Ventures (www.osfventures.org),2017.0,Closed,NaN,...,None,None,None,05/06/2023,15958-81F,OSF Ventures Fund,160041-88,OSF Ventures,None,None
16,16054-75F,Providence Ventures Fund,None,1,Yes (Providence Ventures),Providence Ventures,Providence Ventures (www.providenceventures.org),2014.0,Closed,150.00,...,None,None,None,05/14/2023,16054-75F,Providence Ventures Fund,123677-56,Providence Ventures,None,None
17,16134-04F,TMC Venture Fund,None,1,Yes (Texas Medical Center),Texas Medical Center,Texas Medical Center (www.tmc.edu),2017.0,Closed,25.00,...,None,None,None,05/14/2023,16134-04F,TMC Venture Fund,109795-69,Texas Medical Center,None,None
18,16527-61F,Providence Ventures Fund II,None,2,None,Providence Ventures,Providence Ventures (www.providenceventures.org),2019.0,Closed,150.00,...,None,None,None,05/14/2023,16527-61F,Providence Ventures Fund II,123677-56,Providence Ventures,None,None
19,16624-63F,UnityPoint Health Ventures Innovation Fund,None,1,Yes (UnityPoint Health),UnityPoint Health,UnityPoint Health (www.unitypoint.org),2020.0,Closed,NaN,...,None,None,None,01/30/2023,16624-63F,UnityPoint Health Ventures Innovation Fund,61215-67,UnityPoint Health,None,None
20,16701-67F,OSF Ventures II,None,2,None,OSF Ventures,OSF Ventures (www.osfventures.org),2019.0,Closed,75.00,...,None,None,None,05/06/2023,16701-67F,OSF Ventures II,160041-88,OSF Ventures,None,None
21,16855-39F,Artificial Intelligence and Digital Translatio...,None,"1 (Mass General Brigham), 3 (Mass General Brig...",Yes (Mass General Brigham),"Mass General Brigham, Mass General Brigham Inn...",Mass General Brigham (www.massgeneralbrigham.o...,2019.0,Closed,30.00,...,None,None,None,01/30/2023,16855-39F,Artificial Intelligence and Digital Translatio...,50987-17,Mass General Brigham,118715-50,Mass General Brigham Innovation
22,16855-48F,Translational Innovation Fund,None,"2 (Mass General Brigham), 4 (Mass General Brig...",None,"Mass General Brigham, Mass General Brigham Inn...",Mass General Brigham (www.massgeneralbrigham.o...,2019.0,Closed,50.00,...,None,None,None,01/30/2023,NaN,NaN,NaN,NaN,NaN,NaN
23,16885-63F,Mayo Benefactors Innovation Fund,None,1,Yes (Mayo Clinic Ventures),Mayo Clinic Ventures,Mayo Clinic Ventures (ventures.mayoclinic.org),2020.0,Closed,NaN,...,None,None,None,02/08/2023,16885-63F,Mayo Benefactors Innovation Fund,55757-98,Mayo Clinic Ventures,None,None
24,16929-91F,KPV Fund V,None,8,None,Kaiser Permanente Ventures,Kaiser Permanente Ventures (www.kpventures.com),2019.0,Closed,141.00,...,None,None,None,03/07/2023,16929-91F,KPV Fund V,11246-23,Kaiser Permanente Ventures,None,None
25,17324-11F,Orlando Health Ventures I,None,1,Yes (Orlando Health),Orlando Health,Orlando Health (www.orlandohealth.com),NaN,Closed,21.25,...,None,None,None,05/06/2023,17324-11F,Orlando Health Ventures I,96517-54,Orlando Health,None,None
26,17559-19F,Collaborative Health Ventures V,None,5,None,Ascension Ventures,Ascension Ventures (www.ascensionventures.org),2021.0,Closed,285.00,...,None,None,None,05/12/2023,NaN,NaN,NaN,NaN,NaN,NaN
27,17580-43F,Intermountain Ventures Fund,None,1,Yes (Intermountain Ventures),Intermountain Ventures,Intermountain Ventures (intermountainventures....,NaN,Closed,NaN,...,None,None,None,05/06/2023,17580-43F,Intermountain Ventures Fund,266690-26,Intermountain Ventures,None,None
28,18303-94F,Mass General Brigham Fund III,None,3,None,Mass General Brigham Ventures,Mass General Brigham Ventures (www.massgeneral...,2021.0,Closed,NaN,...,None,None,None,05/06/2023,18303-94F,Mass General Brigham Fund III,433710-46,Mass General Brigham Ventures,None,None
29,20618-65F,OSF Ventures III,None,3,None,OSF Ventures,OSF Ventures (www.osfventures.org),NaN,Open,NaN,...,None,None,None,05/06/2023,NaN,NaN,NaN,NaN,NaN,NaN
30,22073-86F,Orlando Health Ventures II,None,2,None,Orlando Health,Orlando Health (www.orlandohealth.com),NaN,Open,125.00,...,None,None,None,05/06/2023,NaN,NaN,NaN,NaN,NaN,NaN
31,22402-18F,UH Ventures (off-Balance sheet),None,1,None,University Hospitals Ventures,University Hospitals Ventures (ventures.uhhosp...,NaN,Evergreen,NaN,...,None,None,None,05/06/2023,NaN,NaN,NaN,NaN,NaN,NaN
32,22402-36F,Healthcare Collaboration Fund,None,2,None,University Hospitals Ventures,University Hospitals Ventures (ventures.uhhosp...,2021.0,Closed,8.00,...,None,None,None,05/06/2023,22402-36F,Healthcare Collaboration Fund,433943-74,University Hospitals Ventures,None,None

In [33]:
df_selected_funds_2.to_excel(file.dm_p030_10__selected_funds__xl, index = False)