In [102]:
import sys
import pandas as pd
import numpy as np
from pathlib import Path

sys.modules.pop('a20_config.a10_config', None)  # force reload
from a20_config.a10_config import dyr, file, const, var

Path.cwd()

PosixPath('/sharedata/camm/c_projects/i100_g7__VC_arms')

I go through the media list and search for hospital names on Pitchbook website and write down the IDs from the Pitchbook
using that ID I should be able to find all the subsidiaries from the Pitchbook

- What should I write down when I am searching for hospitals?
  - The less the better if you have a field in the data that shows it is a hospital that's enough for checking the data no one read my notes or any thing to make sure how I exactly matched hospitals

In [50]:
# names from media list: https://www.beckershospitalreview.com/healthcare-information-technology/innovation/22-health-systems-with-investment-arms/
h_n = {}
# Pitchbook IDs
h_id = {}
# Pitchbook URL
url = {}
# Pitchbook enitity type, derived from URL
type_pb = {}
# IsHospital, my judgment of it is a hopsital or health system, 1 for True, 0 for False
is_h = {}

# 1
h_n[1] = "Ascension (St. Louis): Ascension Ventures"
h_id[1] = "51614-92"
url[1] = 'https://my.pitchbook.com/profile/51614-92/company/profile#deal-lenders'
type_pb[1] = 'com'
is_h[1] = 1

# 2
h_n[2] = "Ballad Health (Johnson City, Tenn.): Ballad Ventures"
h_id[2] = "166514-86"
url[2] = 'https://my.pitchbook.com/profile/166514-86/company/profile#comparisons'
type_pb[2] = 'com'
is_h[2] = 1

# 3
h_n[3] = "Cleveland Clinic: Cleveland Clinic Ventures"
h_id[3] = "127260-28"
url[3] = 'https://my.pitchbook.com/profile/127260-28/investor/profile#general-info'
type_pb[3] = 'inv'
is_h[3] = 1

# 4
h_n[4] = "Elmhurst Memorial Hospital (Warrenville, Ill.): Edward-Elmhurst Health Venture Capital"
h_id[4] = "159211-27"
url[4] = 'https://my.pitchbook.com/profile/159211-27/company/profile#ai-summary'
type_pb[4] = 'com'
is_h[4] = 1

# 5
h_n[5] = "Henry Ford Health System (Detroit): Henry Ford Innovations"
h_id[5] = "100427-41"
url[5] = 'https://my.pitchbook.com/profile/100427-41/company/profile#comparisons'
type_pb[5] = 'com'
is_h[5] = 1

# 6
h_n[6] = "Intermountain Healthcare (Salt Lake City): Intermountain Ventures Fund"
h_id[6] = "185503-60"
url[6] = 'https://my.pitchbook.com/profile/185503-60/company/profile#ai-summary'
type_pb[6] = 'com'
is_h[6] = 1

# 7
h_n[7] = "Indiana University Health (Indianapolis): CHV Capital"
h_id[7] = "150350-41"
url[7] = 'https://my.pitchbook.com/profile/150350-41/company/profile'
type_pb[7] = 'com'
is_h[7] = 1

# 8
h_n[8] = "Jefferson Health (Philadelphia): Jefferson Innovation"
h_id[8] = "188107-03"
url[8] = 'https://my.pitchbook.com/profile/188107-03/investor/profile#general-info'
type_pb[8] = 'inv'
is_h[8] = 1

# 9
h_n[9] = "Kaiser Permanente (Oakland, Calif.): Kaiser Permanente Ventures"
h_id[9] = '229125-07'
url[9] = 'https://my.pitchbook.com/profile/229125-07/investor/profile#general-info'
type_pb[9] = 'inv'
is_h[9] = 1

# 10
h_n[10] = "Ochsner Lafayette (La.) General Health: Healthcare Innovation Fund"
h_id[10] = "151167-52"
url[10] = 'https://my.pitchbook.com/profile/151167-52/investor/profile#general-info'
type_pb[10] = 'inv'
is_h[10] = 1

# 11
h_n[11] = "Mayo Clinic (Rochester, Minn.): Mayo Clinic Ventures"
h_id[11] = "51726-52"
url[11] = 'https://my.pitchbook.com/profile/51726-52/limited-partner/profile#commitments-by-fund-type'
type_pb[11] = 'lp'
is_h[11] = 1

# 12
h_n[12] = "MemorialCare (Long Beach, Calif.): MemorialCare Fund"
h_id[12] = "56084-95"
url[12] = 'https://my.pitchbook.com/profile/56084-95/company/profile#ai-summary'
type_pb[12] = 'com'
is_h[12] = 1

# 13
h_n[13] = "NewYork-Presbyterian (New York City): NYP Ventures"
h_id[13] = "64197-64"
url[13] = 'https://my.pitchbook.com/profile/64197-64/company/profile#insights'
type_pb[13] = 'com'
is_h[13] = 1

# 14
h_n[14] = "Northwell Health (New York City): Northwell Holdings"
h_id[14] = "169562-80"
url[14] = 'https://my.pitchbook.com/profile/169562-80/company/profile#clinical-trials'
type_pb[14] = 'com'
is_h[14] = 1

# 15
h_n[15] = "Orlando Health: Orlando Health Ventures"
h_id[15] = "96517-54"
url[15] = 'https://my.pitchbook.com/profile/96517-54/company/profile#timeline'
type_pb[15] = 'com'
is_h[15] = 1

# 16
h_n[16] = "OSF HealthCare (Peoria, Ill.): OSF Ventures"
h_id[16] = "265269-88"
url[16] = 'https://my.pitchbook.com/profile/265269-88/company/profile#ai-summary'
type_pb[16] = 'com'
is_h[16] = 1

# 17
h_n[17] = "Partners HealthCare (Boston): Partners Innovation Fund"
h_id[17] = "50987-17"
url[17] = 'https://my.pitchbook.com/profile/50987-17/company/profile#comparisons'
type_pb[17] = 'com'
is_h[17] = 1

# 18
h_n[18] = "Providence (Renton, Wash.): Providence Ventures"
h_id[18] = "64677-79"
url[18] = 'https://my.pitchbook.com/profile/64677-79/company/profile#insights'
type_pb[18] = 'com'
is_h[18] = 1

# 19
# Not a hospital, it is a VC no parent hospital should I keep it in the sample?
h_n[19] = "Texas Medical Center (Houston): TMC Venture Fund"
h_id[19] = "109795-69"
url[19] = 'https://my.pitchbook.com/profile/109795-69/company/profile#insights'
type_pb[19] = 'com'
is_h[19] = 0

# 20
h_n[20] = "UCI Health (Orange County, Calif.): UCI Health Innovation Fund"
h_id[20] = np.nan  # not found in PB
url[20] = np.nan
type_pb[20] = np.nan
is_h[20] = np.nan

# 21
h_n[21] = "UnityPoint Health (West Des Moines, Iowa): UnityPoint Health Ventures"
h_id[21] = "61215-67"
url[21] = 'https://my.pitchbook.com/profile/61215-67/company/profile#ai-summary'
type_pb[21] = 'com'
is_h[21] = 1

# 22
h_n[22] = "University Hospitals (Cleveland): UH Ventures"
h_id[22] = "55165-33"
url[22] = 'https://my.pitchbook.com/profile/55165-33/investor/profile#general-info'
type_pb[22] = 'inv'
is_h[22] = 1

# 23
h_n[23] = "UPMC (Pittsburgh): UPMC Enterprises"
h_id[23] = "58870-45"
url[23] = 'https://my.pitchbook.com/profile/58870-45/investor/profile#board-members'
type_pb[23] = 'inv'
is_h[23] = 1

- One question is where can I find it in the data, how it is classified in the data? Company, Investor or what?
- Which items are hospitals which items are venture capitals?

- what should I present at this point?
    - List of hospitals
        - Their calssification in the data as company, investor or what
            - use the URL to find out what type it is
        - some general information like name and other things
        - Decide which one is a hospital or not, manually for now
    - Any Affiliated VC company
        - By the ID and parent company relation maybe other relation types also
        - have the list of IDs in a column in the list of hospitals + have it in the parent column in VC company table
    - Any Affiliated Fund diretly
        - I pass this for now and just do the VC companies and ask my questions then in the next steps I would do that

- How should I creted these two data tables/frames as quickly as possible?
    - Getting results as quickly as possible is the goal so I just use the links for finding out what type of enitity it is for each of them
    - Then I read the right table and get the general information for it and have it in the data , explain I did it on purpose to keep the variable names separate
    - Then find all the VC companies that has one of the hospitals as their parent company and just send that.
- So find all the VC companies and send alongside the hospitals then ask questions and send the tables.
    - say I don't think it is enough but to send something and show the progress I send this
 
What I considered as hospitals? 
first groupby different types
- academic medical center like #3
- Operator of hospitals? like #8
- #9 : Kaiser Permanente is an integrated managed care consortium. The company also contracts with Kaiser Foundation hospitals and medical groups to provide medical and hospital services. It serves members in California, Colorado, Georgia, Hawaii, Maryland, Ohio, Oregon, Virginia, Washington and the District of Columbia. It was founded in 1945 and is headquartered in Pleasanton, California. It seeks to acquire other companies whose businesses can be integrated into its existing operations
- #11: Provider of not-for-profit healthcare services through its community-owned affiliated hospitals headquartered in Lafayette, Louisiana. The company offers a range of services like bariatric surgery and weight loss, breast care, cancer care, ophthalmology, primary care as well as surgery services intending to improve the health of all of its communities and to serve its patients better.


Why do I have the is hospital column? 
- If I am counting all of them as hospital why I have that column? keep the code for now, just drop it when I am creating the dataframe then after finding out about the hospital types that we want to consider then decide what to do with that.

In [51]:
print(h_n)

{1: 'Ascension (St. Louis): Ascension Ventures', 2: 'Ballad Health (Johnson City, Tenn.): Ballad Ventures', 3: 'Cleveland Clinic: Cleveland Clinic Ventures', 4: 'Elmhurst Memorial Hospital (Warrenville, Ill.): Edward-Elmhurst Health Venture Capital', 5: 'Henry Ford Health System (Detroit): Henry Ford Innovations', 6: 'Intermountain Healthcare (Salt Lake City): Intermountain Ventures Fund', 7: 'Indiana University Health (Indianapolis): CHV Capital', 8: 'Jefferson Health (Philadelphia): Jefferson Innovation', 9: 'Kaiser Permanente (Oakland, Calif.): Kaiser Permanente Ventures', 10: 'Ochsner Lafayette (La.) General Health: Healthcare Innovation Fund', 11: 'Mayo Clinic (Rochester, Minn.): Mayo Clinic Ventures', 12: 'MemorialCare (Long Beach, Calif.): MemorialCare Fund', 13: 'NewYork-Presbyterian (New York City): NYP Ventures', 14: 'Northwell Health (New York City): Northwell Holdings', 15: 'Orlando Health: Orlando Health Ventures', 16: 'OSF HealthCare (Peoria, Ill.): OSF Ventures', 17: 'Partners HealthCare (Boston): Partners Innovation Fund', 18: 'Providence (Renton, Wash.): Providence Ventures', 19: 'Texas Medical Center (Houston): TMC Venture Fund', 20: 'UCI Health (Orange County, Calif.): UCI Health Innovation Fund', 21: 'UnityPoint Health (West Des Moines, Iowa): UnityPoint Health Ventures', 22: 'University Hospitals (Cleveland): UH Ventures', 23: 'UPMC (Pittsburgh): UPMC Enterprises'}

In [52]:
# assert only 1 row found from the right table
# read general data from the right table for each of the hospitals
data = {
        var.name_from_media: h_n.values(),
        var.pb_id          : h_id.values(),
        var.pb_url         : url.values(),
        var.pb_type        : type_pb.values(),
}

df = pd.DataFrame(data = data)

In [53]:
df_com = pd.read_parquet(file.pb_companies__parq)
df_inv = pd.read_parquet(file.pb_investor__parq)
df_lp = pd.read_parquet(file.pb_limited_partners__parq)

In [54]:
df_com

,CompanyID,CompanyName,CompanyAlsoKnownAs,CompanyFormerName,CompanyLegalName,Description,Keywords,CompanyFinancingStatus,CompanyFinancingStatusDate,TotalRaised,...,LastFinancingDebtSize,LastFinancingDebtDate,LastFinancingStatus,LastInvestmentInvestorOwnership,FacebookProfileURL,TwitterProfileURL,LinkedInProfileURL,PitchBookProfileLink,MorningstarID,LastUpdated
0,10010-89,Broadcom (Acquired 2016),None,None,Broadcom Corp.,Manufacturer of semiconductors. The company de...,"ethernet communication, fabless semiconductor,...",Formerly VC-backed,02/01/2016,66.360000,...,15600.0,02/01/2016,Completed,NaN,None,None,None,https://my.pitchbook.com?c=10010-89,0C00000711,01/30/2023
1,187998-49,Matador Film,None,None,None,Operator of media production company. The comp...,"media production, scriptwriting, tv series pro...",Corporate Backed or Acquired,08/29/2017,NaN,...,NaN,08/29/2017,Completed,NaN,None,None,None,https://my.pitchbook.com?c=187998-49,None,05/06/2023
2,10011-16,Acetex,None,None,Acetex Corporation,"Manufacturer of acetic acid in Vancouver, Cana...","acetic acid, acid derivative, pharmaceutical",Corporate Backed or Acquired,07/20/2005,4.247384,...,NaN,07/20/2005,Completed,NaN,None,None,https://www.linkedin.com/company/8322399,https://my.pitchbook.com?c=10011-16,None,04/26/2023
3,187998-58,Chronicle Studio,None,None,None,Provider of web development services intended ...,"web application developer, web developer's pla...",Accelerator/Incubator Backed,None,0.050000,...,NaN,None,Completed,NaN,https://www.facebook.com/TeamChronicle,https://twitter.com/teamchronicle,https://www.linkedin.com/company/chronicle-studio,https://my.pitchbook.com?c=187998-58,None,01/30/2023
4,10011-43,Basic Energy Services,Basic,Sierra Well Service,Basic Energy Services Inc,Basic Energy Services Inc is a provider of wel...,"contract drilling, water logistics, water logi...",Formerly PE-Backed,10/01/2021,50.000000,...,NaN,10/01/2021,Completed,NaN,None,None,None,https://my.pitchbook.com?c=10011-43,0C000006UZ,01/30/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
952979,12394-90,"Martin, Shudt, Wallace, DiLorenzo & Johnson",None,None,None,Provider of legal services catering to corpora...,"law firm, legal firm operator, legal service, ...",Corporate Backed or Acquired,10/01/2021,NaN,...,NaN,10/01/2021,Completed,NaN,None,None,None,https://my.pitchbook.com?c=12394-90,None,01/30/2023
952980,11705-23,3DGeo Development,3DGeo,None,"3DGeo Development, Inc.",Provider of advanced seismic imaging software ...,"seismic imaging, seismic inversion, spectral i...",Formerly PE-Backed,11/03/2008,NaN,...,NaN,11/03/2008,Completed,NaN,None,None,None,https://my.pitchbook.com?c=11705-23,None,01/30/2023
952981,390019-51,Cooper Glass Company,None,None,Cooper Glass Company LLC,Provider of residential and commercial glass s...,"commercial glass product, commercial glass ser...",Corporate Backed or Acquired,02/20/2020,NaN,...,NaN,02/20/2020,Completed,NaN,https://www.facebook.com/Cooper-Glass-Company-...,None,https://www.linkedin.com/company/cooper-glass-...,https://my.pitchbook.com?c=390019-51,None,05/06/2023
952982,12230-92,Pinnacle Electronics,None,"Contraves, Contraves Goerz Corporation",Pinnacle Electronics LLC,Manufacturer of high-reliability electronic as...,"cable, circuit, circuit assembly, electromecha...",Formerly PE-Backed,01/22/2016,NaN,...,NaN,01/22/2016,Completed,NaN,None,None,None,https://my.pitchbook.com?c=12230-92,None,01/30/2023
952983,12011-59,Palombo's Med-Rite Pharmacy,Palombos Med-Rite Pharmacy,None,None,Provider of pharmacy services. The company off...,"ancillary management, care, consultancy, healt...",Formerly PE-Backed,01/01/2006,NaN,...,NaN,01/01/2006,Completed,NaN,None,None,None,https://my.pitchbook.com?c=12011-59,None,01/30/2023

In [56]:
df_com_1 = df_com.copy()
df_com_1.columns = const.com_dot + df_com_1.columns
df_com_1.columns

Index(['Company.CompanyID', 'Company.CompanyName',
       'Company.CompanyAlsoKnownAs', 'Company.CompanyFormerName',
       'Company.CompanyLegalName', 'Company.Description', 'Company.Keywords',
       'Company.CompanyFinancingStatus', 'Company.CompanyFinancingStatusDate',
       'Company.TotalRaised', 'Company.TotalRaisedNativeAmount',
       'Company.TotalRaisedNativeCurrency', 'Company.BusinessStatus',
       'Company.BusinessStatusDate', 'Company.OwnershipStatus',
       'Company.OwnershipStatusDate', 'Company.Universe', 'Company.Website',
       'Company.Employees', 'Company.EmployeeAsOfDate',
       'Company.DescriptionShort', 'Company.Exchange', 'Company.Ticker',
       'Company.YearFounded', 'Company.ParentCompany',
       'Company.ParentCompanyID', 'Company.FinancingStatusNote',
       'Company.FinancingStatusNoteAsOfDate', 'Company.CikCode',
       'Company.PrimaryIndustrySector', 'Company.PrimaryIndustryGroup',
       'Company.PrimaryIndustryCode', 'Company.AllIndustries',
       'Company.Verticals', 'Company.EmergingSpaces', 'Company.HQLocation',
       'Company.HQAddressLine1', 'Company.HQAddressLine2', 'Company.HQCity',
       'Company.HQState_Province', 'Company.HQPostCode', 'Company.HQCountry',
       'Company.HQPhone', 'Company.HQFax', 'Company.HQEmail',
       'Company.HQGlobalRegion', 'Company.HQGlobalSubRegion',
       'Company.AlternateOfficeCount', 'Company.ActiveInvestors',
       'Company.FormerInvestors', 'Company.Revenue', 'Company.GrossProfit',
       'Company.NetIncome', 'Company.EnterpriseValue', 'Company.EBITDA',
       'Company.EBIT', 'Company.NetDebt', 'Company.FiscalPeriod',
       'Company.PeriodEndDate', 'Company.FirstFinancingDealID',
       'Company.FirstFinancingDate', 'Company.FirstFinancingSize',
       'Company.FirstFinancingSizeStatus', 'Company.FirstFinancingValuation',
       'Company.FirstFinancingValuationStatus',
       'Company.FirstFinancingDealType', 'Company.FirstFinancingDealType2',
       'Company.FirstFinancingDealType3', 'Company.FirstFinancingDealClass',
       'Company.FirstFinancingDebt', 'Company.FirstFinancingDebtSize',
       'Company.FirstFinancingDebtDate', 'Company.FirstFinancingStatus',
       'Company.LastKnownValuation', 'Company.LastKnownValuationDate',
       'Company.LastKnownValuationDealType', 'Company.LastFinancingDealID',
       'Company.LastFinancingDate', 'Company.LastFinancingSize',
       'Company.LastFinancingSizeStatus', 'Company.LastFinancingValuation',
       'Company.LastFinancingValuationStatus', 'Company.LastFinancingDealType',
       'Company.LastFinancingDealType2', 'Company.LastFinancingDealType3',
       'Company.LastFinancingDealClass', 'Company.LastFinancingDebt',
       'Company.LastFinancingDebtSize', 'Company.LastFinancingDebtDate',
       'Company.LastFinancingStatus',
       'Company.LastInvestmentInvestorOwnership', 'Company.FacebookProfileURL',
       'Company.TwitterProfileURL', 'Company.LinkedInProfileURL',
       'Company.PitchBookProfileLink', 'Company.MorningstarID',
       'Company.LastUpdated'],
      dtype='object')

In [57]:
df_1 = pd.merge(df, df_com_1, left_on = var.pb_id, right_on = var.com_dot__company_id, how = 'left')
df_1

,NameFromMedia,PBID,PBURL,PBEntityType,Company.CompanyID,Company.CompanyName,Company.CompanyAlsoKnownAs,Company.CompanyFormerName,Company.CompanyLegalName,Company.Description,...,Company.LastFinancingDebtSize,Company.LastFinancingDebtDate,Company.LastFinancingStatus,Company.LastInvestmentInvestorOwnership,Company.FacebookProfileURL,Company.TwitterProfileURL,Company.LinkedInProfileURL,Company.PitchBookProfileLink,Company.MorningstarID,Company.LastUpdated
0,Ascension (St. Louis): Ascension Ventures,51614-92,https://my.pitchbook.com/profile/51614-92/comp...,com,51614-92,Ascension Health,Ascension,None,None,Provider of a health system intended to provid...,...,NaN,10/01/2019,Completed,NaN,https://www.facebook.com/ascensionorg,https://twitter.com/ascensionorg,https://www.linkedin.com/company/ascensionorg,https://my.pitchbook.com?c=51614-92,None,05/05/2023
1,"Ballad Health (Johnson City, Tenn.): Ballad Ve...",166514-86,https://my.pitchbook.com/profile/166514-86/com...,com,166514-86,Ballad Health,Better Together,"Wellmont Health System, Mountain States Health...",None,Provider of healthcare services intended to of...,...,NaN,09/19/2017,Completed,NaN,None,None,None,https://my.pitchbook.com?c=166514-86,None,05/06/2023
2,Cleveland Clinic: Cleveland Clinic Ventures,127260-28,https://my.pitchbook.com/profile/127260-28/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Elmhurst Memorial Hospital (Warrenville, Ill.)...",159211-27,https://my.pitchbook.com/profile/159211-27/com...,com,159211-27,Edward-Elmhurst Health,"EEH, Edward-Elmhurst",None,None,Operator of general medical and surgical hospi...,...,NaN,01/05/2022,Completed,NaN,https://www.facebook.com/healthydriven,https://twitter.com/healthydriven,https://www.linkedin.com/company/edward-hospital,https://my.pitchbook.com?c=159211-27,None,05/06/2023
4,Henry Ford Health System (Detroit): Henry Ford...,100427-41,https://my.pitchbook.com/profile/100427-41/com...,com,100427-41,Henry Ford Health System,"Henry Ford, HFHS",None,"Henry Ford Health System, Inc.",Henry Ford Health System is a health care prov...,...,NaN,05/21/2013,Failed/Cancelled,NaN,https://www.facebook.com/HenryFordHealth/,https://twitter.com/henryfordhealth,https://www.linkedin.com/company/8936,https://my.pitchbook.com?c=100427-41,None,01/30/2023
5,Intermountain Healthcare (Salt Lake City): Int...,185503-60,https://my.pitchbook.com/profile/185503-60/com...,com,185503-60,Intermountain Healthcare,Intermountain,None,"Intermountain Healthcare, Inc.",Operator of a non-profit healthcare system of ...,...,NaN,05/29/2020,Completed,NaN,https://www.facebook.com/Intermountain,https://twitter.com/Intermountain,https://www.linkedin.com/company/intermountain...,https://my.pitchbook.com?c=185503-60,None,03/23/2023
6,Indiana University Health (Indianapolis): CHV ...,150350-41,https://my.pitchbook.com/profile/150350-41/com...,com,150350-41,IU Health La Porte Hospital,None,None,None,Operator of a hospital. The company owns and o...,...,NaN,03/01/2016,Completed,NaN,https://www.facebook.com/LPHospital,None,https://www.linkedin.com/company/laporte-hospital,https://my.pitchbook.com?c=150350-41,None,05/04/2023
7,Jefferson Health (Philadelphia): Jefferson Inn...,188107-03,https://my.pitchbook.com/profile/188107-03/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"Kaiser Permanente (Oakland, Calif.): Kaiser Pe...",229125-07,https://my.pitchbook.com/profile/229125-07/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Ochsner Lafayette (La.) General Health: Health...,151167-52,https://my.pitchbook.com/profile/151167-52/inv...,inv,151167-52,Ochsner Lafayette General,None,Lafayette General Health,"Lafayette General Health System, Inc.",Provider of not-for-profit healthcare services...,...,NaN,10/01/2020,Completed,NaN,https://www.facebook.com/OchsnerLafayetteGeneral,https://twitter.com/lafgeneral,https://www.linkedin.com/company/ochsner-lafay...,https://my.pitchbook.com?c=151167-52,None,05/06/2023
10,"Mayo Clinic (Rochester, Minn.): Mayo Clinic Ve...",51726-52,https://my.pitchbook.com/profile/51726-52/limi...,lp,51726-52,Mayo Clinic,None,None,None,Provider of patient care services intended to ...,...,NaN,10/31/2019,Completed,NaN,https://www.facebook.com/MayoClinic,https://twitter.com/mayoclinic,https://www.linkedin.com/company/mayo-clinic,https://my.pitchbook.com?c=51726-52,None,05/12/2023
11,"MemorialCare (Long Beach, Calif.): MemorialCar...",56084-95,https://my.pitchbook.com/profile/56084-95/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NewYork-Presbyterian (New York City): NYP Vent...,64197-64,https://my.pitchbook.com/profile/64197-64/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Northwell Health (New York City): Northwell Ho...,169562-80,https://my.pitchbook.com/profile/169562-80/com...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Orlando Health: Orlando Health Ventures,96517-54,https://my.pitchbook.com/profile/96517-54/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,"OSF HealthCare (Peoria, Ill.): OSF Ventures",265269-88,https://my.pitchbook.com/profile/265269-88/com...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Partners HealthCare (Boston): Partners Innovat...,50987-17,https://my.pitchbook.com/profile/50987-17/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,"Providence (Renton, Wash.): Providence Ventures",64677-79,https://my.pitchbook.com/profile/64677-79/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Texas Medical Center (Houston): TMC Venture Fund,109795-69,https://my.pitchbook.com/profile/109795-69/com...,com,109795-69,Texas Medical Center,"TMCx, TMC",None,None,Operator of a medical complex. The company has...,...,1.713402,04/11/2020,Completed,NaN,https://www.facebook.com/texasmedcenter,https://twitter.com/TXMedCenter,https://www.linkedin.com/company/texas-medical...,https://my.pitchbook.com?c=109795-69,None,05/04/2023
19,"UCI Health (Orange County, Calif.): UCI Health...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"UnityPoint Health (West Des Moines, Iowa): Uni...",61215-67,https://my.pitchbook.com/profile/61215-67/comp...,com,61215-67,UnityPoint Health,Iowa Health System,None,None,Provider of healthcare services based in West ...,...,NaN,None,Upcoming,NaN,https://www.facebook.com/unitypointhealth,https://twitter.com/UnityPointNews,https://www.linkedin.com/company/iowa-methodis...,https://my.pitchbook.com?c=61215-67,None,05/17/2023
21,University Hospitals (Cleveland): UH Ventures,55165-33,https://my.pitchbook.com/profile/55165-33/inve...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,UPMC (Pittsburgh): UPMC Enterprises,58870-45,https://my.pitchbook.com/profile/58870-45/inve...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
# make sure there is only 1 row is merged not more
# also make sure other types than 'com' has no data after merge all should be nan

# if no extra rows is matched then the whole df rows must be the same as before

assert len(df_1) == len(df)

# pass

# others should be not matched
# msk = df_1[var.pb_type].ne(const.com)
# assert df_1.loc[msk, var.com_dot__company_id].isna().all()

# Assertion Error, Learning: two items number 9 and 10 that are inv and lp are present in the company data, doesn't seem to make sense but that's how it is
# so I should check it doesn't come from multiple tables at least
# to see where it matched I create helper columns for this
msk = df_1[var.com_dot__company_id].notna()
df_1.loc[msk, var.matched_from_com] = True
df_1

,NameFromMedia,PBID,PBURL,PBEntityType,Company.CompanyID,Company.CompanyName,Company.CompanyAlsoKnownAs,Company.CompanyFormerName,Company.CompanyLegalName,Company.Description,...,Company.LastFinancingDebtDate,Company.LastFinancingStatus,Company.LastInvestmentInvestorOwnership,Company.FacebookProfileURL,Company.TwitterProfileURL,Company.LinkedInProfileURL,Company.PitchBookProfileLink,Company.MorningstarID,Company.LastUpdated,Matched_From_Com
0,Ascension (St. Louis): Ascension Ventures,51614-92,https://my.pitchbook.com/profile/51614-92/comp...,com,51614-92,Ascension Health,Ascension,None,None,Provider of a health system intended to provid...,...,10/01/2019,Completed,NaN,https://www.facebook.com/ascensionorg,https://twitter.com/ascensionorg,https://www.linkedin.com/company/ascensionorg,https://my.pitchbook.com?c=51614-92,None,05/05/2023,True
1,"Ballad Health (Johnson City, Tenn.): Ballad Ve...",166514-86,https://my.pitchbook.com/profile/166514-86/com...,com,166514-86,Ballad Health,Better Together,"Wellmont Health System, Mountain States Health...",None,Provider of healthcare services intended to of...,...,09/19/2017,Completed,NaN,None,None,None,https://my.pitchbook.com?c=166514-86,None,05/06/2023,True
2,Cleveland Clinic: Cleveland Clinic Ventures,127260-28,https://my.pitchbook.com/profile/127260-28/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Elmhurst Memorial Hospital (Warrenville, Ill.)...",159211-27,https://my.pitchbook.com/profile/159211-27/com...,com,159211-27,Edward-Elmhurst Health,"EEH, Edward-Elmhurst",None,None,Operator of general medical and surgical hospi...,...,01/05/2022,Completed,NaN,https://www.facebook.com/healthydriven,https://twitter.com/healthydriven,https://www.linkedin.com/company/edward-hospital,https://my.pitchbook.com?c=159211-27,None,05/06/2023,True
4,Henry Ford Health System (Detroit): Henry Ford...,100427-41,https://my.pitchbook.com/profile/100427-41/com...,com,100427-41,Henry Ford Health System,"Henry Ford, HFHS",None,"Henry Ford Health System, Inc.",Henry Ford Health System is a health care prov...,...,05/21/2013,Failed/Cancelled,NaN,https://www.facebook.com/HenryFordHealth/,https://twitter.com/henryfordhealth,https://www.linkedin.com/company/8936,https://my.pitchbook.com?c=100427-41,None,01/30/2023,True
5,Intermountain Healthcare (Salt Lake City): Int...,185503-60,https://my.pitchbook.com/profile/185503-60/com...,com,185503-60,Intermountain Healthcare,Intermountain,None,"Intermountain Healthcare, Inc.",Operator of a non-profit healthcare system of ...,...,05/29/2020,Completed,NaN,https://www.facebook.com/Intermountain,https://twitter.com/Intermountain,https://www.linkedin.com/company/intermountain...,https://my.pitchbook.com?c=185503-60,None,03/23/2023,True
6,Indiana University Health (Indianapolis): CHV ...,150350-41,https://my.pitchbook.com/profile/150350-41/com...,com,150350-41,IU Health La Porte Hospital,None,None,None,Operator of a hospital. The company owns and o...,...,03/01/2016,Completed,NaN,https://www.facebook.com/LPHospital,None,https://www.linkedin.com/company/laporte-hospital,https://my.pitchbook.com?c=150350-41,None,05/04/2023,True
7,Jefferson Health (Philadelphia): Jefferson Inn...,188107-03,https://my.pitchbook.com/profile/188107-03/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"Kaiser Permanente (Oakland, Calif.): Kaiser Pe...",229125-07,https://my.pitchbook.com/profile/229125-07/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Ochsner Lafayette (La.) General Health: Health...,151167-52,https://my.pitchbook.com/profile/151167-52/inv...,inv,151167-52,Ochsner Lafayette General,None,Lafayette General Health,"Lafayette General Health System, Inc.",Provider of not-for-profit healthcare services...,...,10/01/2020,Completed,NaN,https://www.facebook.com/OchsnerLafayetteGeneral,https://twitter.com/lafgeneral,https://www.linkedin.com/company/ochsner-lafay...,https://my.pitchbook.com?c=151167-52,None,05/06/2023,True
10,"Mayo Clinic (Rochester, Minn.): Mayo Clinic Ve...",51726-52,https://my.pitchbook.com/profile/51726-52/limi...,lp,51726-52,Mayo Clinic,None,None,None,Provider of patient care services intended to ...,...,10/31/2019,Completed,NaN,https://www.facebook.com/MayoClinic,https://twitter.com/mayoclinic,https://www.linkedin.com/company/mayo-clinic,https://my.pitchbook.com?c=51726-52,None,05/12/2023,True
11,"MemorialCare (Long Beach, Calif.): MemorialCar...",56084-95,https://my.pitchbook.com/profile/56084-95/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NewYork-Presbyterian (New York City): NYP Vent...,64197-64,https://my.pitchbook.com/profile/64197-64/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Northwell Health (New York City): Northwell Ho...,169562-80,https://my.pitchbook.com/profile/169562-80/com...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Orlando Health: Orlando Health Ventures,96517-54,https://my.pitchbook.com/profile/96517-54/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,"OSF HealthCare (Peoria, Ill.): OSF Ventures",265269-88,https://my.pitchbook.com/profile/265269-88/com...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Partners HealthCare (Boston): Partners Innovat...,50987-17,https://my.pitchbook.com/profile/50987-17/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,"Providence (Renton, Wash.): Providence Ventures",64677-79,https://my.pitchbook.com/profile/64677-79/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Texas Medical Center (Houston): TMC Venture Fund,109795-69,https://my.pitchbook.com/profile/109795-69/com...,com,109795-69,Texas Medical Center,"TMCx, TMC",None,None,Operator of a medical complex. The company has...,...,04/11/2020,Completed,NaN,https://www.facebook.com/texasmedcenter,https://twitter.com/TXMedCenter,https://www.linkedin.com/company/texas-medical...,https://my.pitchbook.com?c=109795-69,None,05/04/2023,True
19,"UCI Health (Orange County, Calif.): UCI Health...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"UnityPoint Health (West Des Moines, Iowa): Uni...",61215-67,https://my.pitchbook.com/profile/61215-67/comp...,com,61215-67,UnityPoint Health,Iowa Health System,None,None,Provider of healthcare services based in West ...,...,None,Upcoming,NaN,https://www.facebook.com/unitypointhealth,https://twitter.com/UnityPointNews,https://www.linkedin.com/company/iowa-methodis...,https://my.pitchbook.com?c=61215-67,None,05/17/2023,True
21,University Hospitals (Cleveland): UH Ventures,55165-33,https://my.pitchbook.com/profile/55165-33/inve...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,UPMC (Pittsburgh): UPMC Enterprises,58870-45,https://my.pitchbook.com/profile/58870-45/inve...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
# msk_1 = df_1[var.pb_type].ne(const.com)
# msk_1 &= df_1[var.com_dot__company_id].notna()

# dfa = df_1[msk_1]
# dfa

In [60]:
# pd.isnull(dfa.loc[2, 'Company.CompanyID'])

In [61]:
df_inv_1 = df_inv.copy()
df_inv_1.columns = const.inv_dot + df_inv_1.columns
df_inv_1.columns

Index(['Investor.InvestorID', 'Investor.InvestorName',
       'Investor.InvestorAlsoKnownAs', 'Investor.InvestorFormerName',
       'Investor.InvestorLegalName', 'Investor.Description',
       'Investor.InvestorStatus', 'Investor.PrimaryInvestorType',
       'Investor.OtherInvestorTypes', 'Investor.AUM',
       ...
       'Investor.LastFinancingDebt', 'Investor.LastFinancingDebtDate',
       'Investor.LastInvestmentStatus', 'Investor.LastClosedFundName',
       'Investor.LastClosedFundVintage', 'Investor.LastClosedFundSize',
       'Investor.LastClosedFundType', 'Investor.LastClosedFundCloseDate',
       'Investor.LastClosedFundOpenDate', 'Investor.LastUpdated'],
      dtype='object', length=114)

In [62]:
df_2 = pd.merge(df_1, df_inv_1, left_on = var.pb_id, right_on = var.inv_dot__investor_id, how = 'left')
df_2

,NameFromMedia,PBID,PBURL,PBEntityType,Company.CompanyID,Company.CompanyName,Company.CompanyAlsoKnownAs,Company.CompanyFormerName,Company.CompanyLegalName,Company.Description,...,Investor.LastFinancingDebt,Investor.LastFinancingDebtDate,Investor.LastInvestmentStatus,Investor.LastClosedFundName,Investor.LastClosedFundVintage,Investor.LastClosedFundSize,Investor.LastClosedFundType,Investor.LastClosedFundCloseDate,Investor.LastClosedFundOpenDate,Investor.LastUpdated
0,Ascension (St. Louis): Ascension Ventures,51614-92,https://my.pitchbook.com/profile/51614-92/comp...,com,51614-92,Ascension Health,Ascension,None,None,Provider of a health system intended to provid...,...,None,01/24/2023,Completed,Catholic Health Ventures II,2007.0,120.00,Venture - General,01/01/2007,None,05/09/2023
1,"Ballad Health (Johnson City, Tenn.): Ballad Ve...",166514-86,https://my.pitchbook.com/profile/166514-86/com...,com,166514-86,Ballad Health,Better Together,"Wellmont Health System, Mountain States Health...",None,Provider of healthcare services intended to of...,...,None,05/01/2020,Completed,None,NaN,NaN,None,None,None,02/02/2023
2,Cleveland Clinic: Cleveland Clinic Ventures,127260-28,https://my.pitchbook.com/profile/127260-28/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,None,05/17/2023,Completed,None,NaN,NaN,None,None,None,05/18/2023
3,"Elmhurst Memorial Hospital (Warrenville, Ill.)...",159211-27,https://my.pitchbook.com/profile/159211-27/com...,com,159211-27,Edward-Elmhurst Health,"EEH, Edward-Elmhurst",None,None,Operator of general medical and surgical hospi...,...,None,03/31/2022,Completed,None,NaN,NaN,None,None,None,04/26/2023
4,Henry Ford Health System (Detroit): Henry Ford...,100427-41,https://my.pitchbook.com/profile/100427-41/com...,com,100427-41,Henry Ford Health System,"Henry Ford, HFHS",None,"Henry Ford Health System, Inc.",Henry Ford Health System is a health care prov...,...,None,09/15/2021,Completed,None,NaN,NaN,None,None,None,05/06/2023
5,Intermountain Healthcare (Salt Lake City): Int...,185503-60,https://my.pitchbook.com/profile/185503-60/com...,com,185503-60,Intermountain Healthcare,Intermountain,None,"Intermountain Healthcare, Inc.",Operator of a non-profit healthcare system of ...,...,None,03/23/2023,Completed,None,NaN,NaN,None,None,None,05/06/2023
6,Indiana University Health (Indianapolis): CHV ...,150350-41,https://my.pitchbook.com/profile/150350-41/com...,com,150350-41,IU Health La Porte Hospital,None,None,None,Operator of a hospital. The company owns and o...,...,None,05/01/2017,Completed,None,NaN,NaN,None,None,None,05/04/2023
7,Jefferson Health (Philadelphia): Jefferson Inn...,188107-03,https://my.pitchbook.com/profile/188107-03/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,None,11/16/2021,Completed,None,NaN,NaN,None,None,None,05/16/2023
8,"Kaiser Permanente (Oakland, Calif.): Kaiser Pe...",229125-07,https://my.pitchbook.com/profile/229125-07/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,None,03/15/2018,Completed,None,NaN,NaN,None,None,None,05/06/2023
9,Ochsner Lafayette (La.) General Health: Health...,151167-52,https://my.pitchbook.com/profile/151167-52/inv...,inv,151167-52,Ochsner Lafayette General,None,Lafayette General Health,"Lafayette General Health System, Inc.",Provider of not-for-profit healthcare services...,...,None,09/15/2022,Completed,Healthcare Innovation Fund,NaN,2.50,Venture Capital - Early Stage,None,01/01/2016,05/06/2023
10,"Mayo Clinic (Rochester, Minn.): Mayo Clinic Ve...",51726-52,https://my.pitchbook.com/profile/51726-52/limi...,lp,51726-52,Mayo Clinic,None,None,None,Provider of patient care services intended to ...,...,None,05/01/2023,Announced/In Progress,None,NaN,NaN,None,None,None,05/18/2023
11,"MemorialCare (Long Beach, Calif.): MemorialCar...",56084-95,https://my.pitchbook.com/profile/56084-95/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,None,07/21/2021,Completed,None,NaN,NaN,None,None,None,04/20/2023
12,NewYork-Presbyterian (New York City): NYP Vent...,64197-64,https://my.pitchbook.com/profile/64197-64/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,None,01/09/2017,Completed,None,NaN,NaN,None,None,None,02/14/2023
13,Northwell Health (New York City): Northwell Ho...,169562-80,https://my.pitchbook.com/profile/169562-80/com...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,None,04/18/2023,Completed,None,NaN,NaN,None,None,None,05/06/2023
14,Orlando Health: Orlando Health Ventures,96517-54,https://my.pitchbook.com/profile/96517-54/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,None,05/09/2023,Completed,Orlando Health Ventures I,NaN,21.25,Buyout,None,03/16/2020,05/17/2023
15,"OSF HealthCare (Peoria, Ill.): OSF Ventures",265269-88,https://my.pitchbook.com/profile/265269-88/com...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,None,05/05/2023,Completed,None,NaN,NaN,None,None,None,05/14/2023
16,Partners HealthCare (Boston): Partners Innovat...,50987-17,https://my.pitchbook.com/profile/50987-17/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,None,02/27/2023,Completed,Translational Innovation Fund,2019.0,50.00,Venture - General,10/21/2019,10/21/2019,05/17/2023
17,"Providence (Renton, Wash.): Providence Ventures",64677-79,https://my.pitchbook.com/profile/64677-79/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,None,03/14/2016,Completed,PHS Ventures,2014.0,150.00,Venture Capital - Early Stage,09/22/2014,None,05/17/2023
18,Texas Medical Center (Houston): TMC Venture Fund,109795-69,https://my.pitchbook.com/profile/109795-69/com...,com,109795-69,Texas Medical Center,"TMCx, TMC",None,None,Operator of a medical complex. The company has...,...,None,01/23/2023,Completed,TMC Venture Fund,2017.0,25.00,Venture Capital - Early Stage,11/08/2017,None,05/18/2023
19,"UCI Health (Orange County, Calif.): UCI Health...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"UnityPoint Health (West Des Moines, Iowa): Uni...",61215-67,https://my.pitchbook.com/profile/61215-67/comp...,com,61215-67,UnityPoint Health,Iowa Health System,None,None,Provider of healthcare services based in West ...,...,None,10/02/2021,Completed,UnityPoint Health Ventures Innovation Fund,2020.0,NaN,Venture Capital - Early Stage,12/31/2020,05/23/2019,04/11/2023
21,University Hospitals (Cleveland): UH Ventures,55165-33,https://my.pitchbook.com/profile/55165-33/inve...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,None,07/23/2018,Completed,None,NaN,NaN,None,None,None,03/09/2023
22,UPMC (Pittsburgh): UPMC Enterprises,58870-45,https://my.pitchbook.com/profile/58870-45/inve...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,None,03/13/2023,Completed,None,NaN,NaN,None,None,None,05/12/2023

In [63]:
# no new rows 
assert len(df_2) == len(df)

msk = df_2[var.inv_dot__investor_id].notna()
df_2.loc[msk, var.matched_from_inv] = True
df_2;

In [64]:
df_lp

,LimitedPartnerID,LimitedPartnerName,LimitedPartnerFormerName,LimitedPartnerAlsoKnownAs,Description,LimitedPartnerType,AUM,YearFounded,Website,HQLocation,...,TargetEquitiesPercentMax,TargetFixedIncomeMin,TargetFixedIncomePercentMin,TargetFixedIncomeMax,TargetFixedIncomePercentMax,TargetCashMin,TargetCashPercentMin,TargetCashMax,TargetCashPercentMax,LastUpdated
0,10014-49,Blackstone,The Blackstone Group,Blackstone Strategic Partner,The Blackstone Group is an investment advisory...,Investment Advisor,9.510000e+05,1985.0,www.blackstone.com,"New York, NY",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/03/2023
1,11951-65,Amundi Investment Solutions,Credit Agricole Structured Asset Management Ad...,Amundi IS,Amundi Investment Solutions (Amundi IS) was a ...,Money Management Firm,NaN,2005.0,None,"Paris, France",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
2,10018-18,J.P. Morgan,None,None,J.P. Morgan is a banking institution based in ...,Banking Institution,3.840000e+06,1895.0,www.jpmorgan.com,"New York, NY",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02/16/2023
3,11997-01,VIG Partners,Vogo Investment Group,None,VIG Partners is a direct investment firm based...,Direct Investment,3.000000e+03,2005.0,www.vigpartners.com,"Seoul, South Korea",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
4,10024-93,UBS Group,Union Bank of Switzerland,UBS,"UBS is a banking institution based in Zurich, ...",Banking Institution,3.400000e+03,1998.0,www.ubs.com,"Zurich, Switzerland",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/18/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17458,225940-24,Kenneth Haas Revocable Trust,None,None,Kenneth Haas Revocable Trust is a private inve...,Private Investment Fund,NaN,NaN,None,"Columbus, OH",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
17459,52585-75,Pension Plan of Carpenters Health & Welfare an...,None,None,Pension Plan of Carpenters Health & Welfare an...,Union Pension Fund,NaN,1965.0,None,"Philadelphia, PA",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
17460,187046-65,Muhammad M. Al Ghariba,None,None,Muhammad M. Al Ghariba is a high-net-worth inv...,High-net-worth investor,NaN,NaN,None,"London, United Kingdom",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
17461,58838-50,Chipstone Foundation,None,None,Chipstone Foundation is an independent non-pro...,Foundation,8.216481e+01,1966.0,www.chipstone.org,"Milwaukee, WI",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/18/2023
17462,185601-70,Robert Shaw,None,None,Robert Shaw is a high-net-worth investor with ...,High-net-worth investor,NaN,NaN,None,"Edinburgh, United Kingdom",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023

In [65]:
df_lp_1 = df_lp.copy()
df_lp_1.columns = const.lp_dot + df_lp_1.columns
df_lp_1.columns;

In [66]:
df_3 = pd.merge(df_2, df_lp_1, left_on = var.pb_id, right_on = var.lp_dot__lp_id, how = 'left')
df_3

,NameFromMedia,PBID,PBURL,PBEntityType,Company.CompanyID,Company.CompanyName,Company.CompanyAlsoKnownAs,Company.CompanyFormerName,Company.CompanyLegalName,Company.Description,...,LimitedPartner.TargetEquitiesPercentMax,LimitedPartner.TargetFixedIncomeMin,LimitedPartner.TargetFixedIncomePercentMin,LimitedPartner.TargetFixedIncomeMax,LimitedPartner.TargetFixedIncomePercentMax,LimitedPartner.TargetCashMin,LimitedPartner.TargetCashPercentMin,LimitedPartner.TargetCashMax,LimitedPartner.TargetCashPercentMax,LimitedPartner.LastUpdated
0,Ascension (St. Louis): Ascension Ventures,51614-92,https://my.pitchbook.com/profile/51614-92/comp...,com,51614-92,Ascension Health,Ascension,None,None,Provider of a health system intended to provid...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
1,"Ballad Health (Johnson City, Tenn.): Ballad Ve...",166514-86,https://my.pitchbook.com/profile/166514-86/com...,com,166514-86,Ballad Health,Better Together,"Wellmont Health System, Mountain States Health...",None,Provider of healthcare services intended to of...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Cleveland Clinic: Cleveland Clinic Ventures,127260-28,https://my.pitchbook.com/profile/127260-28/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Elmhurst Memorial Hospital (Warrenville, Ill.)...",159211-27,https://my.pitchbook.com/profile/159211-27/com...,com,159211-27,Edward-Elmhurst Health,"EEH, Edward-Elmhurst",None,None,Operator of general medical and surgical hospi...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Henry Ford Health System (Detroit): Henry Ford...,100427-41,https://my.pitchbook.com/profile/100427-41/com...,com,100427-41,Henry Ford Health System,"Henry Ford, HFHS",None,"Henry Ford Health System, Inc.",Henry Ford Health System is a health care prov...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Intermountain Healthcare (Salt Lake City): Int...,185503-60,https://my.pitchbook.com/profile/185503-60/com...,com,185503-60,Intermountain Healthcare,Intermountain,None,"Intermountain Healthcare, Inc.",Operator of a non-profit healthcare system of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Indiana University Health (Indianapolis): CHV ...,150350-41,https://my.pitchbook.com/profile/150350-41/com...,com,150350-41,IU Health La Porte Hospital,None,None,None,Operator of a hospital. The company owns and o...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Jefferson Health (Philadelphia): Jefferson Inn...,188107-03,https://my.pitchbook.com/profile/188107-03/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"Kaiser Permanente (Oakland, Calif.): Kaiser Pe...",229125-07,https://my.pitchbook.com/profile/229125-07/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Ochsner Lafayette (La.) General Health: Health...,151167-52,https://my.pitchbook.com/profile/151167-52/inv...,inv,151167-52,Ochsner Lafayette General,None,Lafayette General Health,"Lafayette General Health System, Inc.",Provider of not-for-profit healthcare services...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"Mayo Clinic (Rochester, Minn.): Mayo Clinic Ve...",51726-52,https://my.pitchbook.com/profile/51726-52/limi...,lp,51726-52,Mayo Clinic,None,None,None,Provider of patient care services intended to ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03/03/2023
11,"MemorialCare (Long Beach, Calif.): MemorialCar...",56084-95,https://my.pitchbook.com/profile/56084-95/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NewYork-Presbyterian (New York City): NYP Vent...,64197-64,https://my.pitchbook.com/profile/64197-64/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
13,Northwell Health (New York City): Northwell Ho...,169562-80,https://my.pitchbook.com/profile/169562-80/com...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Orlando Health: Orlando Health Ventures,96517-54,https://my.pitchbook.com/profile/96517-54/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,"OSF HealthCare (Peoria, Ill.): OSF Ventures",265269-88,https://my.pitchbook.com/profile/265269-88/com...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Partners HealthCare (Boston): Partners Innovat...,50987-17,https://my.pitchbook.com/profile/50987-17/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,"Providence (Renton, Wash.): Providence Ventures",64677-79,https://my.pitchbook.com/profile/64677-79/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Texas Medical Center (Houston): TMC Venture Fund,109795-69,https://my.pitchbook.com/profile/109795-69/com...,com,109795-69,Texas Medical Center,"TMCx, TMC",None,None,Operator of a medical complex. The company has...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03/30/2023
19,"UCI Health (Orange County, Calif.): UCI Health...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"UnityPoint Health (West Des Moines, Iowa): Uni...",61215-67,https://my.pitchbook.com/profile/61215-67/comp...,com,61215-67,UnityPoint Health,Iowa Health System,None,None,Provider of healthcare services based in West ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
21,University Hospitals (Cleveland): UH Ventures,55165-33,https://my.pitchbook.com/profile/55165-33/inve...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,UPMC (Pittsburgh): UPMC Enterprises,58870-45,https://my.pitchbook.com/profile/58870-45/inve...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023

In [67]:
# no new rows 
assert len(df_2) == len(df)

msk = df_3[var.lp_dot__lp_id].notna()
df_3.loc[msk, var.matched_from_lp] = True
df_3

,NameFromMedia,PBID,PBURL,PBEntityType,Company.CompanyID,Company.CompanyName,Company.CompanyAlsoKnownAs,Company.CompanyFormerName,Company.CompanyLegalName,Company.Description,...,LimitedPartner.TargetFixedIncomeMin,LimitedPartner.TargetFixedIncomePercentMin,LimitedPartner.TargetFixedIncomeMax,LimitedPartner.TargetFixedIncomePercentMax,LimitedPartner.TargetCashMin,LimitedPartner.TargetCashPercentMin,LimitedPartner.TargetCashMax,LimitedPartner.TargetCashPercentMax,LimitedPartner.LastUpdated,Matched_From_LP
0,Ascension (St. Louis): Ascension Ventures,51614-92,https://my.pitchbook.com/profile/51614-92/comp...,com,51614-92,Ascension Health,Ascension,None,None,Provider of a health system intended to provid...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023,True
1,"Ballad Health (Johnson City, Tenn.): Ballad Ve...",166514-86,https://my.pitchbook.com/profile/166514-86/com...,com,166514-86,Ballad Health,Better Together,"Wellmont Health System, Mountain States Health...",None,Provider of healthcare services intended to of...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Cleveland Clinic: Cleveland Clinic Ventures,127260-28,https://my.pitchbook.com/profile/127260-28/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Elmhurst Memorial Hospital (Warrenville, Ill.)...",159211-27,https://my.pitchbook.com/profile/159211-27/com...,com,159211-27,Edward-Elmhurst Health,"EEH, Edward-Elmhurst",None,None,Operator of general medical and surgical hospi...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Henry Ford Health System (Detroit): Henry Ford...,100427-41,https://my.pitchbook.com/profile/100427-41/com...,com,100427-41,Henry Ford Health System,"Henry Ford, HFHS",None,"Henry Ford Health System, Inc.",Henry Ford Health System is a health care prov...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Intermountain Healthcare (Salt Lake City): Int...,185503-60,https://my.pitchbook.com/profile/185503-60/com...,com,185503-60,Intermountain Healthcare,Intermountain,None,"Intermountain Healthcare, Inc.",Operator of a non-profit healthcare system of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Indiana University Health (Indianapolis): CHV ...,150350-41,https://my.pitchbook.com/profile/150350-41/com...,com,150350-41,IU Health La Porte Hospital,None,None,None,Operator of a hospital. The company owns and o...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Jefferson Health (Philadelphia): Jefferson Inn...,188107-03,https://my.pitchbook.com/profile/188107-03/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"Kaiser Permanente (Oakland, Calif.): Kaiser Pe...",229125-07,https://my.pitchbook.com/profile/229125-07/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Ochsner Lafayette (La.) General Health: Health...,151167-52,https://my.pitchbook.com/profile/151167-52/inv...,inv,151167-52,Ochsner Lafayette General,None,Lafayette General Health,"Lafayette General Health System, Inc.",Provider of not-for-profit healthcare services...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"Mayo Clinic (Rochester, Minn.): Mayo Clinic Ve...",51726-52,https://my.pitchbook.com/profile/51726-52/limi...,lp,51726-52,Mayo Clinic,None,None,None,Provider of patient care services intended to ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03/03/2023,True
11,"MemorialCare (Long Beach, Calif.): MemorialCar...",56084-95,https://my.pitchbook.com/profile/56084-95/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NewYork-Presbyterian (New York City): NYP Vent...,64197-64,https://my.pitchbook.com/profile/64197-64/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023,True
13,Northwell Health (New York City): Northwell Ho...,169562-80,https://my.pitchbook.com/profile/169562-80/com...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Orlando Health: Orlando Health Ventures,96517-54,https://my.pitchbook.com/profile/96517-54/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,"OSF HealthCare (Peoria, Ill.): OSF Ventures",265269-88,https://my.pitchbook.com/profile/265269-88/com...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Partners HealthCare (Boston): Partners Innovat...,50987-17,https://my.pitchbook.com/profile/50987-17/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,"Providence (Renton, Wash.): Providence Ventures",64677-79,https://my.pitchbook.com/profile/64677-79/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Texas Medical Center (Houston): TMC Venture Fund,109795-69,https://my.pitchbook.com/profile/109795-69/com...,com,109795-69,Texas Medical Center,"TMCx, TMC",None,None,Operator of a medical complex. The company has...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03/30/2023,True
19,"UCI Health (Orange County, Calif.): UCI Health...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"UnityPoint Health (West Des Moines, Iowa): Uni...",61215-67,https://my.pitchbook.com/profile/61215-67/comp...,com,61215-67,UnityPoint Health,Iowa Health System,None,None,Provider of healthcare services based in West ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023,True
21,University Hospitals (Cleveland): UH Ventures,55165-33,https://my.pitchbook.com/profile/55165-33/inve...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,UPMC (Pittsburgh): UPMC Enterprises,58870-45,https://my.pitchbook.com/profile/58870-45/inve...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023,True

so what now? what should I do next?
- I should do some checks on the data gathered for the hospitals to better understand it
but should I search the whole data for the VC arms? NO for now just search the companies and justify that for the most part I see that the owner is a hospital or a parent firm that owns both the hospital and make at least for example for any of these two things. justify that based on the things I found is that this type of relation I didn't search for the whole type of relations but I can do that although I doubt I would find more affiliations. so for now just find the VC arms related to them but mention this is not the whole affilations that we have, is it hard to search in all tables? yes just send this then do that later if needed.

In [68]:
df_3.head()

,NameFromMedia,PBID,PBURL,PBEntityType,Company.CompanyID,Company.CompanyName,Company.CompanyAlsoKnownAs,Company.CompanyFormerName,Company.CompanyLegalName,Company.Description,...,LimitedPartner.TargetFixedIncomeMin,LimitedPartner.TargetFixedIncomePercentMin,LimitedPartner.TargetFixedIncomeMax,LimitedPartner.TargetFixedIncomePercentMax,LimitedPartner.TargetCashMin,LimitedPartner.TargetCashPercentMin,LimitedPartner.TargetCashMax,LimitedPartner.TargetCashPercentMax,LimitedPartner.LastUpdated,Matched_From_LP
0,Ascension (St. Louis): Ascension Ventures,51614-92,https://my.pitchbook.com/profile/51614-92/comp...,com,51614-92,Ascension Health,Ascension,None,None,Provider of a health system intended to provid...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023,True
1,"Ballad Health (Johnson City, Tenn.): Ballad Ve...",166514-86,https://my.pitchbook.com/profile/166514-86/com...,com,166514-86,Ballad Health,Better Together,"Wellmont Health System, Mountain States Health...",None,Provider of healthcare services intended to of...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Cleveland Clinic: Cleveland Clinic Ventures,127260-28,https://my.pitchbook.com/profile/127260-28/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Elmhurst Memorial Hospital (Warrenville, Ill.)...",159211-27,https://my.pitchbook.com/profile/159211-27/com...,com,159211-27,Edward-Elmhurst Health,"EEH, Edward-Elmhurst",None,None,Operator of general medical and surgical hospi...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Henry Ford Health System (Detroit): Henry Ford...,100427-41,https://my.pitchbook.com/profile/100427-41/com...,com,100427-41,Henry Ford Health System,"Henry Ford, HFHS",None,"Henry Ford Health System, Inc.",Henry Ford Health System is a health care prov...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
df_3.shape

(23, 310)

In [70]:
# check only 1 of the matched columns should be 1 in each row and only 1 other should be NAN

cols = [var.matched_from_com, var.matched_from_inv, var.matched_from_lp]  # the subset of columns to check
val = True  # the value that exactly one column should equal

_df = df_3
mask = (
        _df[cols].notna().sum(axis = 1).eq(1)  # exactly one non-NaN among the subset
        & _df[cols].eq(val).any(axis = 1)  # and that non-NaN equals `val`
)

# rows that satisfy the condition:
df_valid = _df[mask]

# rows that do NOT satisfy the condition:
df_invalid = _df[~mask]

In [71]:
df_valid

,NameFromMedia,PBID,PBURL,PBEntityType,Company.CompanyID,Company.CompanyName,Company.CompanyAlsoKnownAs,Company.CompanyFormerName,Company.CompanyLegalName,Company.Description,...,LimitedPartner.TargetFixedIncomeMin,LimitedPartner.TargetFixedIncomePercentMin,LimitedPartner.TargetFixedIncomeMax,LimitedPartner.TargetFixedIncomePercentMax,LimitedPartner.TargetCashMin,LimitedPartner.TargetCashPercentMin,LimitedPartner.TargetCashMax,LimitedPartner.TargetCashPercentMax,LimitedPartner.LastUpdated,Matched_From_LP
2,Cleveland Clinic: Cleveland Clinic Ventures,127260-28,https://my.pitchbook.com/profile/127260-28/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Jefferson Health (Philadelphia): Jefferson Inn...,188107-03,https://my.pitchbook.com/profile/188107-03/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"Kaiser Permanente (Oakland, Calif.): Kaiser Pe...",229125-07,https://my.pitchbook.com/profile/229125-07/inv...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"MemorialCare (Long Beach, Calif.): MemorialCar...",56084-95,https://my.pitchbook.com/profile/56084-95/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Northwell Health (New York City): Northwell Ho...,169562-80,https://my.pitchbook.com/profile/169562-80/com...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Orlando Health: Orlando Health Ventures,96517-54,https://my.pitchbook.com/profile/96517-54/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,"OSF HealthCare (Peoria, Ill.): OSF Ventures",265269-88,https://my.pitchbook.com/profile/265269-88/com...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Partners HealthCare (Boston): Partners Innovat...,50987-17,https://my.pitchbook.com/profile/50987-17/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,"Providence (Renton, Wash.): Providence Ventures",64677-79,https://my.pitchbook.com/profile/64677-79/comp...,com,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,University Hospitals (Cleveland): UH Ventures,55165-33,https://my.pitchbook.com/profile/55165-33/inve...,inv,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
df_invalid[cols]

   Matched_From_Com Matched_From_Inv Matched_From_LP
0              True             True            True
1              True             True             NaN
3              True             True             NaN
4              True             True             NaN
5              True             True             NaN
6              True             True             NaN
9              True             True             NaN
10             True             True            True
12              NaN             True            True
18             True             True            True
19              NaN              NaN             NaN
20             True             True            True
22              NaN             True            True

**Learning**

Entities are not separately defined if something is defined as a company then it is not investor or limited partner it can be any of those

so now I want to find all the VC arms related to these entities I found for that I should find all the entities that has one of these IDs in their parent ID data field. from maybe different data tables in the PB data or maybe only the company table.

TODO:
- first look out the data fileds I found before to see what files, tables should I look into to find

- then after finding the right tables to search into them them filter those for the IDs and the right other data field that shows that enitiy is a VC  

- Should I then gather how many VC arms found for each of them and their IDs in a list? no need for that just for the sake of being quick and getting some results and report ASAP.

In [73]:
# [H]ospital [A]ffiliated entity dataframe to store found data from different PB data in it
df_ha = pd.DataFrame()
df_ha[var.hospital_id] = df_3[var.pb_id]
df_ha = df_ha.dropna()
df_ha

   HospitalID
0    51614-92
1   166514-86
2   127260-28
3   159211-27
4   100427-41
5   185503-60
6   150350-41
7   188107-03
8   229125-07
9   151167-52
10   51726-52
11   56084-95
12   64197-64
13  169562-80
14   96517-54
15  265269-88
16   50987-17
17   64677-79
18  109795-69
20   61215-67
21   55165-33
22   58870-45

In [83]:
df_ent_aff_rel = pd.read_parquet(file.pb_ent_aff_rel__parq)

print(df_ent_aff_rel.shape)
df_ent_aff_rel

(1622354, 11)

,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated
0,10011-61,52315-12,Ares Management,Asset Manager,"Los Angeles, CA",1997.0,Parent,Los Angeles,California,United States,01/30/2023
1,57113-56,132850-99,Edco Eindhoven,Distributors/Wholesale,"Eindhoven, Netherlands",1978.0,Parent,Eindhoven,None,Netherlands,01/30/2023
2,10010-89,42930-37,Gadzoox Networks,Storage (IT),"San Jose, CA",1992.0,Subsidiary,San Jose,California,United States,01/30/2023
3,57127-24,10358-29,Aurorium,Specialty Chemicals,"Indianapolis, IN",1856.0,Parent,Indianapolis,Indiana,United States,03/14/2023
4,10010-89,123134-23,M-Stream,Media and Information Services (B2B),"Nantes, France",2001.0,Subsidiary,Nantes,None,France,01/30/2023
...,...,...,...,...,...,...,...,...,...,...,...
1622349,482203-99,484327-81,Tandläkarhuset Enköping,Clinics/Outpatient Services,"Enkoping, Sweden",2013.0,Sister,Enkoping,None,Sweden,01/30/2023
1622350,482203-99,455009-77,LudvikaTandläkarna,Clinics/Outpatient Services,"Ludvika, Sweden",2019.0,Sister,Ludvika,None,Sweden,01/30/2023
1622351,482203-99,466763-77,Solna Dental,Clinics/Outpatient Services,"Stockholm, Sweden",2014.0,Sister,Stockholm,None,Sweden,01/30/2023
1622352,482203-99,225754-66,City Dental,Clinics/Outpatient Services,"Stockholm, Sweden",2005.0,Sister,Stockholm,None,Sweden,01/30/2023
1622353,482204-62,277203-34,Granted Consultancy,Other Service Provider Type,"Exeter, United Kingdom",2010.0,Sister,Exeter,England,United Kingdom,05/06/2023

In [86]:
_df = df_ent_aff_rel
msk = _df[var.entity_id].isin(df_ha[var.hospital_id])
df_e1 = _df[msk]
df_e1

,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated
9221,151167-52,361472-59,Acadia General Hospital,Hospitals/Inpatient Services,"Crowley, LA",2014.0,Subsidiary,Crowley,Louisiana,United States,05/06/2023
9233,151167-52,399434-32,Healthcare Innovation Fund,Corporate Venture Capital,"Lafayette, LA",NaN,Subsidiary,Lafayette,Louisiana,United States,05/06/2023
42882,56084-95,56040-94,MemorialCare Innovation Fund,Corporate Venture Capital,"Long Beach, CA",1993.0,Subsidiary,Long Beach,California,United States,01/30/2023
42886,56084-95,62952-67,Summation Health Ventures,Corporate Venture Capital,"Long Beach, CA",2014.0,Subsidiary,Long Beach,California,United States,01/30/2023
45098,150350-41,51450-31,CHV Capital,Venture Capital,"Indianapolis, IN",2007.0,Subsidiary,Indianapolis,Indiana,United States,01/30/2023
...,...,...,...,...,...,...,...,...,...,...,...
1530114,58870-45,244258-57,UPMC Western Maryland,Hospitals/Inpatient Services,"Cumberland, MD",1996.0,Subsidiary,Cumberland,Maryland,United States,01/30/2023
1530118,58870-45,160890-22,UPMC Enterprises,Corporate Venture Capital,"Pittsburgh, PA",2014.0,Subsidiary,Pittsburgh,Pennsylvania,United States,01/30/2023
1530122,58870-45,161879-41,Sports Surgery Clinic,Clinics/Outpatient Services,"Dublin, Ireland",2007.0,Subsidiary,Dublin,None,Ireland,03/15/2023
1530150,58870-45,290328-13,LifeSolutions,Hospitals/Inpatient Services,"Pittsburgh, PA",1997.0,Subsidiary,Pittsburgh,Pennsylvania,United States,03/16/2023
1530170,58870-45,160035-76,UPMC Susquehanna,Clinics/Outpatient Services,"Williamsport, PA",1994.0,Subsidiary,Williamsport,Pennsylvania,United States,01/30/2023

In [87]:
df_e1.shape

(75, 11)

In [88]:
_df = df_ent_aff_rel
msk = _df[var.aff_id].isin(df_ha[var.hospital_id])
df_e2 = _df[msk]
df_e2

,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated
6994,434783-53,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023
28857,433943-74,55165-33,University Hospitals,Acquirer,None,1866.0,Parent,None,None,None,05/06/2023
40286,56040-94,56084-95,MemorialCare Health System,Clinics/Outpatient Services,"Long Beach, CA",1907.0,Parent,Long Beach,California,United States,01/30/2023
43802,433710-46,50987-17,Mass General Brigham,Hospitals/Inpatient Services,"Boston, MA",1994.0,Parent,Boston,Massachusetts,United States,05/06/2023
44669,55757-98,51726-52,Mayo Clinic,Clinics/Outpatient Services,"Rochester, MN",1889.0,Parent,Rochester,Minnesota,United States,01/30/2023
61542,244258-57,58870-45,University of Pittsburgh Medical Center,Investor,"Pittsburgh, PA",1986.0,Parent,Pittsburgh,Pennsylvania,United States,05/06/2023
68373,527156-92,188107-03,Jefferson Health,Acquirer,"Philadelphia, PA",1877.0,Parent,Philadelphia,Pennsylvania,United States,05/06/2023
69003,527267-26,265269-88,OSF Healthcare,Clinics/Outpatient Services,"Peoria, IL",1877.0,Parent,Peoria,Illinois,United States,05/06/2023
102950,290328-13,58870-45,University of Pittsburgh Medical Center,Investor,"Pittsburgh, PA",1986.0,Parent,Pittsburgh,Pennsylvania,United States,03/16/2023
123130,525429-19,51614-92,Ascension Health,Clinics/Outpatient Services,"Saint Louis, MO",1999.0,Parent,Saint Louis,Missouri,United States,05/06/2023
141902,100288-72,185503-60,Intermountain Healthcare,Clinics/Outpatient Services,"Salt Lake City, UT",1975.0,Parent,Salt Lake City,Utah,United States,05/06/2023
184781,51292-81,64677-79,Providence Health Care,Clinics/Outpatient Services,"Vancouver, Canada",1997.0,Parent,Vancouver,British Columbia,Canada,01/30/2023
185545,51450-31,150350-41,IU Health La Porte Hospital,Hospitals/Inpatient Services,"La Porte, IN",1972.0,Parent,La Porte,Indiana,United States,01/30/2023
201922,98383-60,51726-52,Mayo Clinic,Clinics/Outpatient Services,"Rochester, MN",1889.0,Parent,Rochester,Minnesota,United States,02/03/2023
240816,97167-61,51614-92,Ascension Health,Clinics/Outpatient Services,"Saint Louis, MO",1999.0,Parent,Saint Louis,Missouri,United States,02/10/2023
242634,521701-84,64677-79,Providence Health Care,Clinics/Outpatient Services,"Vancouver, Canada",1997.0,Parent,Vancouver,British Columbia,Canada,05/06/2023
266329,331511-59,185503-60,Intermountain Healthcare,Clinics/Outpatient Services,"Salt Lake City, UT",1975.0,Parent,Salt Lake City,Utah,United States,01/30/2023
280490,142182-82,51726-52,Mayo Clinic,Clinics/Outpatient Services,"Rochester, MN",1889.0,Parent,Rochester,Minnesota,United States,05/06/2023
305081,188063-65,58870-45,University of Pittsburgh Medical Center,Investor,"Pittsburgh, PA",1986.0,Parent,Pittsburgh,Pennsylvania,United States,05/06/2023
360132,92342-62,58870-45,University of Pittsburgh Medical Center,Investor,"Pittsburgh, PA",1986.0,Parent,Pittsburgh,Pennsylvania,United States,01/30/2023
421516,185286-07,55165-33,University Hospitals,Acquirer,None,1866.0,Parent,None,None,None,01/30/2023
520470,88455-70,188107-03,Jefferson Health,Acquirer,"Philadelphia, PA",1877.0,Parent,Philadelphia,Pennsylvania,United States,05/06/2023
564224,512264-53,169562-80,Northwell Health,Hospitals/Inpatient Services,"New Hyde Park, NY",1997.0,Parent,New Hyde Park,New York,United States,01/30/2023
631474,227329-84,159211-27,Edward-Elmhurst Health,Hospitals/Inpatient Services,"Naperville, IL",2013.0,Sister,Naperville,Illinois,United States,01/30/2023
787365,221543-56,64197-64,NewYork-Presbyterian Hospital,Foundation,"New York, NY",1998.0,Parent,New York,New York,United States,01/30/2023
802604,362629-81,265269-88,OSF Healthcare,Clinics/Outpatient Services,"Peoria, IL",1877.0,Parent,Peoria,Illinois,United States,05/06/2023
806565,268046-92,61215-67,UnityPoint Health,Corporation,"West Des Moines, IA",1994.0,Parent,West Des Moines,Iowa,United States,05/06/2023
847523,266690-26,185503-60,Intermountain Healthcare,Clinics/Outpatient Services,"Salt Lake City, UT",1975.0,Parent,Salt Lake City,Utah,United States,05/06/2023
882072,265871-98,229125-07,Permanente Medicine,Clinics/Outpatient Services,"Oakland, CA",1997.0,Parent,Oakland,California,United States,05/06/2023
900718,123725-62,64677-79,Providence Health Care,Clinics/Outpatient Services,"Vancouver, Canada",1997.0,Parent,Vancouver,British Columbia,Canada,01/30/2023
900724,123731-65,64677-79,Providence Health Care,Clinics/Outpatient Services,"Vancouver, Canada",1997.0,Parent,Vancouver,British Columbia,Canada,01/30/2023
982838,357417-64,127260-28,Cleveland Clinic,Acquirer,"Cleveland, OH",1921.0,Parent,Cleveland,Ohio,United States,01/30/2023
1000590,120829-78,64677-79,Providence Health Care,Clinics/Outpatient Services,"Vancouver, Canada",1997.0,Parent,Vancouver,British Columbia,Canada,01/30/2023
1014010,356844-34,159211-27,Edward-Elmhurst Health,Hospitals/Inpatient Services,"Naperville, IL",2013.0,Sister,Naperville,Illinois,United States,05/06/2023
1060152,118715-50,50987-17,Mass General Brigham,Hospitals/Inpatient Services,"Boston, MA",1994.0,Parent,Boston,Massachusetts,United States,05/06/2023
1060414,118843-03,100427-41,Henry Ford Health System,Hospitals/Inpatient Services,"Detroit, MI",1915.0,Parent,Detroit,Michigan,United States,05/06/2023
1067593,448678-45,169562-80,Northwell Health,Hospitals/Inpatient Services,"New Hyde Park, NY",1997.0,Parent,New Hyde Park,New York,United States,05/06/2023
1106095,399434-32,151167-52,Ochsner Lafayette General,Hospitals/Inpatient Services,"Lafayette, LA",1911.0,Parent,Lafayette,Louisiana,United States,05/06/2023
1143278,209544-22,58870-45,University of Pittsburgh Medical Center,Investor,"Pittsburgh, PA",1986.0,Parent,Pittsburgh,Pennsylvania,United States,05/06/2023
1146227,161879-41,58870-45,University of Pittsburgh Medical Center,Investor,"Pittsburgh, PA",1986.0,Parent,Pittsburgh,Pennsylvania,United States,03/15/2023
1180594,160890-22,58870-45,University of Pittsburgh Medical Center,Investor,"Pittsburgh, PA",1986.0,Parent,Pittsburgh,Pennsylvania,United States,01/30/2023
1185461,160671-43,169562-80,Northwell Health,Hospitals/Inpatient Services,"New Hyde Park, NY",1997.0,Parent,New Hyde Park,New York,United States,05/06/2023
1206677,160035-76,58870-45,University of Pittsburgh Medical Center,Investor,"Pittsburgh, PA",1986.0,Parent,Pittsburgh,Pennsylvania,United States,01/30/2023
1206749,160041-88,265269-88,OSF Healthcare,Clinics/Outpatient Services,"Peoria, IL",1877.0,Parent,Peoria,Illinois,United States,05/06/2023
1283378,158836-15,51726-52,Mayo Clinic,Clinics/Outpatient Services,"Rochester, MN",1889.0,Parent,Rochester,Minnesota,United States,05/06/2023
1325521,62921-17,159211-27,Edward-Elmhurst Health,Hospitals/Inpatient Services,"Naperville, IL",2013.0,Subsidiary,Naperville,Illinois,United States,01/30/2023
1326827,62952-67,56084-95,MemorialCare Health System,Clinics/Outpatient Services,"Long Beach, CA",1907.0,Parent,Long Beach,California,United States,01/30/2023
1364789,61712-74,265269-88,OSF Healthcare,Clinics/Outpatient Services,"Peoria, IL",1877.0,Parent,Peoria,Illinois,United States,01/30/2023
1365425,108883-18,51726-52,Mayo Clinic,Clinics/Outpatient Services,"Rochester, MN",1889.0,Parent,Rochester,Minnesota,United States,01/30/2023
1380574,61552-45,96517-54,Orlando Health,Hospitals/Inpatient Services,"Orlando, FL",1918.0,Parent,Orlando,Florida,United States,01/30/2023
1520674,58865-23,185503-60,Intermountain Healthcare,Clinics/Outpatient Services,"Salt Lake City, UT",1975.0,Parent,Salt Lake City,Utah,United States,01/30/2023
1542292,58606-12,50987-17,Mass General Brigham,Hospitals/Inpatient Services,"Boston, MA",1994.0,Parent,Boston,Massachusetts,United States,01/30/2023
1544583,11114-65,51614-92,Ascension Health,Clinics/Outpatient Services,"Saint Louis, MO",1999.0,Parent,Saint Louis,Missouri,United States,01/30/2023
1544927,11246-23,229125-07,Permanente Medicine,Clinics/Outpatient Services,"Oakland, CA",1997.0,Parent,Oakland,California,United States,01/30/2023
1560278,10937-35,51614-92,Ascension Health,Clinics/Outpatient Services,"Saint Louis, MO",1999.0,Parent,Saint Louis,Missouri,United States,01/30/2023
1591445,340845-76,127260-28,Cleveland Clinic,Acquirer,"Cleveland, OH",1921.0,Parent,Cleveland,Ohio,United States,01/30/2023
1594867,482380-93,159211-27,Edward-Elmhurst Health,Hospitals/Inpatient Services,"Naperville, IL",2013.0,Parent,Naperville,Illinois,United States,05/06/2023

In [89]:
df_e2.shape

(57, 11)

In [90]:
# do we have all the entity ID from e2 in the affiliate ID from e1?

df_e2[var.entity_id].isin(df_e1[var.aff_id]).all()

# yes we have it so only consider it one way

np.True_

In [91]:
df_e1[var.aff_type].unique()

array(['Subsidiary', 'Parent', 'Sister'], dtype=object)

In [92]:
df_e1[var.aff_type].value_counts()

AffiliateType
Subsidiary    71
Parent         2
Sister         2
Name: count, dtype: int64

In [93]:
df_e1[var.industry].value_counts()

Industry
Corporate Venture Capital       17
Hospitals/Inpatient Services    14
Corporate Pension               13
Clinics/Outpatient Services     10
Foundation                       7
Venture Capital                  3
Acquirer                         2
Elder and Disabled Care          1
Managed Care                     1
Monitoring Equipment             1
Accelerator/Incubator            1
Private Investment Fund          1
Buildings and Property           1
Air                              1
Other Commercial Services        1
Biotechnology                    1
Name: count, dtype: int64

In [94]:
df_inv.head()

,InvestorID,InvestorName,InvestorAlsoKnownAs,InvestorFormerName,InvestorLegalName,Description,InvestorStatus,PrimaryInvestorType,OtherInvestorTypes,AUM,...,LastFinancingDebt,LastFinancingDebtDate,LastInvestmentStatus,LastClosedFundName,LastClosedFundVintage,LastClosedFundSize,LastClosedFundType,LastClosedFundCloseDate,LastClosedFundOpenDate,LastUpdated
0,10010-89,Broadcom (Acquired 2016),None,None,Broadcom Corp.,"Broadcom was a designer, developer and global ...",Acquired/Merged,Corporation,None,NaN,...,Other,11/17/2017,Completed,None,NaN,NaN,None,None,None,01/30/2023
1,56752-21,Invertec,None,None,None,Invertec was a Spain based venture capital fir...,Out of Business,Venture Capital,None,NaN,...,None,04/20/2010,Completed,None,NaN,NaN,None,None,None,01/30/2023
2,10011-79,Charterhouse Equity Partners,Charterhouse,None,"Charterhouse Equity Partners, LLC",Charterhouse Equity Partners was a private equ...,Out of Business,PE/Buyout,Growth/Expansion,NaN,...,None,02/03/2020,Completed,Charterhouse Equity Partners IV,2005.0,447.0,Buyout,12/31/2003,05/02/2003,04/04/2023
3,56853-46,IQ Partners,IQ Partners Sp. z o.o.,None,IQ Partners S.A.,"Founded in 2011, IQ Partners was a venture cap...",Out of Business,Venture Capital,None,NaN,...,None,03/14/2018,Completed,EREMIE fund Seed,2017.0,NaN,Venture Capital - Early Stage,12/31/2017,None,05/18/2023
4,10011-61,Ares Private Equity Group,Ares,None,Ares Capital Management LLC,"Founded in 1997, Ares Private Equity Group is ...",Actively Seeking New Investments,PE/Buyout,"Growth/Expansion, Infrastructure, Real Estate",33400.0,...,None,05/11/2023,Announced/In Progress,None,NaN,NaN,None,None,None,05/17/2023

In [95]:
msk = df_inv[var.parent_com_id].isin(df_ha[var.hospital_id])

df_inv_1 = df_inv[msk]

df_inv_1

,InvestorID,InvestorName,InvestorAlsoKnownAs,InvestorFormerName,InvestorLegalName,Description,InvestorStatus,PrimaryInvestorType,OtherInvestorTypes,AUM,...,LastFinancingDebt,LastFinancingDebtDate,LastInvestmentStatus,LastClosedFundName,LastClosedFundVintage,LastClosedFundSize,LastClosedFundType,LastClosedFundCloseDate,LastClosedFundOpenDate,LastUpdated
11711,55757-98,Mayo Clinic Ventures,MCV,None,None,"Founded in 1986, Mayo Clinic Ventures is the c...",Actively Seeking New Investments,Venture Capital,Corporate Venture Capital,NaN,...,None,05/17/2023,Completed,Mayo Benefactors Innovation Fund,2020.0,NaN,Venture - General,01/01/2020,None,05/18/2023
13004,340845-76,Cleveland Clinic Ventures,CCV,None,None,"Founded in 2016, Cleveland Clinic Ventures is ...",Actively Seeking New Investments,Corporate Venture Capital,None,NaN,...,None,06/27/2022,Completed,None,NaN,NaN,None,None,None,04/30/2023
13817,56040-94,MemorialCare Innovation Fund,MCIF,None,"MemorialCare Innovation Fund, L.P.","Founded in 1993, MemorialCare Innovation Fund ...",Actively Seeking New Investments,Corporate Venture Capital,Venture Capital,150.000000,...,None,12/01/2022,Completed,MemorialCare Innovation Fund,2013.0,150.0,Venture - General,01/01/2013,11/01/2012,05/18/2023
13864,434783-53,Ballad Ventures,None,None,"Ballad Ventures, LLC","Founded in 2020, Ballad Ventures is a corporat...",Actively Seeking New Investments,Corporate Venture Capital,Venture Capital,25.000000,...,None,03/06/2023,Completed,None,NaN,NaN,None,None,None,05/14/2023
18662,482380-93,Edward-Elmhurst Health Venture Capital,EEH VC,None,None,"Founded in 2019, Edward-Elmhurst Health Ventur...",Actively Seeking New Investments,Corporate Venture Capital,None,NaN,...,"Other - $20,00M",08/23/2022,Completed,None,NaN,NaN,None,None,None,05/06/2023
25811,433710-46,Mass General Brigham Ventures,None,"PIF, Partners Innovation Fund","Mass General Brigham Ventures, LLC","Founded in 2008, Mass General Brigham Ventures...",Actively Seeking New Investments,Venture Capital,None,450.000000,...,None,03/15/2023,Completed,Mass General Brigham Fund III,2021.0,NaN,Venture - General,12/31/2021,02/01/2021,05/12/2023
26771,433943-74,University Hospitals Ventures,UH Ventures,None,None,University Hospitals Ventures is a venture cap...,Actively Seeking New Investments,Corporate Venture Capital,"Growth/Expansion, Not-For-Profit Venture Capit...",NaN,...,None,01/06/2023,Completed,Healthcare Collaboration Fund,2021.0,8.0,Venture Capital - Early Stage,12/31/2021,07/01/2021,05/11/2023
40338,51450-31,CHV Capital,CHV,None,"CHV Capital, Inc.",CHV Capital was a venture capital arm of India...,Out of Business,Venture Capital,None,NaN,...,None,02/18/2016,Completed,None,NaN,NaN,None,None,None,01/30/2023
49637,290328-13,LifeSolutions,None,None,None,None,None,Corporation,None,NaN,...,None,02/19/2013,Completed,None,NaN,NaN,None,None,None,05/06/2023
55421,97167-61,Alexian Brothers Health System,"ABHS, Alexian",None,None,Provider of healthcare services. The company p...,Acquired/Merged,Corporation,None,NaN,...,None,04/13/2015,Completed,None,NaN,NaN,None,None,None,05/06/2023
64837,51292-81,Institute for Systems Biology,ISB,None,"Institute for Systems Biology, Inc.",Provider of biomedical research. The company i...,None,Corporation,None,NaN,...,None,04/30/2015,Completed,None,NaN,NaN,None,None,None,05/12/2023
66105,521701-84,Providence Health Care Ventures,None,None,None,Providence Health Care Ventures is a corporate...,Actively Seeking New Investments,Corporate Venture Capital,Venture Capital,NaN,...,None,05/03/2022,Completed,None,NaN,NaN,None,None,None,05/06/2023
73979,188063-65,UPMC WorkPartners,WorkPartners,None,None,UPMC WorkPartners is a provider of health and ...,Actively Seeking New Investments,Corporation,None,NaN,...,None,10/12/2017,Completed,None,NaN,NaN,None,None,None,05/06/2023
185704,221543-56,NewYork-Presbyterian Ventures,NYP Ventures,None,None,"Founded in 2015, NewYork-Presbyterian Ventures...",Actively Seeking New Investments,Corporate Venture Capital,Venture Capital,NaN,...,None,07/15/2020,Completed,None,NaN,NaN,None,None,None,05/02/2023
189642,268046-92,UnityPoint Health Ventures,None,None,None,"Founded in 2019, UnityPoint Health Ventures is...",Actively Seeking New Investments,Corporate Venture Capital,None,NaN,...,None,05/17/2023,Completed,None,NaN,NaN,None,None,None,05/18/2023
200159,266690-26,Intermountain Ventures,None,"Intermountain Insights, LLC","Intermountain Ventures, LLC","Founded in 2012, Intermountain Ventures is a c...",Actively Seeking New Investments,Corporate Venture Capital,None,NaN,...,None,11/14/2022,Completed,Intermountain Ventures Fund,NaN,NaN,Venture - General,None,None,05/17/2023
204280,123731-65,Swedish Health Services,Swedish,Swedish Medical Center,None,Swedish Medical Center is a provider of health...,Acquired/Merged (Operating Subsidiary),Corporation,None,NaN,...,None,02/21/2020,Completed,None,NaN,NaN,None,None,None,05/06/2023
207312,123725-62,Providence Tarzana Medical Center,None,Tarzana Regional Medical Center,None,"Operator of hospitals in Tarzana, California i...",None,Corporation,None,NaN,...,None,01/07/2016,Completed,None,NaN,NaN,None,None,None,01/30/2023
222672,120829-78,St. Joseph Health,SJH,None,None,Provider of healthcare services. The company p...,Acquired/Merged,Corporation,None,NaN,...,None,08/01/2016,Completed,None,NaN,NaN,None,None,None,03/20/2023
241572,118715-50,Mass General Brigham Innovation,"Partners Innovation, Mass General Brigham",Partners HealthCare Innovation,None,Partners HealthCare Innovation is a corporate ...,Actively Seeking New Investments,Corporate Venture Capital,Venture Capital,251.000000,...,None,01/14/2021,Completed,Translational Innovation Fund,2019.0,50.0,Venture - General,10/21/2019,10/21/2019,05/17/2023
242244,118843-03,Health Alliance Plan,None,None,None,None,None,Corporation,None,NaN,...,None,09/19/2019,Completed,None,NaN,NaN,None,None,None,05/06/2023
259377,399434-32,Healthcare Innovation Fund,HIF,None,None,Healthcare Innovation Fund is a corporate vent...,Actively Seeking New Investments,Corporate Venture Capital,"Corporation, Venture Capital",10.000000,...,"Bridge - $0,18M (Convertible); Loan - $0,75M (...",12/17/2018,Completed,None,NaN,NaN,None,None,None,05/06/2023
279549,160671-43,Northwell Holdings,"Northwell Ventures, Northwell Holdings & Ventures",None,None,"Founded in 2013, Northwell Holdings & Ventures...",Actively Seeking New Investments,Corporate Venture Capital,Venture Capital,NaN,...,None,04/18/2023,Completed,None,NaN,NaN,None,None,None,05/17/2023
280027,160890-22,UPMC Enterprises,None,None,None,"Founded in 2014, UPMC Enterprises is a venture...",Actively Seeking New Investments,Corporate Venture Capital,"University, Venture Capital",NaN,...,None,02/11/2023,Completed,None,NaN,NaN,None,None,None,05/17/2023
288076,160041-88,OSF Ventures,None,None,None,"Founded in 2015, OSF Ventures is a corporate v...",Actively Seeking New Investments,Corporate Venture Capital,Venture Capital,250.000000,...,"Bridge - $5,40M (Convertible); Bridge - $3,50M...",12/21/2022,Completed,OSF Ventures II,2019.0,75.0,Venture - General,07/25/2019,None,05/17/2023
290012,160035-76,UPMC Susquehanna,Susquehanna Health,Susquehanna Health System,None,Operator of a hospital-based health network in...,None,Corporation,None,NaN,...,None,10/02/2017,Completed,None,NaN,NaN,None,None,None,05/06/2023
300915,158836-15,Mayo Clinic Business Accelerator,MC Business Accelerator,None,None,Mayo Clinic Business Accelerator provides infr...,Actively Seeking New Investments,Accelerator/Incubator,None,NaN,...,None,01/01/2020,Completed,None,NaN,NaN,None,None,None,05/06/2023
315031,62952-67,Summation Health Ventures,None,None,None,"Founded in 2014, Summation Health Ventures is ...",Actively Seeking New Investments,Corporate Venture Capital,None,100.000000,...,None,11/24/2020,Completed,Summation Health Ventures Fund,2014.0,80.0,Venture - General,07/28/2014,07/15/2014,05/09/2023
328002,108883-18,Methodist Le Bonheur Healthcare,MLH,None,"Methodist Le Bonheur Healthcare, Inc.",Methodist Le Bonheur Healthcare is a provider ...,Acquired/Merged (Operating Subsidiary),Corporation,None,NaN,...,None,09/05/2012,Completed,None,NaN,NaN,None,None,None,05/06/2023
328782,61712-74,OSF Healthcare Foundation,None,None,None,OSF Healthcare System is a foundation based in...,None,Limited Partner,None,170.916253,...,None,05/30/2018,Completed,None,NaN,NaN,None,None,None,01/30/2023
364842,58865-23,Sisters of Charity of Leavenworth Health System,"SCL Health, SCL",None,Sisters of Charity of Leavenworth Health Syste...,Sisters of Charity of Leavenworth Health Syste...,None,Limited Partner,None,3006.800000,...,None,12/13/2021,Completed,None,NaN,NaN,None,None,None,03/02/2023
368450,58606-12,Foundation of the Massachusetts Eye & Ear Infi...,None,None,Foundation of the Massachusetts Eye and Ear In...,Foundation of the Massachusetts Eye & Ear Infi...,None,Limited Partner,None,266.433952,...,None,11/13/2017,Completed,None,NaN,NaN,None,None,None,03/14/2023
372117,10937-35,Compassus,None,CLP Healthcare Services Inc.,"Hospice Compassus, Inc.",Hospice Compassus is a provider of hospice and...,Actively Seeking New Investments,PE-Backed Company,Corporation,NaN,...,None,12/02/2016,Completed,None,NaN,NaN,None,None,None,01/30/2023
372891,11114-65,Ascension Ventures,AV,Ascension Health Ventures,"AVH Holding Company, LLC","Founded in 2001, Ascension Ventures is a corpo...",Actively Seeking New Investments,Corporate Venture Capital,Growth/Expansion,1000.000000,...,None,01/17/2023,Completed,Collaborative Health Ventures V,2021.0,285.0,Venture - General,02/19/2021,05/01/2020,05/12/2023
375075,11246-23,Kaiser Permanente Ventures,"KPV, Kaiser Permanente",None,"Kaiser Permanente Ventures, LLC","Established in 1997, Kaiser Permanente Venture...",Actively Seeking New Investments,Corporate Venture Capital,None,500.000000,...,"Other - $3,55M",01/18/2023,Completed,KPV Fund V,2019.0,141.0,Venture - General,12/05/2019,None,05/17/2023

In [96]:
df_inv_1.shape

(35, 114)

In [97]:
# Are all the found items included in the df_e1
df_inv_1[var.parent_com_id].isin(df_e1[var.entity_id]).all()

# so we don't need to find them from the investor data

np.True_

In [98]:
wanted_ind_types = ['Corporate Venture Capital', 'Venture Capital']
df_e3 = df_e1[df_e1[var.industry].isin(wanted_ind_types)]
df_e3

,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated
9233,151167-52,399434-32,Healthcare Innovation Fund,Corporate Venture Capital,"Lafayette, LA",NaN,Subsidiary,Lafayette,Louisiana,United States,05/06/2023
42882,56084-95,56040-94,MemorialCare Innovation Fund,Corporate Venture Capital,"Long Beach, CA",1993.0,Subsidiary,Long Beach,California,United States,01/30/2023
42886,56084-95,62952-67,Summation Health Ventures,Corporate Venture Capital,"Long Beach, CA",2014.0,Subsidiary,Long Beach,California,United States,01/30/2023
45098,150350-41,51450-31,CHV Capital,Venture Capital,"Indianapolis, IN",2007.0,Subsidiary,Indianapolis,Indiana,United States,01/30/2023
83834,55165-33,433943-74,University Hospitals Ventures,Corporate Venture Capital,"Cleveland, OH",2018.0,Subsidiary,Cleveland,Ohio,United States,03/03/2023
183848,51614-92,11114-65,Ascension Ventures,Corporate Venture Capital,"Saint Louis, MO",2001.0,Subsidiary,Saint Louis,Missouri,United States,01/30/2023
185492,51726-52,55757-98,Mayo Clinic Ventures,Venture Capital,"Rochester, MN",1986.0,Subsidiary,Rochester,Minnesota,United States,01/30/2023
209023,50987-17,118715-50,Mass General Brigham Innovation,Corporate Venture Capital,"Cambridge, MA",NaN,Subsidiary,Cambridge,Massachusetts,United States,01/30/2023
209033,50987-17,433710-46,Mass General Brigham Ventures,Venture Capital,"Cambridge, MA",2008.0,Subsidiary,Cambridge,Massachusetts,United States,04/24/2023
405509,185503-60,266690-26,Intermountain Ventures,Corporate Venture Capital,"Salt Lake City, UT",2012.0,Subsidiary,Salt Lake City,Utah,United States,01/30/2023
568341,229125-07,11246-23,Kaiser Permanente Ventures,Corporate Venture Capital,"Oakland, CA",1997.0,Subsidiary,Oakland,California,United States,05/06/2023
785095,127260-28,340845-76,Cleveland Clinic Ventures,Corporate Venture Capital,"Cleveland, OH",2016.0,Subsidiary,Cleveland,Ohio,United States,01/30/2023
902000,265269-88,160041-88,OSF Ventures,Corporate Venture Capital,"Peoria, IL",2015.0,Subsidiary,Peoria,Illinois,United States,01/30/2023
963766,169562-80,160671-43,Northwell Holdings,Corporate Venture Capital,"New York, NY",2013.0,Subsidiary,New York,New York,United States,01/30/2023
1042762,166514-86,434783-53,Ballad Ventures,Corporate Venture Capital,"Johnson City, TN",2020.0,Subsidiary,Johnson City,Tennessee,United States,01/30/2023
1264082,159211-27,482380-93,Edward-Elmhurst Health Venture Capital,Corporate Venture Capital,"Naperville, IL",NaN,Subsidiary,Naperville,Illinois,United States,01/30/2023
1269789,64677-79,521701-84,Providence Health Care Ventures,Corporate Venture Capital,"Vancouver, Canada",NaN,Subsidiary,Vancouver,British Columbia,Canada,03/17/2023
1290557,64197-64,221543-56,NewYork-Presbyterian Ventures,Corporate Venture Capital,"New York, NY",2015.0,Subsidiary,New York,New York,United States,01/30/2023
1388227,61215-67,268046-92,UnityPoint Health Ventures,Corporate Venture Capital,"West Des Moines, IA",2019.0,Subsidiary,West Des Moines,Iowa,United States,01/30/2023
1530118,58870-45,160890-22,UPMC Enterprises,Corporate Venture Capital,"Pittsburgh, PA",2014.0,Subsidiary,Pittsburgh,Pennsylvania,United States,01/30/2023

In [99]:
df_e3.shape

(20, 11)

In [101]:
df_e3.to_excel(file.dm_sp040_10__affiliated_entities_manual_list__xl, index = False)

In [103]:
df_3.to_excel(file.dm_sp040_15__manual_hospitals_list__xl, index = False)

In [104]:
df_e3[var.aff_type].value_counts()

AffiliateType
Subsidiary    20
Name: count, dtype: int64