# GOAL
- Create a data set that is like entity affiliation dataset in the PitchBook data for hospitals and VCs only
- That has all the hospital and vc firms in one data set.
    - Some affiliation is missing in the PitchBook data so we will need to do some manual work to fill in the gaps.
- I want both pair in the same dataset
- I want to enumerate all the unique pairs
- I want to sort the dataset by pair number or ID so every pair is next to each other
- I want to mark those that added to the dataset manually and those that were in the PitchBook data
- I want to fill in the missing affiliation information from PitchBook data
- At the end check exatcly two rows have the same pair ID, one for each direction of the affiliation
- I want to specify which one is hospital and which one is VC for each row

# CONFIG

In [13]:
import sys
import pandas as pd
from pathlib import Path

sys.modules.pop('a20_config.a10_config', None)  # force reload
from a20_config.a10_config import dyr, file, const, var

Path.cwd()

PosixPath('/sharedata/camm/c_projects/i100_g7__VC_arms')

# Create initial combined dataset from two datasets, one is hospital with affiliated VCs, the other is VCs with affiliated hospitals.
- Also checking for duplicates after combining

In [3]:
df_00 = pd.read_excel(file.di_sp050_15__hospitals_with_affiliated_vc__manual_list_added_to_by_data_property__xl)

df_00[var.affiliate_type] = const.hospital
df_00[var.entity_type] = const.vc

df_00

,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type
0,434783-53,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc
1,57221-29,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc
2,433943-74,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc
3,56040-94,56084-95,MemorialCare Health System,Clinics/Outpatient Services,"Long Beach, CA",1907.0,Parent,Long Beach,California,United States,01/30/2023,hospital,vc
4,433943-74,185286-07,St. John Medical Center (Sisters of Charity He...,Hospitals/Inpatient Services,"Cleveland, OH",NaN,Sister,Cleveland,Ohio,United States,05/06/2023,hospital,vc
...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,435625-48,99685-00,Renal Services,Clinics/Outpatient Services,"London, United Kingdom",2007.0,Sister,London,England,United Kingdom,05/06/2023,hospital,vc
244,340845-76,127260-28,Cleveland Clinic,Acquirer,"Cleveland, OH",1921.0,Parent,Cleveland,Ohio,United States,01/30/2023,hospital,vc
245,482380-93,159211-27,Edward-Elmhurst Health,Hospitals/Inpatient Services,"Naperville, IL",2013.0,Parent,Naperville,Illinois,United States,05/06/2023,hospital,vc
246,435253-51,484448-50,Foundations for Change,Clinics/Outpatient Services,"Peoria, AZ",2017.0,Subsidiary,Peoria,Arizona,United States,01/30/2023,hospital,vc
247,435253-51,435249-19,Cedar Psychiatry,Clinics/Outpatient Services,"Springville, UT",NaN,Subsidiary,Springville,Utah,United States,01/30/2023,hospital,vc

In [4]:
df_05 = pd.read_excel(file.di_sp050_20__VCs_with_affiliated_hospitals_manual_list_added_to_by_data_property__xl)

df_05[var.affiliate_type] = const.vc
df_05[var.entity_type] = const.hospital

df_05

,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type
0,151167-52,399434-32,Healthcare Innovation Fund,Corporate Venture Capital,"Lafayette, LA",NaN,Subsidiary,Lafayette,Louisiana,United States,05/06/2023,vc,hospital
1,433878-04,42282-37,PureTech Health,Venture Capital,"Boston, MA",2001.0,Parent,Boston,Massachusetts,United States,01/30/2023,vc,hospital
2,151100-02,55472-23,Health Insight Capital,Corporate Venture Capital,"Nashville, TN",NaN,Sister,Nashville,Tennessee,United States,01/30/2023,vc,hospital
3,433997-20,168311-71,Sodexo Ventures,Corporate Venture Capital,"Issy les Moulineaux, France",2016.0,Sister,Issy les Moulineaux,NaN,France,01/30/2023,vc,hospital
4,56084-95,56040-94,MemorialCare Innovation Fund,Corporate Venture Capital,"Long Beach, CA",1993.0,Subsidiary,Long Beach,California,United States,01/30/2023,vc,hospital
...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,10466-20,168311-71,Sodexo Ventures,Corporate Venture Capital,"Issy les Moulineaux, France",2016.0,Sister,Issy les Moulineaux,NaN,France,01/30/2023,vc,hospital
247,10326-34,167357-98,Well Ventures,Corporate Venture Capital,"Deerfield, IL",2009.0,Subsidiary,Deerfield,Illinois,United States,01/30/2023,vc,hospital
248,10308-70,120443-77,McKesson Ventures,Corporate Venture Capital,"San Francisco, CA",2014.0,Sister,San Francisco,California,United States,01/30/2023,vc,hospital
249,152034-13,166204-27,Fresenius Medical Care Ventures,Corporate Venture Capital,"Bad Homburg, Germany",2016.0,Sister,Bad Homburg,NaN,Germany,01/30/2023,vc,hospital
250,482193-37,81906-40,Air Liquide Venture Capital,Corporate Venture Capital,"Paris, France",2013.0,Sister,Paris,NaN,France,01/30/2023,vc,hospital

In [5]:
df_all_pb = pd.concat([df_00, df_05], ignore_index = True)
print(df_all_pb.shape)
df_all_pb

(499, 13)

,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type
0,434783-53,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc
1,57221-29,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc
2,433943-74,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc
3,56040-94,56084-95,MemorialCare Health System,Clinics/Outpatient Services,"Long Beach, CA",1907.0,Parent,Long Beach,California,United States,01/30/2023,hospital,vc
4,433943-74,185286-07,St. John Medical Center (Sisters of Charity He...,Hospitals/Inpatient Services,"Cleveland, OH",NaN,Sister,Cleveland,Ohio,United States,05/06/2023,hospital,vc
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,10466-20,168311-71,Sodexo Ventures,Corporate Venture Capital,"Issy les Moulineaux, France",2016.0,Sister,Issy les Moulineaux,NaN,France,01/30/2023,vc,hospital
495,10326-34,167357-98,Well Ventures,Corporate Venture Capital,"Deerfield, IL",2009.0,Subsidiary,Deerfield,Illinois,United States,01/30/2023,vc,hospital
496,10308-70,120443-77,McKesson Ventures,Corporate Venture Capital,"San Francisco, CA",2014.0,Sister,San Francisco,California,United States,01/30/2023,vc,hospital
497,152034-13,166204-27,Fresenius Medical Care Ventures,Corporate Venture Capital,"Bad Homburg, Germany",2016.0,Sister,Bad Homburg,NaN,Germany,01/30/2023,vc,hospital
498,482193-37,81906-40,Air Liquide Venture Capital,Corporate Venture Capital,"Paris, France",2013.0,Sister,Paris,NaN,France,01/30/2023,vc,hospital

In [6]:
df_all_pb = df_all_pb.drop_duplicates()
print(df_all_pb.shape)
df_all_pb

(499, 13)

,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type
0,434783-53,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc
1,57221-29,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc
2,433943-74,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc
3,56040-94,56084-95,MemorialCare Health System,Clinics/Outpatient Services,"Long Beach, CA",1907.0,Parent,Long Beach,California,United States,01/30/2023,hospital,vc
4,433943-74,185286-07,St. John Medical Center (Sisters of Charity He...,Hospitals/Inpatient Services,"Cleveland, OH",NaN,Sister,Cleveland,Ohio,United States,05/06/2023,hospital,vc
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,10466-20,168311-71,Sodexo Ventures,Corporate Venture Capital,"Issy les Moulineaux, France",2016.0,Sister,Issy les Moulineaux,NaN,France,01/30/2023,vc,hospital
495,10326-34,167357-98,Well Ventures,Corporate Venture Capital,"Deerfield, IL",2009.0,Subsidiary,Deerfield,Illinois,United States,01/30/2023,vc,hospital
496,10308-70,120443-77,McKesson Ventures,Corporate Venture Capital,"San Francisco, CA",2014.0,Sister,San Francisco,California,United States,01/30/2023,vc,hospital
497,152034-13,166204-27,Fresenius Medical Care Ventures,Corporate Venture Capital,"Bad Homburg, Germany",2016.0,Sister,Bad Homburg,NaN,Germany,01/30/2023,vc,hospital
498,482193-37,81906-40,Air Liquide Venture Capital,Corporate Venture Capital,"Paris, France",2013.0,Sister,Paris,NaN,France,01/30/2023,vc,hospital

-> result: there is no duplicates because number of rows remained the same

# Mark all the items coming from the original PitchBook data, later we will mark the manually added ones as False in this column.
- Because there are some missing items from a pair, we will need to add them manually later.

In [7]:
# mark all rows as from PitchBook data, later we will mark the manually added ones af False in this column
df_10 = df_all_pb.copy()
df_10[var.from_pitchbook] = True
df_10

,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type,FromPitchBook
0,434783-53,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc,True
1,57221-29,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc,True
2,433943-74,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc,True
3,56040-94,56084-95,MemorialCare Health System,Clinics/Outpatient Services,"Long Beach, CA",1907.0,Parent,Long Beach,California,United States,01/30/2023,hospital,vc,True
4,433943-74,185286-07,St. John Medical Center (Sisters of Charity He...,Hospitals/Inpatient Services,"Cleveland, OH",NaN,Sister,Cleveland,Ohio,United States,05/06/2023,hospital,vc,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,10466-20,168311-71,Sodexo Ventures,Corporate Venture Capital,"Issy les Moulineaux, France",2016.0,Sister,Issy les Moulineaux,NaN,France,01/30/2023,vc,hospital,True
495,10326-34,167357-98,Well Ventures,Corporate Venture Capital,"Deerfield, IL",2009.0,Subsidiary,Deerfield,Illinois,United States,01/30/2023,vc,hospital,True
496,10308-70,120443-77,McKesson Ventures,Corporate Venture Capital,"San Francisco, CA",2014.0,Sister,San Francisco,California,United States,01/30/2023,vc,hospital,True
497,152034-13,166204-27,Fresenius Medical Care Ventures,Corporate Venture Capital,"Bad Homburg, Germany",2016.0,Sister,Bad Homburg,NaN,Germany,01/30/2023,vc,hospital,True
498,482193-37,81906-40,Air Liquide Venture Capital,Corporate Venture Capital,"Paris, France",2013.0,Sister,Paris,NaN,France,01/30/2023,vc,hospital,True

# Generate pair IDs for each unique pair (regardless of order), and ensure both directions of the pair are present in the dataset.

In [8]:
df_15 = df_10.copy()

# Create a set of existing pairs with normalized order (smaller, larger)
pair_to_id = {}
pair_id_counter = 0

# First pass: assign IDs to existing pairs
for idx, row in df_15.iterrows():
    val1, val2 = row[var.entity_id], row[var.affiliate_id]
    # Normalize pair to always have consistent ordering for ID assignment
    normalized_pair = tuple(sorted([val1, val2]))

    if normalized_pair not in pair_to_id:
        pair_to_id[normalized_pair] = pair_id_counter
        pair_id_counter += 1

# Add pair_id column to original DataFrame
df_15[var.pair_id] = df_15.apply(lambda row: pair_to_id[tuple(sorted([row[var.entity_id], row[var.affiliate_id]]))],
                                 axis = 1)

# Move pair_id to first position, keep all other columns
cols = [var.pair_id] + [col for col in df_15.columns if col != var.pair_id]
df_15 = df_15[cols]

df_15 = df_15.sort_values(by = var.pair_id).reset_index(drop = True)

df_15

,pair_id,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type,FromPitchBook
0,0,434783-53,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc,True
1,0,166514-86,434783-53,Ballad Ventures,Corporate Venture Capital,"Johnson City, TN",2020.0,Subsidiary,Johnson City,Tennessee,United States,01/30/2023,vc,hospital,True
2,1,62802-10,57221-29,Bank Austria TFV,Venture Capital,"Vienna, Austria",1996.0,Sister,Vienna,NaN,Austria,01/30/2023,vc,hospital,True
3,1,57221-29,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc,True
4,2,433943-74,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,249,164588-68,507452-14,Wanyuandia Investment,Corporate Venture Capital,"Hangzhou, China",2021.0,Subsidiary,Hangzhou,Zhejiang,China,01/30/2023,vc,hospital,True
495,250,114336-37,527371-30,Catalyst by Wellstar,Corporate Venture Capital,"Marietta, GA",2021.0,Sister,Marietta,Georgia,United States,05/12/2023,vc,hospital,True
496,251,64863-82,527371-30,Catalyst by Wellstar,Corporate Venture Capital,"Marietta, GA",2021.0,Subsidiary,Marietta,Georgia,United States,05/12/2023,vc,hospital,True
497,252,111991-60,62848-00,DLD Ventures,Corporate Venture Capital,"Munich, Germany",2007.0,Sister,Munich,NaN,Germany,01/30/2023,vc,hospital,True
498,253,157276-27,166341-79,Oravision Ventures,Corporate Venture Capital,"Andover, MA",NaN,Subsidiary,Andover,Massachusetts,United States,01/30/2023,vc,hospital,True

# Find missing pairs and add them to the dataset

In [9]:
# Find missing reversed pairs
existing_pairs = set(zip(df_15[var.entity_id], df_15[var.affiliate_id]))
missing_pairs = []

for val1, val2 in existing_pairs:
    if (val2, val1) not in existing_pairs:
        normalized_pair = tuple(sorted([val1, val2]))
        missing_pairs.append({
                var.entity_id   : val2,
                var.affiliate_id: val1,
                var.pair_id     : pair_to_id[normalized_pair]
        })

# Combine original and missing pairs
if missing_pairs:
    missing_df = pd.DataFrame(missing_pairs)
    df_20_complete = pd.concat([df_15, missing_df], ignore_index = True)
else:
    df_20_complete = df_15.copy()

# Sort by pair_id for better visualization
df_20_complete = df_20_complete.sort_values('pair_id').reset_index(drop = True)

# number of missing pairs added
len(missing_pairs)

9

In [10]:
df_20_complete

,pair_id,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type,FromPitchBook
0,0,434783-53,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc,True
1,0,166514-86,434783-53,Ballad Ventures,Corporate Venture Capital,"Johnson City, TN",2020.0,Subsidiary,Johnson City,Tennessee,United States,01/30/2023,vc,hospital,True
2,1,62802-10,57221-29,Bank Austria TFV,Venture Capital,"Vienna, Austria",1996.0,Sister,Vienna,NaN,Austria,01/30/2023,vc,hospital,True
3,1,57221-29,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc,True
4,2,433943-74,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,251,527371-30,64863-82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,252,62848-00,111991-60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
505,252,111991-60,62848-00,DLD Ventures,Corporate Venture Capital,"Munich, Germany",2007.0,Sister,Munich,NaN,Germany,01/30/2023,vc,hospital,True
506,253,157276-27,166341-79,Oravision Ventures,Corporate Venture Capital,"Andover, MA",NaN,Subsidiary,Andover,Massachusetts,United States,01/30/2023,vc,hospital,True
507,253,166341-79,157276-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Are all pair IDs appearing exactly twice?

# Check the count of each pair_id
pair_counts = df_20_complete[var.pair_id].value_counts().sort_index()

print("Count of each pair_id:", pair_counts)

# Check if all pair_ids appear exactly twice
all_twice = (pair_counts == 2).all()

if all_twice:
    print("\n✓ All pair_ids appear exactly twice!")
else:
    print("\n✗ Some pair_ids do NOT appear exactly twice:")
    print(pair_counts[pair_counts != 2])

Count of each pair_id: pair_id
0      2
1      2
2      2
3      2
4      2
      ..
249    2
250    2
251    2
252    2
253    2
Name: count, Length: 254, dtype: int64

✓ All pair_ids appear exactly twice!

In [14]:
# save intermediate result
df_20_complete.to_excel(file.di_sp060_01__all_hospitals_and_VC_affiliations__preliminary__xl,
                        index = False)

In [15]:
# Fill in missing affiliation information from PitchBook data
df_30_complete = pd.read_excel(file.di_sp060_01__all_hospitals_and_VC_affiliations__preliminary__xl)

# Solution 1: Convert to boolean explicitly (RECOMMENDED)
df_30_complete[var.from_pitchbook] = df_30_complete[var.from_pitchbook].fillna(False).astype(bool)
df_30_complete

,pair_id,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type,FromPitchBook
0,0,434783-53,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc,True
1,0,166514-86,434783-53,Ballad Ventures,Corporate Venture Capital,"Johnson City, TN",2020.0,Subsidiary,Johnson City,Tennessee,United States,01/30/2023,vc,hospital,True
2,1,62802-10,57221-29,Bank Austria TFV,Venture Capital,"Vienna, Austria",1996.0,Sister,Vienna,NaN,Austria,01/30/2023,vc,hospital,True
3,1,57221-29,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc,True
4,2,433943-74,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,251,527371-30,64863-82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
504,252,62848-00,111991-60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
505,252,111991-60,62848-00,DLD Ventures,Corporate Venture Capital,"Munich, Germany",2007.0,Sister,Munich,NaN,Germany,01/30/2023,vc,hospital,True
506,253,157276-27,166341-79,Oravision Ventures,Corporate Venture Capital,"Andover, MA",NaN,Subsidiary,Andover,Massachusetts,United States,01/30/2023,vc,hospital,True
507,253,166341-79,157276-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [17]:
msk = df_30_complete[var.from_pitchbook].eq(False)
df_manual = df_30_complete[msk]
df_manual

,pair_id,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type,FromPitchBook
21,10,266429-44,55440-55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
343,171,361472-59,399434-32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
455,227,513338-32,11259-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
497,248,158931-46,125942-95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
498,249,507452-14,164588-68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
500,250,527371-30,114336-37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
503,251,527371-30,64863-82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
504,252,62848-00,111991-60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
507,253,166341-79,157276-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [18]:
df_40_ref = df_all_pb.copy()
df_40_ref

,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type
0,434783-53,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc
1,57221-29,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc
2,433943-74,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc
3,56040-94,56084-95,MemorialCare Health System,Clinics/Outpatient Services,"Long Beach, CA",1907.0,Parent,Long Beach,California,United States,01/30/2023,hospital,vc
4,433943-74,185286-07,St. John Medical Center (Sisters of Charity He...,Hospitals/Inpatient Services,"Cleveland, OH",NaN,Sister,Cleveland,Ohio,United States,05/06/2023,hospital,vc
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,10466-20,168311-71,Sodexo Ventures,Corporate Venture Capital,"Issy les Moulineaux, France",2016.0,Sister,Issy les Moulineaux,NaN,France,01/30/2023,vc,hospital
495,10326-34,167357-98,Well Ventures,Corporate Venture Capital,"Deerfield, IL",2009.0,Subsidiary,Deerfield,Illinois,United States,01/30/2023,vc,hospital
496,10308-70,120443-77,McKesson Ventures,Corporate Venture Capital,"San Francisco, CA",2014.0,Sister,San Francisco,California,United States,01/30/2023,vc,hospital
497,152034-13,166204-27,Fresenius Medical Care Ventures,Corporate Venture Capital,"Bad Homburg, Germany",2016.0,Sister,Bad Homburg,NaN,Germany,01/30/2023,vc,hospital
498,482193-37,81906-40,Air Liquide Venture Capital,Corporate Venture Capital,"Paris, France",2013.0,Sister,Paris,NaN,France,01/30/2023,vc,hospital

In [19]:
df_40_ref = df_40_ref.drop(columns = [var.entity_id])
df_40_ref

,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type
0,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc
1,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc
2,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc
3,56084-95,MemorialCare Health System,Clinics/Outpatient Services,"Long Beach, CA",1907.0,Parent,Long Beach,California,United States,01/30/2023,hospital,vc
4,185286-07,St. John Medical Center (Sisters of Charity He...,Hospitals/Inpatient Services,"Cleveland, OH",NaN,Sister,Cleveland,Ohio,United States,05/06/2023,hospital,vc
...,...,...,...,...,...,...,...,...,...,...,...,...
494,168311-71,Sodexo Ventures,Corporate Venture Capital,"Issy les Moulineaux, France",2016.0,Sister,Issy les Moulineaux,NaN,France,01/30/2023,vc,hospital
495,167357-98,Well Ventures,Corporate Venture Capital,"Deerfield, IL",2009.0,Subsidiary,Deerfield,Illinois,United States,01/30/2023,vc,hospital
496,120443-77,McKesson Ventures,Corporate Venture Capital,"San Francisco, CA",2014.0,Sister,San Francisco,California,United States,01/30/2023,vc,hospital
497,166204-27,Fresenius Medical Care Ventures,Corporate Venture Capital,"Bad Homburg, Germany",2016.0,Sister,Bad Homburg,NaN,Germany,01/30/2023,vc,hospital
498,81906-40,Air Liquide Venture Capital,Corporate Venture Capital,"Paris, France",2013.0,Sister,Paris,NaN,France,01/30/2023,vc,hospital

In [20]:
df_40_ref = df_40_ref.drop_duplicates(subset = [var.affiliate_id])
print(df_40_ref.shape)
df_40_ref

(335, 12)

,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type
0,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc
1,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc
2,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc
3,56084-95,MemorialCare Health System,Clinics/Outpatient Services,"Long Beach, CA",1907.0,Parent,Long Beach,California,United States,01/30/2023,hospital,vc
4,185286-07,St. John Medical Center (Sisters of Charity He...,Hospitals/Inpatient Services,"Cleveland, OH",NaN,Sister,Cleveland,Ohio,United States,05/06/2023,hospital,vc
...,...,...,...,...,...,...,...,...,...,...,...,...
468,268046-92,UnityPoint Health Ventures,Corporate Venture Capital,"West Des Moines, IA",2019.0,Subsidiary,West Des Moines,Iowa,United States,01/30/2023,vc,hospital
470,322655-05,Vingroup Ventures,Venture Capital,"Ho Chi Minh City, Vietnam",2018.0,Sister,Ho Chi Minh City,NaN,Vietnam,05/06/2023,vc,hospital
478,435253-51,Novamind,Venture Capital,"Toronto, Canada",2019.0,Parent,Toronto,Ontario,Canada,01/30/2023,vc,hospital
479,498163-60,Halma Ventures,Venture Capital,"Amersham, United Kingdom",2019.0,Sister,Amersham,England,United Kingdom,03/27/2023,vc,hospital
492,228475-27,CureDuchenne Ventures,Corporate Venture Capital,"Newport Beach, CA",2014.0,Subsidiary,Newport Beach,California,United States,01/30/2023,vc,hospital

In [21]:
df_40_ref = df_40_ref.drop_duplicates()
print(df_40_ref.shape)
df_40_ref

(335, 12)

,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type
0,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc
1,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc
2,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc
3,56084-95,MemorialCare Health System,Clinics/Outpatient Services,"Long Beach, CA",1907.0,Parent,Long Beach,California,United States,01/30/2023,hospital,vc
4,185286-07,St. John Medical Center (Sisters of Charity He...,Hospitals/Inpatient Services,"Cleveland, OH",NaN,Sister,Cleveland,Ohio,United States,05/06/2023,hospital,vc
...,...,...,...,...,...,...,...,...,...,...,...,...
468,268046-92,UnityPoint Health Ventures,Corporate Venture Capital,"West Des Moines, IA",2019.0,Subsidiary,West Des Moines,Iowa,United States,01/30/2023,vc,hospital
470,322655-05,Vingroup Ventures,Venture Capital,"Ho Chi Minh City, Vietnam",2018.0,Sister,Ho Chi Minh City,NaN,Vietnam,05/06/2023,vc,hospital
478,435253-51,Novamind,Venture Capital,"Toronto, Canada",2019.0,Parent,Toronto,Ontario,Canada,01/30/2023,vc,hospital
479,498163-60,Halma Ventures,Venture Capital,"Amersham, United Kingdom",2019.0,Sister,Amersham,England,United Kingdom,03/27/2023,vc,hospital
492,228475-27,CureDuchenne Ventures,Corporate Venture Capital,"Newport Beach, CA",2014.0,Subsidiary,Newport Beach,California,United States,01/30/2023,vc,hospital

In [22]:
key_counts = df_40_ref[var.affiliate_id].value_counts()
duplicates = key_counts[key_counts > 1]
duplicates

Series([], Name: count, dtype: int64)

In [23]:
# so no duplicates, I can be sure there is one and only one row per affiliate_id
assert duplicates.empty, f"Reference DataFrame has duplicate keys: {duplicates.index.tolist()}"

In [24]:
# Assert all keys in df exist in ref_df
missing_keys = set(df_30_complete[var.affiliate_id]) - set(df_40_ref[var.affiliate_id])
if missing_keys: print(f"Keys in df not found in reference: {missing_keys}")
print("number of missing keys:", len(missing_keys))
print("number of nan rows in affiliate_id column:", len(df_manual))

Keys in df not found in reference: {'164588-68', '114336-37', '11259-10', '64863-82'}
number of missing keys: 4
number of nan rows in affiliate_id column: 9

In [25]:
# fill in missing affiliation information from reference DataFrame
df_45_merged = df_30_complete.merge(df_40_ref, on = var.affiliate_id, how = 'left', suffixes = ('', '_ref'),
                                    validate = 'many_to_one')

df_45_merged

,pair_id,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,...,Industry_ref,Location_ref,YearFounded_ref,AffiliateType_ref,HQCity_ref,HQState_Province_ref,HQCountry_ref,LastUpdated_ref,affiliate_type_ref,entity_type_ref
0,0,434783-53,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,...,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc
1,0,166514-86,434783-53,Ballad Ventures,Corporate Venture Capital,"Johnson City, TN",2020.0,Subsidiary,Johnson City,Tennessee,...,Corporate Venture Capital,"Johnson City, TN",2020.0,Subsidiary,Johnson City,Tennessee,United States,01/30/2023,vc,hospital
2,1,62802-10,57221-29,Bank Austria TFV,Venture Capital,"Vienna, Austria",1996.0,Sister,Vienna,NaN,...,Venture Capital,"Vienna, Austria",1996.0,Sister,Vienna,NaN,Austria,01/30/2023,vc,hospital
3,1,57221-29,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,...,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc
4,2,433943-74,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,...,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,251,527371-30,64863-82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
504,252,62848-00,111991-60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Other Healthcare Services,"Vienna, Austria",2001.0,Sister,Vienna,NaN,Austria,01/30/2023,hospital,vc
505,252,111991-60,62848-00,DLD Ventures,Corporate Venture Capital,"Munich, Germany",2007.0,Sister,Munich,NaN,...,Corporate Venture Capital,"Munich, Germany",2007.0,Sister,Munich,NaN,Germany,01/30/2023,vc,hospital
506,253,157276-27,166341-79,Oravision Ventures,Corporate Venture Capital,"Andover, MA",NaN,Subsidiary,Andover,Massachusetts,...,Corporate Venture Capital,"Andover, MA",NaN,Subsidiary,Andover,Massachusetts,United States,01/30/2023,vc,hospital
507,253,166341-79,157276-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Other Healthcare Services,"Andover, MA",1985.0,Parent,Andover,Massachusetts,United States,01/30/2023,hospital,vc

In [26]:
# Step 3: Fill in the columns (update existing or add new)

df_50_complete = df_30_complete.copy()

for col in df_40_ref.columns:
    if col != var.affiliate_id:  # Skip the key column
        if col in df_50_complete.columns:
            # Update existing column
            # we don't lose existing data becasue they are mathced already.
            # If is for the case that we didn't merge on all of the df_ref columns
            df_50_complete[col] = df_45_merged[f'{col}_ref'] if f'{col}_ref' in df_45_merged.columns else \
                df_50_complete[col]

        else:
            # Add new column
            df_50_complete[col] = df_45_merged[col]

print("Filled DataFrame:")
df_50_complete

Filled DataFrame:

,pair_id,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type,FromPitchBook
0,0,434783-53,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc,True
1,0,166514-86,434783-53,Ballad Ventures,Corporate Venture Capital,"Johnson City, TN",2020.0,Subsidiary,Johnson City,Tennessee,United States,01/30/2023,vc,hospital,True
2,1,62802-10,57221-29,Bank Austria TFV,Venture Capital,"Vienna, Austria",1996.0,Sister,Vienna,NaN,Austria,01/30/2023,vc,hospital,True
3,1,57221-29,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc,True
4,2,433943-74,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,251,527371-30,64863-82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
504,252,62848-00,111991-60,Netdoktor.at,Other Healthcare Services,"Vienna, Austria",2001.0,Sister,Vienna,NaN,Austria,01/30/2023,hospital,vc,False
505,252,111991-60,62848-00,DLD Ventures,Corporate Venture Capital,"Munich, Germany",2007.0,Sister,Munich,NaN,Germany,01/30/2023,vc,hospital,True
506,253,157276-27,166341-79,Oravision Ventures,Corporate Venture Capital,"Andover, MA",NaN,Subsidiary,Andover,Massachusetts,United States,01/30/2023,vc,hospital,True
507,253,166341-79,157276-27,Ora Clinical,Other Healthcare Services,"Andover, MA",1985.0,Parent,Andover,Massachusetts,United States,01/30/2023,hospital,vc,False

In [27]:
# There are still 4 rows with NaN in some columns but 5 columns are filled
msk = df_50_complete[var.from_pitchbook].eq(False)
df_manual_filled = df_50_complete[msk]
df_manual_filled

,pair_id,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type,FromPitchBook
21,10,266429-44,55440-55,Highmark Health Ventures,Venture Capital,"Pittsburgh, PA",1990.0,Sister,Pittsburgh,Pennsylvania,United States,01/30/2023,vc,hospital,False
343,171,361472-59,399434-32,Healthcare Innovation Fund,Corporate Venture Capital,"Lafayette, LA",NaN,Subsidiary,Lafayette,Louisiana,United States,05/06/2023,vc,hospital,False
455,227,513338-32,11259-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
497,248,158931-46,125942-95,Medsi Group,Clinics/Outpatient Services,"Moscow, Russia",1996.0,Sister,Moscow,NaN,Russia,05/06/2023,hospital,vc,False
498,249,507452-14,164588-68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
500,250,527371-30,114336-37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
503,251,527371-30,64863-82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
504,252,62848-00,111991-60,Netdoktor.at,Other Healthcare Services,"Vienna, Austria",2001.0,Sister,Vienna,NaN,Austria,01/30/2023,hospital,vc,False
507,253,166341-79,157276-27,Ora Clinical,Other Healthcare Services,"Andover, MA",1985.0,Parent,Andover,Massachusetts,United States,01/30/2023,hospital,vc,False

In [28]:
## for future use, create a function to do the filling from reference DataFrame with validation

# Check for exact one-to-one or many-to-one relationship
def fill_from_reference(df, ref_df, key_col, columns_to_fill = None):
    """
    Fill columns in df from ref_df based on key_col.
    Ensures each row in df matches exactly one row in ref_df.

    Parameters:
    - df: Main DataFrame to fill
    - ref_df: Reference DataFrame to fill from
    - key_col: Column name to match on
    - columns_to_fill: List of columns to fill (None = all columns except key)
    """

    # Validate reference DataFrame has no duplicate keys
    dup_keys = ref_df[key_col][ref_df[key_col].duplicated()].unique()
    assert len(dup_keys) == 0, f"Reference has duplicate keys: {dup_keys.tolist()}"

    # Validate all keys in df exist in ref_df
    missing = set(df[key_col]) - set(ref_df[key_col])
    assert len(missing) == 0, f"Keys not found in reference: {missing}"

    # Determine which columns to fill
    if columns_to_fill is None:
        columns_to_fill = [col for col in ref_df.columns if col != key_col]

    # Create a subset of ref_df with only needed columns
    ref_subset = ref_df[[key_col] + columns_to_fill]

    # Merge with validation
    result = df.drop(columns = [col for col in columns_to_fill if col in df.columns], errors = 'ignore')
    result = result.merge(ref_subset, on = key_col, how = 'left', validate = 'many_to_one')

    # Verify no NaN introduced (meaning all keys matched)
    for col in columns_to_fill:
        assert result[col].notna().all(), f"Column {col} has NaN after merge - some keys didn't match"

    return result

# Usage
# df_filled = fill_from_reference(df, ref_df, 'key')
# print(df_filled)

In [29]:
# for those 4 rows I still can fill in the affiliation type from its pair,
# if the pair is sister the affiliation type should be the same
# if the pair is parent-subsidiary the affiliation type should be reversed

df_55_complete = df_50_complete.copy()
df = df_55_complete

# Define the reverse affiliation mapping
reverse_affiliation = {
        const.par: const.sub,
        const.sub: const.par,
        const.sis: const.sis,
}

msk = df[var.aff_type].isna()

# Fill missing affiliations based on reverse pairs
for idx, row in df[msk].iterrows():
    # Find the reverse pair (same pair_id, but col1 and col2 swapped)
    reverse_mask = (
            (df[var.pair_id] == row[var.pair_id]) &
            (df[var.entity_id] == row[var.affiliate_id]) &
            (df[var.affiliate_id] == row[var.entity_id])
    )

    reverse_rows = df[reverse_mask]

    if not reverse_rows.empty:
        reverse_affiliation_value = reverse_rows.iloc[0][var.aff_type]
        reverse_affiliated_type_value = reverse_rows.iloc[0][var.affiliate_type]

        if pd.notna(reverse_affiliation_value):
            # Apply the reverse mapping
            df.at[idx, var.aff_type] = reverse_affiliation[reverse_affiliation_value]
            df.at[idx, var.affiliate_type] = const.hospital if reverse_affiliated_type_value == const.vc else const.vc
            df.at[
                idx, var.entity_type] = const.hospital if reverse_affiliated_type_value == const.hospital else const.vc

df_55_complete[msk]

,pair_id,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type,FromPitchBook
455,227,513338-32,11259-10,NaN,NaN,NaN,NaN,Sister,NaN,NaN,NaN,NaN,vc,hospital,False
498,249,507452-14,164588-68,NaN,NaN,NaN,NaN,Parent,NaN,NaN,NaN,NaN,hospital,vc,False
500,250,527371-30,114336-37,NaN,NaN,NaN,NaN,Sister,NaN,NaN,NaN,NaN,hospital,vc,False
503,251,527371-30,64863-82,NaN,NaN,NaN,NaN,Sister,NaN,NaN,NaN,NaN,hospital,vc,False

In [30]:
# manually check those rows have the right affiliation type now
msk = df_50_complete[var.aff_type].isna()
df_a = df_50_complete[msk]

msk = df_55_complete[var.pair_id].isin(df_a[var.pair_id])
df_b = df_55_complete[msk]
df_b

,pair_id,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type,FromPitchBook
454,227,11259-10,513338-32,Novartis (Ophthalmology and Respiratory Units),Clinics/Outpatient Services,"Basel, Switzerland",NaN,Sister,Basel,NaN,Switzerland,01/30/2023,hospital,vc,True
455,227,513338-32,11259-10,NaN,NaN,NaN,NaN,Sister,NaN,NaN,NaN,NaN,vc,hospital,False
498,249,507452-14,164588-68,NaN,NaN,NaN,NaN,Parent,NaN,NaN,NaN,NaN,hospital,vc,False
499,249,164588-68,507452-14,Wanyuandia Investment,Corporate Venture Capital,"Hangzhou, China",2021.0,Subsidiary,Hangzhou,Zhejiang,China,01/30/2023,vc,hospital,True
500,250,527371-30,114336-37,NaN,NaN,NaN,NaN,Sister,NaN,NaN,NaN,NaN,hospital,vc,False
501,250,114336-37,527371-30,Catalyst by Wellstar,Corporate Venture Capital,"Marietta, GA",2021.0,Sister,Marietta,Georgia,United States,05/12/2023,vc,hospital,True
502,251,64863-82,527371-30,Catalyst by Wellstar,Corporate Venture Capital,"Marietta, GA",2021.0,Sister,Marietta,Georgia,United States,05/12/2023,vc,hospital,True
503,251,527371-30,64863-82,NaN,NaN,NaN,NaN,Sister,NaN,NaN,NaN,NaN,hospital,vc,False

In [31]:
# YES they are filled correctly

In [32]:
df_55_complete = df_55_complete.sort_values(by = var.pair_id).reset_index(drop = True)
df_55_complete

,pair_id,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type,FromPitchBook
0,0,434783-53,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc,True
1,0,166514-86,434783-53,Ballad Ventures,Corporate Venture Capital,"Johnson City, TN",2020.0,Subsidiary,Johnson City,Tennessee,United States,01/30/2023,vc,hospital,True
2,1,62802-10,57221-29,Bank Austria TFV,Venture Capital,"Vienna, Austria",1996.0,Sister,Vienna,NaN,Austria,01/30/2023,vc,hospital,True
3,1,57221-29,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc,True
4,2,433943-74,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,251,527371-30,64863-82,NaN,NaN,NaN,NaN,Sister,NaN,NaN,NaN,NaN,hospital,vc,False
504,252,62848-00,111991-60,Netdoktor.at,Other Healthcare Services,"Vienna, Austria",2001.0,Sister,Vienna,NaN,Austria,01/30/2023,hospital,vc,False
505,252,111991-60,62848-00,DLD Ventures,Corporate Venture Capital,"Munich, Germany",2007.0,Sister,Munich,NaN,Germany,01/30/2023,vc,hospital,True
506,253,157276-27,166341-79,Oravision Ventures,Corporate Venture Capital,"Andover, MA",NaN,Subsidiary,Andover,Massachusetts,United States,01/30/2023,vc,hospital,True
507,253,166341-79,157276-27,Ora Clinical,Other Healthcare Services,"Andover, MA",1985.0,Parent,Andover,Massachusetts,United States,01/30/2023,hospital,vc,False

In [32]:
# how many unique VCs and hospitals are there?

# number of unique VCs

df = df_55_complete

msk = df[var.affiliate_type].eq(const.vc)
df[msk][var.affiliate_id].nunique()

113

In [33]:
# number of unique hospitals

df = df_55_complete

msk = df[var.affiliate_type].eq(const.hospital)
df[msk][var.affiliate_id].nunique()

226

In [34]:
# how many unique sister hospital-VC pairs are there?

df = df_55_complete

msk0 = df[var.aff_type].eq(const.sis)
df_sis = df[msk0]
df_sis[var.pair_id].nunique()

216

In [35]:
# how many unique parent-subsidiary hospital-VC pairs are there?
df = df_55_complete
msk = df[var.aff_type].isin([const.par, const.sub])
df_par_sub = df[msk]
df_par_sub[var.pair_id].nunique()

65

In [36]:
print(len(df))
print(len(df_sis) + len(df_par_sub))
assert len(df_sis) + len(df_par_sub) == len(df)

508
508

In [37]:
# how many parent hospital and VS as subsidiary we have?
df = df_55_complete

msk1 = df[var.affiliate_type].eq(const.hospital) & df[var.aff_type].eq(const.par)
df_1 = df[msk1]
len(df[msk1])

47

In [38]:
# how many VC as parent and hospital as subsidiary we have?
df = df_55_complete

msk2 = df[var.affiliate_type].eq(const.vc) & df[var.aff_type].eq(const.par)
df_2 = df[msk2]

len(df[msk2])

9

In [39]:
missing_0 = set(df_par_sub[var.pair_id]) - set(df_1[var.pair_id]) - set(df_2[var.pair_id])
missing_0

{4, 8, 10, 42, 43, 70, 107, 116, 171}

In [40]:
dfa = df[df[var.pair_id].isin(missing_0)]
dfa

,pair_id,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type,FromPitchBook
8,4,433943-74,185286-07,St. John Medical Center (Sisters of Charity He...,Hospitals/Inpatient Services,"Cleveland, OH",NaN,Sister,Cleveland,Ohio,United States,05/06/2023,hospital,vc,True
9,4,185286-07,433943-74,University Hospitals Ventures,Corporate Venture Capital,"Cleveland, OH",2018.0,Subsidiary,Cleveland,Ohio,United States,03/03/2023,vc,hospital,True
16,8,55757-98,142182-82,Summit Healthcare Regional Medical Center,Hospitals/Inpatient Services,"Show Low, AZ",1970.0,Sister,Show Low,Arizona,United States,01/30/2023,hospital,vc,True
17,8,142182-82,55757-98,Mayo Clinic Ventures,Venture Capital,"Rochester, MN",1986.0,Subsidiary,Rochester,Minnesota,United States,01/30/2023,vc,hospital,True
20,10,55440-55,266429-44,United Concordia Dental,Clinics/Outpatient Services,"Harrisburg, PA",1992.0,Subsidiary,Harrisburg,Pennsylvania,United States,01/30/2023,hospital,vc,True
21,10,266429-44,55440-55,Highmark Health Ventures,Venture Capital,"Pittsburgh, PA",1990.0,Sister,Pittsburgh,Pennsylvania,United States,01/30/2023,vc,hospital,False
84,42,165856-15,521254-27,Shanghai Meihong Private Equity Fund,Corporate Venture Capital,"Shanghai, China",NaN,Subsidiary,Shanghai,NaN,China,03/08/2023,vc,hospital,True
85,42,521254-27,165856-15,CiMing Health Checkup Management Group Company,Clinics/Outpatient Services,"Beijing, China",2002.0,Sister,Beijing,NaN,China,05/06/2023,hospital,vc,True
86,43,521254-27,490813-93,Shenzhen AoYa Health Management,Clinics/Outpatient Services,"Shenzhen, China",2014.0,Sister,Shenzhen,Guangdong,China,05/06/2023,hospital,vc,True
87,43,490813-93,521254-27,Shanghai Meihong Private Equity Fund,Corporate Venture Capital,"Shanghai, China",NaN,Subsidiary,Shanghai,NaN,China,03/08/2023,vc,hospital,True
140,70,183174-85,470719-63,Luminox Health,Other Healthcare Services,"Tel Aviv, Israel",2013.0,Subsidiary,Tel Aviv,NaN,Israel,01/30/2023,hospital,vc,True
141,70,470719-63,183174-85,Qure Ventures,Venture Capital,"Herzliya, Israel",2012.0,Sister,Herzliya,NaN,Israel,01/30/2023,vc,hospital,True
214,107,470719-63,172574-29,Cognitiv Ventures,Venture Capital,"Herzliya, Israel",2013.0,Sister,Herzliya,NaN,Israel,01/30/2023,vc,hospital,True
215,107,172574-29,470719-63,Luminox Health,Other Healthcare Services,"Tel Aviv, Israel",2013.0,Subsidiary,Tel Aviv,NaN,Israel,01/30/2023,hospital,vc,True
232,116,439680-34,123677-56,Providence Ventures,Venture Capital,"Seattle, WA",2014.0,Subsidiary,Seattle,Washington,United States,01/30/2023,vc,hospital,True
233,116,123677-56,439680-34,Shin Imaging,Clinics/Outpatient Services,"Los Angeles, CA",2003.0,Sister,Los Angeles,California,United States,05/06/2023,hospital,vc,True
342,171,399434-32,361472-59,Acadia General Hospital,Hospitals/Inpatient Services,"Crowley, LA",2014.0,Sister,Crowley,Louisiana,United States,05/06/2023,hospital,vc,True
343,171,361472-59,399434-32,Healthcare Innovation Fund,Corporate Venture Capital,"Lafayette, LA",NaN,Subsidiary,Lafayette,Louisiana,United States,05/06/2023,vc,hospital,False

In [41]:
df = df_55_complete

msk = df[var.pair_id].isin(missing_0)

df.loc[msk, var.not_valid_affiliation_type] = True

df[msk]

,pair_id,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type,FromPitchBook,not_valid_affiliation_type
8,4,433943-74,185286-07,St. John Medical Center (Sisters of Charity He...,Hospitals/Inpatient Services,"Cleveland, OH",NaN,Sister,Cleveland,Ohio,United States,05/06/2023,hospital,vc,True,True
9,4,185286-07,433943-74,University Hospitals Ventures,Corporate Venture Capital,"Cleveland, OH",2018.0,Subsidiary,Cleveland,Ohio,United States,03/03/2023,vc,hospital,True,True
16,8,55757-98,142182-82,Summit Healthcare Regional Medical Center,Hospitals/Inpatient Services,"Show Low, AZ",1970.0,Sister,Show Low,Arizona,United States,01/30/2023,hospital,vc,True,True
17,8,142182-82,55757-98,Mayo Clinic Ventures,Venture Capital,"Rochester, MN",1986.0,Subsidiary,Rochester,Minnesota,United States,01/30/2023,vc,hospital,True,True
20,10,55440-55,266429-44,United Concordia Dental,Clinics/Outpatient Services,"Harrisburg, PA",1992.0,Subsidiary,Harrisburg,Pennsylvania,United States,01/30/2023,hospital,vc,True,True
21,10,266429-44,55440-55,Highmark Health Ventures,Venture Capital,"Pittsburgh, PA",1990.0,Sister,Pittsburgh,Pennsylvania,United States,01/30/2023,vc,hospital,False,True
84,42,165856-15,521254-27,Shanghai Meihong Private Equity Fund,Corporate Venture Capital,"Shanghai, China",NaN,Subsidiary,Shanghai,NaN,China,03/08/2023,vc,hospital,True,True
85,42,521254-27,165856-15,CiMing Health Checkup Management Group Company,Clinics/Outpatient Services,"Beijing, China",2002.0,Sister,Beijing,NaN,China,05/06/2023,hospital,vc,True,True
86,43,521254-27,490813-93,Shenzhen AoYa Health Management,Clinics/Outpatient Services,"Shenzhen, China",2014.0,Sister,Shenzhen,Guangdong,China,05/06/2023,hospital,vc,True,True
87,43,490813-93,521254-27,Shanghai Meihong Private Equity Fund,Corporate Venture Capital,"Shanghai, China",NaN,Subsidiary,Shanghai,NaN,China,03/08/2023,vc,hospital,True,True
140,70,183174-85,470719-63,Luminox Health,Other Healthcare Services,"Tel Aviv, Israel",2013.0,Subsidiary,Tel Aviv,NaN,Israel,01/30/2023,hospital,vc,True,True
141,70,470719-63,183174-85,Qure Ventures,Venture Capital,"Herzliya, Israel",2012.0,Sister,Herzliya,NaN,Israel,01/30/2023,vc,hospital,True,True
214,107,470719-63,172574-29,Cognitiv Ventures,Venture Capital,"Herzliya, Israel",2013.0,Sister,Herzliya,NaN,Israel,01/30/2023,vc,hospital,True,True
215,107,172574-29,470719-63,Luminox Health,Other Healthcare Services,"Tel Aviv, Israel",2013.0,Subsidiary,Tel Aviv,NaN,Israel,01/30/2023,hospital,vc,True,True
232,116,439680-34,123677-56,Providence Ventures,Venture Capital,"Seattle, WA",2014.0,Subsidiary,Seattle,Washington,United States,01/30/2023,vc,hospital,True,True
233,116,123677-56,439680-34,Shin Imaging,Clinics/Outpatient Services,"Los Angeles, CA",2003.0,Sister,Los Angeles,California,United States,05/06/2023,hospital,vc,True,True
342,171,399434-32,361472-59,Acadia General Hospital,Hospitals/Inpatient Services,"Crowley, LA",2014.0,Sister,Crowley,Louisiana,United States,05/06/2023,hospital,vc,True,True
343,171,361472-59,399434-32,Healthcare Innovation Fund,Corporate Venture Capital,"Lafayette, LA",NaN,Subsidiary,Lafayette,Louisiana,United States,05/06/2023,vc,hospital,False,True

In [52]:
df.to_excel(file.di_sp060_05__all_hospitals_and_VC_affiliations__xl, index = False)

In [53]:
df = df_55_complete.copy()

msk = df[var.not_valid_affiliation_type].eq(True)
df = df[~msk]

df_60_complete = df.copy()
df_60_complete

,pair_id,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type,FromPitchBook,not_valid_affiliation_type
0,0,434783-53,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc,True,NaN
1,0,166514-86,434783-53,Ballad Ventures,Corporate Venture Capital,"Johnson City, TN",2020.0,Subsidiary,Johnson City,Tennessee,United States,01/30/2023,vc,hospital,True,NaN
2,1,62802-10,57221-29,Bank Austria TFV,Venture Capital,"Vienna, Austria",1996.0,Sister,Vienna,NaN,Austria,01/30/2023,vc,hospital,True,NaN
3,1,57221-29,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc,True,NaN
4,2,433943-74,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,251,64863-82,527371-30,Catalyst by Wellstar,Corporate Venture Capital,"Marietta, GA",2021.0,Sister,Marietta,Georgia,United States,05/12/2023,vc,hospital,True,NaN
504,252,111991-60,62848-00,DLD Ventures,Corporate Venture Capital,"Munich, Germany",2007.0,Sister,Munich,NaN,Germany,01/30/2023,vc,hospital,True,NaN
505,252,62848-00,111991-60,Netdoktor.at,Other Healthcare Services,"Vienna, Austria",2001.0,Sister,Vienna,NaN,Austria,01/30/2023,hospital,vc,False,NaN
506,253,166341-79,157276-27,Ora Clinical,Other Healthcare Services,"Andover, MA",1985.0,Parent,Andover,Massachusetts,United States,01/30/2023,hospital,vc,False,NaN
507,253,157276-27,166341-79,Oravision Ventures,Corporate Venture Capital,"Andover, MA",NaN,Subsidiary,Andover,Massachusetts,United States,01/30/2023,vc,hospital,True,NaN

In [54]:
df_60_complete.to_excel(file.dp_sp060_10__all_hospitals_and_VC_affiliations__final__xl, index = False)

In [55]:
df_60_complete = pd.read_excel(file.dp_sp060_10__all_hospitals_and_VC_affiliations__final__xl)

In [56]:
# now count again how many unique VCs and hospitals are there?

# number of unique VCs

df = df_60_complete

df

msk = df[var.affiliate_type].eq(const.vc)
df[msk][var.affiliate_id].nunique()

111

In [57]:
# number of unique hospitals

msk = df[var.affiliate_type].eq(const.hospital)
df[msk][var.affiliate_id].nunique()

219

In [58]:
# how many unique sister hospital-VC pairs are there?
msk0 = df[var.aff_type].eq(const.sis)
df_sis = df[msk0]
df_sis[var.pair_id].nunique()

207

In [59]:
msk = df[var.aff_type].isin([const.par, const.sub])
df_par_sub = df[msk]
df_par_sub[var.pair_id].nunique()

56

In [60]:
print(len(df))
print(len(df_sis) + len(df_par_sub))
assert len(df_sis) + len(df_par_sub) == len(df)

490
490

In [61]:
# how many parent hospital and VS as subsidiary we have?
msk1 = df[var.affiliate_type].eq(const.hospital) & df[var.aff_type].eq(const.par)
df_1 = df[msk1]
len(df[msk1])

47

In [62]:
# how many parent VC and hospital as subsidiary we have?
msk2 = df[var.affiliate_type].eq(const.vc) & df[var.aff_type].eq(const.par)
df_2 = df[msk2]
len(df[msk2])

9