# GOAL
Prepare data for plots requested by Richard. Plotting in R.

# CONFIG

In [6]:
import sys
import pandas as pd
from pathlib import Path

sys.modules.pop('a20_config.a10_config', None)  # force reload
from a20_config.a10_config import dyr, file, const, var

Path.cwd()

PosixPath('/sharedata/camm/c_projects/i100_g7__VC_arms')

# VC Related Deals

In [7]:
# there is a prepared data: od_c050_060_* dataset but it has some issues, I removed some of the affiliations in c055 so I will do the filtering again here

In [8]:
# read the clean affiliation data
df00_aff = pd.read_excel(file.dp_sp060_10__all_hospitals_and_VC_affiliations__final__xl)
df00_aff

,pair_id,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type,FromPitchBook,not_valid_affiliation_type
0,0,434783-53,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc,True,NaN
1,0,166514-86,434783-53,Ballad Ventures,Corporate Venture Capital,"Johnson City, TN",2020.0,Subsidiary,Johnson City,Tennessee,United States,01/30/2023,vc,hospital,True,NaN
2,1,62802-10,57221-29,Bank Austria TFV,Venture Capital,"Vienna, Austria",1996.0,Sister,Vienna,NaN,Austria,01/30/2023,vc,hospital,True,NaN
3,1,57221-29,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc,True,NaN
4,2,433943-74,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449,251,527371-30,64863-82,NaN,NaN,NaN,NaN,Sister,NaN,NaN,NaN,NaN,hospital,vc,False,NaN
450,252,62848-00,111991-60,Netdoktor.at,Other Healthcare Services,"Vienna, Austria",2001.0,Sister,Vienna,NaN,Austria,01/30/2023,hospital,vc,False,NaN
451,252,111991-60,62848-00,DLD Ventures,Corporate Venture Capital,"Munich, Germany",2007.0,Sister,Munich,NaN,Germany,01/30/2023,vc,hospital,True,NaN
452,253,157276-27,166341-79,Oravision Ventures,Corporate Venture Capital,"Andover, MA",NaN,Subsidiary,Andover,Massachusetts,United States,01/30/2023,vc,hospital,True,NaN
453,253,166341-79,157276-27,Ora Clinical,Other Healthcare Services,"Andover, MA",1985.0,Parent,Andover,Massachusetts,United States,01/30/2023,hospital,vc,False,NaN

In [9]:
# get unique VC IDs (all VCs that have hospital affiliations)
msk = df00_aff[var.affiliate_type].eq(const.vc)
unique_vc_ids = df00_aff[msk][var.affiliate_id].unique().tolist()
len(unique_vc_ids), unique_vc_ids[:5]

(110, ['434783-53', '57221-29', '433943-74', '56040-94', '433710-46'])

In [10]:
# read deal-investor relationship data
df_deal_inv_rel = pd.read_parquet(file.pb_deal_inv_rel__parq)
print(df_deal_inv_rel.shape)
df_deal_inv_rel

(2398260, 14)

,DealID,InvestorID,InvestorName,InvestorStatus,IsLeadInvestor,InvestorFundID,InvestorFundName,InvestorWebsite,InvestorInvestmentAmount,LeadPartnerID,LeadPartnerName,LeadPartnerEmail,LeadPartnerPhone,LastUpdated
0,10006-75T,10013-32,Audax Group,New Investor,Yes,10947-16F,Audax Private Equity Fund II,www.audaxgroup.com,NaN,15918-58P,Oliver Ewald,oewald@audaxgroup.com,+1 (617) 859-1538,01/30/2023
1,197378-02T,40667-95,Standard Chartered,New Investor,No,None,None,www.sc.com,NaN,None,None,None,None,01/30/2023
2,10006-93T,10073-98,Irving Place Capital,New Investor,Yes,10913-95F,Irving Place Capital Partners II,www.irvingplacecapital.com,130.000,None,None,None,None,05/12/2023
3,197380-81T,57084-40,Calbee Japan,Acquirer,Yes,None,None,www.calbee.co.jp,NaN,None,None,None,None,02/02/2023
4,10007-02T,10012-69,Berkshire Partners,New Investor,Yes,10928-17F,Berkshire Fund VI,www.berkshirepartners.com,NaN,15348-97P,Marni Payne,mpayne@berkshirepartners.com,+1 (617) 227-0050,05/14/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2398255,199399-96T,10123-03,General Catalyst,New Investor,No,None,None,www.generalcatalyst.com,NaN,None,None,None,None,04/28/2023
2398256,199400-05T,501492-79,Chainlink Fall Hackathon,New Investor,Yes,None,None,None,0.015,None,None,None,None,01/30/2023
2398257,199400-14T,490909-06,Robert Brown,New Investor,No,None,None,None,NaN,289376-83P,Robert Brown,None,None,01/30/2023
2398258,199400-14T,501492-34,Craig Cheek,New Investor,No,None,None,None,NaN,308660-23P,Craig Cheek,None,None,01/30/2023
2398259,199400-14T,184234-96,Anthony Tolliver,New Investor,No,None,None,None,NaN,191694-25P,Anthony Tolliver,atolliver@wealthletefunds.com,+1 (417) 217-7057,01/30/2023

In [12]:
# keep only Investor IDs that are in the final set of VC ids
msk = df_deal_inv_rel[var.investor_id].isin(unique_vc_ids)
df_deal_inv_rel_vc = df_deal_inv_rel[msk]
df_deal_inv_rel_vc

,DealID,InvestorID,InvestorName,InvestorStatus,IsLeadInvestor,InvestorFundID,InvestorFundName,InvestorWebsite,InvestorInvestmentAmount,LeadPartnerID,LeadPartnerName,LeadPartnerEmail,LeadPartnerPhone,LastUpdated
4494,10136-71T,11246-23,Kaiser Permanente Ventures,New Investor,No,None,None,www.kpventures.com,NaN,None,None,None,None,01/30/2023
4677,196969-69T,340845-76,Cleveland Clinic Ventures,Follow-On Investor,Yes,None,None,ventures.clevelandclinic.org,NaN,None,None,None,None,01/30/2023
4928,10149-76T,52247-80,Burda Digital Ventures,New Investor,Yes,None,None,www.burdadigital.de,NaN,None,None,None,None,01/30/2023
6203,196991-11T,55757-98,Mayo Clinic Ventures,New Investor,No,None,None,ventures.mayoclinic.org,NaN,None,None,None,None,01/30/2023
9165,197157-70T,277741-00,Elevator Ventures,New Investor,No,None,None,www.elevator-ventures.com,NaN,215442-82P,Thomas Muchar,thomas.muchar@elevator-ventures.com,None,01/30/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2390204,199713-43T,166204-27,Fresenius Medical Care Ventures,New Investor,Yes,None,None,www.fmcv.com,NaN,13412-17P,Albert Wiegman,albert.wiegman@fmc-na.com,None,02/21/2023
2392865,10580-41T,11114-65,Ascension Ventures,New Investor,No,11004-85F,Ascension Health Ventures,www.ascensionventures.org,10.00000,12822-58P,Matthew Hermann,None,None,01/30/2023
2394354,199106-02T,11271-34,Philips Health Technology Venture Fund,New Investor,Yes,None,None,www.ventures.philips.com,NaN,None,None,None,None,01/30/2023
2394760,199139-41T,55879-21,OurCrowd,New Investor,No,None,None,www.ourcrowd.com,0.35892,None,None,None,None,04/20/2023
2395373,199186-66T,471897-01,NHH Ventures,New Investor,Yes,None,None,www.nhhventures.com,NaN,None,None,None,None,03/22/2023

In [13]:
# check are all investor IDs has the \d+-\d+ pattern?
pattern = r'^\d+-\d+$'
msk = df_deal_inv_rel_vc[var.investor_id].str.match(pattern)
all(msk)

True

-> so there is no row with like a list of investors in one row, good, (if there is, I need to split them first because then filtering will be wrong and can't be matched correctly)

In [14]:
# save the dataset for future reference
_fp = file.di_sp070_05__vc_related_deal_ids__xl
df_deal_inv_rel_vc.to_excel(_fp, index = False)
_fp

PosixPath('/sharedata/camm/c_projects/i100_g7__VC_arms/f10_data_interim/di_sp070_05__vc_related_deal_ids.xlsx')

---

In [15]:
# read back the saved dataset, all the deals that involve VCs
df_deal_inv_rel_vc = pd.read_excel(file.di_sp070_05__vc_related_deal_ids__xl)
df_deal_inv_rel_vc

,DealID,InvestorID,InvestorName,InvestorStatus,IsLeadInvestor,InvestorFundID,InvestorFundName,InvestorWebsite,InvestorInvestmentAmount,LeadPartnerID,LeadPartnerName,LeadPartnerEmail,LeadPartnerPhone,LastUpdated
0,10136-71T,11246-23,Kaiser Permanente Ventures,New Investor,No,NaN,NaN,www.kpventures.com,NaN,NaN,NaN,NaN,NaN,01/30/2023
1,196969-69T,340845-76,Cleveland Clinic Ventures,Follow-On Investor,Yes,NaN,NaN,ventures.clevelandclinic.org,NaN,NaN,NaN,NaN,NaN,01/30/2023
2,10149-76T,52247-80,Burda Digital Ventures,New Investor,Yes,NaN,NaN,www.burdadigital.de,NaN,NaN,NaN,NaN,NaN,01/30/2023
3,196991-11T,55757-98,Mayo Clinic Ventures,New Investor,No,NaN,NaN,ventures.mayoclinic.org,NaN,NaN,NaN,NaN,NaN,01/30/2023
4,197157-70T,277741-00,Elevator Ventures,New Investor,No,NaN,NaN,www.elevator-ventures.com,NaN,215442-82P,Thomas Muchar,thomas.muchar@elevator-ventures.com,NaN,01/30/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4249,199713-43T,166204-27,Fresenius Medical Care Ventures,New Investor,Yes,NaN,NaN,www.fmcv.com,NaN,13412-17P,Albert Wiegman,albert.wiegman@fmc-na.com,NaN,02/21/2023
4250,10580-41T,11114-65,Ascension Ventures,New Investor,No,11004-85F,Ascension Health Ventures,www.ascensionventures.org,10.00000,12822-58P,Matthew Hermann,NaN,NaN,01/30/2023
4251,199106-02T,11271-34,Philips Health Technology Venture Fund,New Investor,Yes,NaN,NaN,www.ventures.philips.com,NaN,NaN,NaN,NaN,NaN,01/30/2023
4252,199139-41T,55879-21,OurCrowd,New Investor,No,NaN,NaN,www.ourcrowd.com,0.35892,NaN,NaN,NaN,NaN,04/20/2023
4253,199186-66T,471897-01,NHH Ventures,New Investor,Yes,NaN,NaN,www.nhhventures.com,NaN,NaN,NaN,NaN,NaN,03/22/2023

In [16]:
df_deal = pd.read_parquet(file.pb_deals__parq)
df_deal

,CompanyID,CompanyName,DealNo,DealID,DealDate,AnnouncedDate,DealSize,DealStatus,DealSizeStatus,PremoneyValuation,...,DealSize_NetIncome,DealSize_Revenue,Valuation_Revenue,ImpliedEV_Revenue,DealSize_CashFlow,Valuation_CashFlow,ImpliedEV_CashFlow,ImpliedEV_NetIncome,EBITDAMarginPercent,LastUpdated
0,10013-68,Arnold Magnetic Technologies,1,10006-75T,01/12/2005,None,NaN,Completed,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
1,123596-92,North Star Rail Intermodal,2,223856-74T,None,None,NaN,Completed,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/17/2023
2,10013-14,7 For All Mankind,1,10006-93T,03/10/2005,None,130.000000,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/03/2023
3,163525-96,Hospital Universitari General de Catalunya,1,223528-96T,None,None,NaN,Completed,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/12/2023
4,10014-58,Aritzia,1,10007-02T,12/20/2005,None,NaN,Completed,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03/17/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1895366,34058-44,Ardmore Regional Surgery Center,1,14746-15T,08/21/2008,None,NaN,Completed,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
1895367,32170-15,Edeniq,1,14748-85T,07/31/2008,None,33.159942,Completed,Actual,100.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
1895368,32173-93,ElectroPetroleum,1,14752-54T,10/01/2008,None,4.776559,Completed,Actual,15.999996,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
1895369,34154-20,About Health,1,14754-79T,11/05/1996,None,NaN,Completed,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
1895370,12916-27,Goretek Data Systems,1,14754-88T,10/20/1995,None,NaN,Completed,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023

In [17]:
# keep only deals that are in the previous filtered deal-investor data
msk = df_deal[var.deal_id].isin(df_deal_inv_rel_vc[var.deal_id])
df_deal_vc = df_deal[msk]
df_deal_vc

,CompanyID,CompanyName,DealNo,DealID,DealDate,AnnouncedDate,DealSize,DealStatus,DealSizeStatus,PremoneyValuation,...,DealSize_NetIncome,DealSize_Revenue,Valuation_Revenue,ImpliedEV_Revenue,DealSize_CashFlow,Valuation_CashFlow,ImpliedEV_CashFlow,ImpliedEV_NetIncome,EBITDAMarginPercent,LastUpdated
1003,464139-28,MyoGene Bio,8,223581-43T,05/11/2023,None,NaN,Completed,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/12/2023
2402,10247-59,Medfinders,5,10136-71T,08/10/2007,None,250.000000,Completed,Estimated,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/18/2023
2634,10382-23,Glam,4,10149-76T,02/25/2008,None,84.667588,Completed,Actual,471.2160,...,NaN,4.051081,25.482468,NaN,NaN,NaN,NaN,NaN,17.703349,02/02/2023
4057,125271-73,OncoResponse,6,223726-96T,05/12/2023,05/01/2023,13.915153,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/18/2023
5569,496403-38,"Hume (Movies, Music and Entertainment)",3,223802-29T,01/26/2023,None,12.700000,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/17/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1891367,12882-79,NeoGuide,5,11866-51T,09/21/2006,None,25.141785,Completed,Actual,31.5185,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02/16/2023
1892151,14777-11,Phenomix,5,12014-56T,03/08/2007,None,55.000001,Completed,Actual,71.7600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/20/2023
1892152,14777-11,Phenomix,6,12014-65T,01/22/2008,None,18.350000,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
1894367,12142-09,Workscape,1,13606-30T,01/01/1999,None,12.500000,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/03/2023
1895300,13129-48,TriPath Imaging,1,14338-45T,11/26/1996,None,NaN,Completed,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023

In [22]:
len(df_deal_vc)

3989

In [23]:
# get deal status value counts
df_deal_vc[var.deal_status].value_counts()

DealStatus
Completed                3984
Announced/In Progress       3
Failed/Cancelled            2
Name: count, dtype: int64

In [24]:
msk = df_deal_vc[var.deal_status].eq('Completed')

df_deal_vc_2 = df_deal_vc[msk]
# 5 rows dropped here
df_deal_vc_2

,CompanyID,CompanyName,DealNo,DealID,DealDate,AnnouncedDate,DealSize,DealStatus,DealSizeStatus,PremoneyValuation,...,DealSize_NetIncome,DealSize_Revenue,Valuation_Revenue,ImpliedEV_Revenue,DealSize_CashFlow,Valuation_CashFlow,ImpliedEV_CashFlow,ImpliedEV_NetIncome,EBITDAMarginPercent,LastUpdated
1003,464139-28,MyoGene Bio,8,223581-43T,05/11/2023,None,NaN,Completed,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/12/2023
2402,10247-59,Medfinders,5,10136-71T,08/10/2007,None,250.000000,Completed,Estimated,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/18/2023
2634,10382-23,Glam,4,10149-76T,02/25/2008,None,84.667588,Completed,Actual,471.2160,...,NaN,4.051081,25.482468,NaN,NaN,NaN,NaN,NaN,17.703349,02/02/2023
4057,125271-73,OncoResponse,6,223726-96T,05/12/2023,05/01/2023,13.915153,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/18/2023
5569,496403-38,"Hume (Movies, Music and Entertainment)",3,223802-29T,01/26/2023,None,12.700000,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/17/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1891367,12882-79,NeoGuide,5,11866-51T,09/21/2006,None,25.141785,Completed,Actual,31.5185,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02/16/2023
1892151,14777-11,Phenomix,5,12014-56T,03/08/2007,None,55.000001,Completed,Actual,71.7600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/20/2023
1892152,14777-11,Phenomix,6,12014-65T,01/22/2008,None,18.350000,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
1894367,12142-09,Workscape,1,13606-30T,01/01/1999,None,12.500000,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/03/2023
1895300,13129-48,TriPath Imaging,1,14338-45T,11/26/1996,None,NaN,Completed,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023

In [25]:
len(df_deal_vc_2)

3984

In [26]:
# keep only deals in $USD
df_deal_vc_2[var.native_currency].value_counts()

NativeCurrencyOfDeal
US Dollars (USD)                       3059
Euros (EUR)                             248
Japanese Yen (JPY)                      232
Chinese Yuan RMB (CNY)                  114
British Pounds (GBP)                    110
Swiss Francs (CHF)                       54
Israeli Shekels (ILS)                    28
India Rupees (INR)                       27
Australian Dollars (AUD)                 26
Canadian Dollars (CAD)                   18
Brazil Real (BRL)                        13
Swedish Krona (SEK)                      10
Viet Nam dong (VND)                      10
Netherlands Antillian guilder (ANG)       7
Singapore Dollar (SGD)                    7
Russian Ruble (RUB)                       6
Danish Kroner (DKK)                       4
Argentine Peso (ARS)                      3
New Zealand Dollar (NZD)                  2
Icelandic Krona (ISK)                     1
Malaysian ringgit (MYR)                   1
Zambian Kwacha (ZMW)                      1
Italian Lira (ITL)                        1
South-Korean Won (KRW)                    1
Polish Zloty (PLN)                        1
Name: count, dtype: int64

In [27]:
msk = df_deal_vc_2[var.native_currency].eq('US Dollars (USD)')
df_deal_vc_3 = df_deal_vc_2[msk]
df_deal_vc_3

,CompanyID,CompanyName,DealNo,DealID,DealDate,AnnouncedDate,DealSize,DealStatus,DealSizeStatus,PremoneyValuation,...,DealSize_NetIncome,DealSize_Revenue,Valuation_Revenue,ImpliedEV_Revenue,DealSize_CashFlow,Valuation_CashFlow,ImpliedEV_CashFlow,ImpliedEV_NetIncome,EBITDAMarginPercent,LastUpdated
1003,464139-28,MyoGene Bio,8,223581-43T,05/11/2023,None,NaN,Completed,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/12/2023
2402,10247-59,Medfinders,5,10136-71T,08/10/2007,None,250.000000,Completed,Estimated,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/18/2023
2634,10382-23,Glam,4,10149-76T,02/25/2008,None,84.667588,Completed,Actual,471.2160,...,NaN,4.051081,25.482468,NaN,NaN,NaN,NaN,NaN,17.703349,02/02/2023
4057,125271-73,OncoResponse,6,223726-96T,05/12/2023,05/01/2023,13.915153,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/18/2023
5569,496403-38,"Hume (Movies, Music and Entertainment)",3,223802-29T,01/26/2023,None,12.700000,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/17/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1891367,12882-79,NeoGuide,5,11866-51T,09/21/2006,None,25.141785,Completed,Actual,31.5185,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02/16/2023
1892151,14777-11,Phenomix,5,12014-56T,03/08/2007,None,55.000001,Completed,Actual,71.7600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/20/2023
1892152,14777-11,Phenomix,6,12014-65T,01/22/2008,None,18.350000,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
1894367,12142-09,Workscape,1,13606-30T,01/01/1999,None,12.500000,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/03/2023
1895300,13129-48,TriPath Imaging,1,14338-45T,11/26/1996,None,NaN,Completed,None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023

In [28]:
len(df_deal_vc_3)

3059

In [29]:
# how many rows dropped here?
print(len(df_deal_vc_2) - len(df_deal_vc_3))
# out of
len(df_deal_vc_2)

925

3984

In [30]:
df_deal_vc_3[var.exit_scope].value_counts()

ExitScope
VC EXIT    23
PE EXIT     8
Name: count, dtype: int64

In [31]:
# drop rows with non-na exit scope
n_bef = len(df_deal_vc_3)
print(n_bef)

msk = df_deal_vc_3[var.exit_scope].isna()
df_deal_vc_3 = df_deal_vc_3[msk]

n_aft = len(df_deal_vc_3)
print(n_aft)
print(f"Dropped {n_bef - n_aft} rows with non-na exit scope.")

3059
3028
Dropped 31 rows with non-na exit scope.

In [32]:
_fp = file.di_sp070_10__vc_related_deals__n1__xl
df_deal_vc_3.to_excel(_fp, index = False)
_fp

PosixPath('/sharedata/camm/c_projects/i100_g7__VC_arms/f10_data_interim/di_sp070_10__vc_related_deals__n1.xlsx')

---

# Further cleaning of deals data

In [33]:
df_deal_vc_3 = pd.read_excel(file.di_sp070_10__vc_related_deals__n1__xl)
df_deal_vc_3

,CompanyID,CompanyName,DealNo,DealID,DealDate,AnnouncedDate,DealSize,DealStatus,DealSizeStatus,PremoneyValuation,...,DealSize_NetIncome,DealSize_Revenue,Valuation_Revenue,ImpliedEV_Revenue,DealSize_CashFlow,Valuation_CashFlow,ImpliedEV_CashFlow,ImpliedEV_NetIncome,EBITDAMarginPercent,LastUpdated
0,464139-28,MyoGene Bio,8,223581-43T,05/11/2023,NaN,NaN,Completed,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/12/2023
1,10382-23,Glam,4,10149-76T,02/25/2008,NaN,84.667588,Completed,Actual,471.2160,...,NaN,4.051081,25.482468,NaN,NaN,NaN,NaN,NaN,17.703349,02/02/2023
2,125271-73,OncoResponse,6,223726-96T,05/12/2023,05/01/2023,13.915153,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/18/2023
3,496403-38,"Hume (Movies, Music and Entertainment)",3,223802-29T,01/26/2023,NaN,12.700000,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/17/2023
4,228181-15,Locanabio,7,223873-21T,05/15/2023,NaN,NaN,Completed,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/18/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3023,12882-79,NeoGuide,5,11866-51T,09/21/2006,NaN,25.141785,Completed,Actual,31.5185,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02/16/2023
3024,14777-11,Phenomix,5,12014-56T,03/08/2007,NaN,55.000001,Completed,Actual,71.7600,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/20/2023
3025,14777-11,Phenomix,6,12014-65T,01/22/2008,NaN,18.350000,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023
3026,12142-09,Workscape,1,13606-30T,01/01/1999,NaN,12.500000,Completed,Actual,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/03/2023
3027,13129-48,TriPath Imaging,1,14338-45T,11/26/1996,NaN,NaN,Completed,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/30/2023

In [34]:
# Count rows before dropping NA rows in dealdate
n_bef = len(df_deal_vc_3)
print(n_bef)

3028

In [35]:
# Drop NA and missing dates
df = df_deal_vc_3.copy()

df_deal_vc_4 = df[df[var.deal_date].notna() & (df[var.deal_date] != "")].copy()
n_aft = len(df_deal_vc_4)
print(n_aft)
print(f"Dropped {n_bef - n_aft} rows with missing deal dates.")

# invalid dates?
df_deal_vc_4[var.deal_date] = pd.to_datetime(df_deal_vc_4[var.deal_date], errors = 'coerce')
msk = df_deal_vc_4[var.deal_date].notna()

df_deal_vc_4_2 = df_deal_vc_4[msk]
n_aft_2 = len(df_deal_vc_4_2)
print(n_aft_2)
print(f"Dropped {n_aft - n_aft_2} rows with invalid deal dates.")

2943
Dropped 85 rows with missing deal dates.
2943
Dropped 0 rows with invalid deal dates.

In [36]:
# Drop nan deal size rows
df = df_deal_vc_4.copy()

df_deal_vc_5 = df[df[var.deal_size].notna()].copy()
n_aft_2 = len(df_deal_vc_5)
print(n_aft_2)
print(f"Dropped {n_aft - n_aft_2} rows with missing deal sizes.")

2658
Dropped 285 rows with missing deal sizes.

In [37]:
# when is the last deal date?
df_deal_vc_5[var.deal_date].max()

Timestamp('2023-05-17 00:00:00')

In [38]:
# how many unique deals are there?
print(len(df_deal_vc_5[var.deal_id].unique()))
# there is no duplicated deal ids
# assert that each deal id appears only once in this dataset
assert df_deal_vc_5[var.deal_id].is_unique

2658

In [39]:
_fp = file.dp_sp070_15__vc_related_deals__n2Final__xl
df_deal_vc_5.to_excel(_fp, index = False)
_fp

PosixPath('/sharedata/camm/c_projects/i100_g7__VC_arms/g10_data_processed/dp_sp070_15__vc_related_deals__n2Final.xlsx')

In [40]:
# find deals count per year
df = df_deal_vc_5.copy()
df[var.deal_year] = df[var.deal_date].dt.year
deal_counts_per_year = df[var.deal_year].value_counts().sort_index()
deal_counts_per_year

deal_year
1987      1
1988      1
1991      1
1996      2
1997      2
1998      5
1999     10
2000     13
2001     18
2002     25
2003     33
2004     44
2005     31
2006     40
2007     50
2008     48
2009     48
2010     42
2011     57
2012     78
2013     95
2014    115
2015    180
2016    168
2017    206
2018    229
2019    241
2020    277
2021    293
2022    245
2023     60
Name: count, dtype: int64

In [41]:
print(deal_counts_per_year.sum())
# should be equal to total number of rows
len(df_deal_vc_5)

2658

2658

In [42]:
_fp = file.rt_sp070_20__vc_deals_by_year__xl
deal_counts_per_year.to_excel(_fp, index = True)
_fp

PosixPath('/sharedata/camm/c_projects/i100_g7__VC_arms/g20_results_tables/rt_sp070_20__vc_deals_by_year.xlsx')

# ReFiltering Hospital-VC affiliations
now only keep those VC that has deal data in this clean deal dataset

In [43]:
df = df_deal_vc_5.copy()

df01_deal_inv_rel = pd.read_parquet(file.pb_deal_inv_rel__parq)
df_1 = df01_deal_inv_rel.copy()

msk = df_1[var.deal_id].isin(df[var.deal_id])

df00_vc_inv = df_1[msk]
df00_vc_inv
# so the final set of VCs should be a subset of this set of investor ids (this list consist of VCs and other types of investors)

,DealID,InvestorID,InvestorName,InvestorStatus,IsLeadInvestor,InvestorFundID,InvestorFundName,InvestorWebsite,InvestorInvestmentAmount,LeadPartnerID,LeadPartnerName,LeadPartnerEmail,LeadPartnerPhone,LastUpdated
4337,196991-11T,53498-35,Scientific Health Development,New Investor,Yes,None,None,www.shdpartners.com,NaN,None,None,None,None,01/30/2023
4613,196969-69T,18862-03,GE Healthcare,New Investor,No,None,None,www.gehealthcare.com,NaN,None,None,None,None,01/30/2023
4647,196969-69T,91166-59,Jumpstart Ventures,New Investor,No,None,None,www.jumpstart.vc,NaN,None,None,None,None,01/30/2023
4677,196969-69T,340845-76,Cleveland Clinic Ventures,Follow-On Investor,Yes,None,None,ventures.clevelandclinic.org,NaN,None,None,None,None,01/30/2023
4891,196969-69T,223625-17,Gana Yantrika Enterprises,New Investor,No,None,None,None,NaN,None,None,None,None,01/30/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2394758,199139-41T,294476-14,Corner Ventures,New Investor,Yes,None,None,cornerventures.com,NaN,63252-28P,Marvin Tien,marvin@cornercapitalmgmt.com,+1 (650) 543-8180,02/18/2023
2394759,199139-41T,435458-35,10X Capital,New Investor,No,None,None,www.10xcapital.com,NaN,None,None,None,None,01/30/2023
2394760,199139-41T,55879-21,OurCrowd,New Investor,No,None,None,www.ourcrowd.com,0.35892,None,None,None,None,04/20/2023
2394761,199139-41T,166690-90,Samsung NEXT Ventures,New Investor,No,None,None,www.samsungnext.com,NaN,None,None,None,None,01/30/2023
2395373,199186-66T,471897-01,NHH Ventures,New Investor,Yes,None,None,www.nhhventures.com,NaN,None,None,None,None,03/22/2023

In [44]:
# so now I need to keep only those affiliations that are in this set of VCs
df_aff = pd.read_excel(file.dp_sp060_10__all_hospitals_and_VC_affiliations__final__xl)
df_aff

,pair_id,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type,FromPitchBook,not_valid_affiliation_type
0,0,434783-53,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc,True,NaN
1,0,166514-86,434783-53,Ballad Ventures,Corporate Venture Capital,"Johnson City, TN",2020.0,Subsidiary,Johnson City,Tennessee,United States,01/30/2023,vc,hospital,True,NaN
2,1,62802-10,57221-29,Bank Austria TFV,Venture Capital,"Vienna, Austria",1996.0,Sister,Vienna,NaN,Austria,01/30/2023,vc,hospital,True,NaN
3,1,57221-29,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc,True,NaN
4,2,433943-74,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449,251,527371-30,64863-82,NaN,NaN,NaN,NaN,Sister,NaN,NaN,NaN,NaN,hospital,vc,False,NaN
450,252,62848-00,111991-60,Netdoktor.at,Other Healthcare Services,"Vienna, Austria",2001.0,Sister,Vienna,NaN,Austria,01/30/2023,hospital,vc,False,NaN
451,252,111991-60,62848-00,DLD Ventures,Corporate Venture Capital,"Munich, Germany",2007.0,Sister,Munich,NaN,Germany,01/30/2023,vc,hospital,True,NaN
452,253,157276-27,166341-79,Oravision Ventures,Corporate Venture Capital,"Andover, MA",NaN,Subsidiary,Andover,Massachusetts,United States,01/30/2023,vc,hospital,True,NaN
453,253,166341-79,157276-27,Ora Clinical,Other Healthcare Services,"Andover, MA",1985.0,Parent,Andover,Massachusetts,United States,01/30/2023,hospital,vc,False,NaN

In [45]:
# drop rows where affiliate type is vc but not in this list of investor ids
# drop rows where enitity type is vc and enitity id not in df00_vc_inv[investor_id]
# make sure all pair number/IDs are exactly twice in the final set
inv_ids = df00_vc_inv[var.investor_id].unique()
len(inv_ids)

6340

In [46]:
msk_a = df_aff.apply(
        lambda row: not (row[var.affiliate_type] == const.vc and row[var.affiliate_id] not in inv_ids),
        axis = 1)

msk_b = df_aff.apply(
        lambda row: not (row[var.entity_type] == const.vc and row[var.entity_type] not in inv_ids),
        axis = 1)

msk = msk_a | msk_b

df05_aff = df_aff[msk]
df05_aff

,pair_id,EntityID,AffiliateID,AffiliateName,Industry,Location,YearFounded,AffiliateType,HQCity,HQState_Province,HQCountry,LastUpdated,affiliate_type,entity_type,FromPitchBook,not_valid_affiliation_type
0,0,434783-53,166514-86,Ballad Health,Hospitals/Inpatient Services,"Johnson City, TN",NaN,Parent,Johnson City,Tennessee,United States,05/06/2023,hospital,vc,True,NaN
1,0,166514-86,434783-53,Ballad Ventures,Corporate Venture Capital,"Johnson City, TN",2020.0,Subsidiary,Johnson City,Tennessee,United States,01/30/2023,vc,hospital,True,NaN
2,1,62802-10,57221-29,Bank Austria TFV,Venture Capital,"Vienna, Austria",1996.0,Sister,Vienna,NaN,Austria,01/30/2023,vc,hospital,True,NaN
3,1,57221-29,62802-10,Clinique Saint,Hospitals/Inpatient Services,"Poissy, France",1959.0,Sister,Poissy,NaN,France,03/02/2023,hospital,vc,True,NaN
4,2,433943-74,55165-33,University Hospitals,Acquirer,NaN,1866.0,Parent,NaN,NaN,NaN,05/06/2023,hospital,vc,True,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449,251,527371-30,64863-82,NaN,NaN,NaN,NaN,Sister,NaN,NaN,NaN,NaN,hospital,vc,False,NaN
450,252,62848-00,111991-60,Netdoktor.at,Other Healthcare Services,"Vienna, Austria",2001.0,Sister,Vienna,NaN,Austria,01/30/2023,hospital,vc,False,NaN
451,252,111991-60,62848-00,DLD Ventures,Corporate Venture Capital,"Munich, Germany",2007.0,Sister,Munich,NaN,Germany,01/30/2023,vc,hospital,True,NaN
452,253,157276-27,166341-79,Oravision Ventures,Corporate Venture Capital,"Andover, MA",NaN,Subsidiary,Andover,Massachusetts,United States,01/30/2023,vc,hospital,True,NaN
453,253,166341-79,157276-27,Ora Clinical,Other Healthcare Services,"Andover, MA",1985.0,Parent,Andover,Massachusetts,United States,01/30/2023,hospital,vc,False,NaN

In [47]:
# nothing is drop here, the number of rows in df05_aff is the same as df_aff
len(df05_aff), len(df_aff)
#   so there is no need to re-filter the affiliations data again (I wanted to keep only those VCs that have deals in the cleaned deal dataset but all of them already have deals in the cleaned deal dataset)

(454, 454)

# Type of Companies these VCs Invest in

In [48]:
df_pb_comp = pd.read_parquet(file.pb_companies__parq)
df_pb_comp

,CompanyID,CompanyName,CompanyAlsoKnownAs,CompanyFormerName,CompanyLegalName,Description,Keywords,CompanyFinancingStatus,CompanyFinancingStatusDate,TotalRaised,...,LastFinancingDebtSize,LastFinancingDebtDate,LastFinancingStatus,LastInvestmentInvestorOwnership,FacebookProfileURL,TwitterProfileURL,LinkedInProfileURL,PitchBookProfileLink,MorningstarID,LastUpdated
0,10010-89,Broadcom (Acquired 2016),None,None,Broadcom Corp.,Manufacturer of semiconductors. The company de...,"ethernet communication, fabless semiconductor,...",Formerly VC-backed,02/01/2016,66.360000,...,15600.0,02/01/2016,Completed,NaN,None,None,None,https://my.pitchbook.com?c=10010-89,0C00000711,01/30/2023
1,187998-49,Matador Film,None,None,None,Operator of media production company. The comp...,"media production, scriptwriting, tv series pro...",Corporate Backed or Acquired,08/29/2017,NaN,...,NaN,08/29/2017,Completed,NaN,None,None,None,https://my.pitchbook.com?c=187998-49,None,05/06/2023
2,10011-16,Acetex,None,None,Acetex Corporation,"Manufacturer of acetic acid in Vancouver, Cana...","acetic acid, acid derivative, pharmaceutical",Corporate Backed or Acquired,07/20/2005,4.247384,...,NaN,07/20/2005,Completed,NaN,None,None,https://www.linkedin.com/company/8322399,https://my.pitchbook.com?c=10011-16,None,04/26/2023
3,187998-58,Chronicle Studio,None,None,None,Provider of web development services intended ...,"web application developer, web developer's pla...",Accelerator/Incubator Backed,None,0.050000,...,NaN,None,Completed,NaN,https://www.facebook.com/TeamChronicle,https://twitter.com/teamchronicle,https://www.linkedin.com/company/chronicle-studio,https://my.pitchbook.com?c=187998-58,None,01/30/2023
4,10011-43,Basic Energy Services,Basic,Sierra Well Service,Basic Energy Services Inc,Basic Energy Services Inc is a provider of wel...,"contract drilling, water logistics, water logi...",Formerly PE-Backed,10/01/2021,50.000000,...,NaN,10/01/2021,Completed,NaN,None,None,None,https://my.pitchbook.com?c=10011-43,0C000006UZ,01/30/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
952979,12394-90,"Martin, Shudt, Wallace, DiLorenzo & Johnson",None,None,None,Provider of legal services catering to corpora...,"law firm, legal firm operator, legal service, ...",Corporate Backed or Acquired,10/01/2021,NaN,...,NaN,10/01/2021,Completed,NaN,None,None,None,https://my.pitchbook.com?c=12394-90,None,01/30/2023
952980,11705-23,3DGeo Development,3DGeo,None,"3DGeo Development, Inc.",Provider of advanced seismic imaging software ...,"seismic imaging, seismic inversion, spectral i...",Formerly PE-Backed,11/03/2008,NaN,...,NaN,11/03/2008,Completed,NaN,None,None,None,https://my.pitchbook.com?c=11705-23,None,01/30/2023
952981,390019-51,Cooper Glass Company,None,None,Cooper Glass Company LLC,Provider of residential and commercial glass s...,"commercial glass product, commercial glass ser...",Corporate Backed or Acquired,02/20/2020,NaN,...,NaN,02/20/2020,Completed,NaN,https://www.facebook.com/Cooper-Glass-Company-...,None,https://www.linkedin.com/company/cooper-glass-...,https://my.pitchbook.com?c=390019-51,None,05/06/2023
952982,12230-92,Pinnacle Electronics,None,"Contraves, Contraves Goerz Corporation",Pinnacle Electronics LLC,Manufacturer of high-reliability electronic as...,"cable, circuit, circuit assembly, electromecha...",Formerly PE-Backed,01/22/2016,NaN,...,NaN,01/22/2016,Completed,NaN,None,None,None,https://my.pitchbook.com?c=12230-92,None,01/30/2023
952983,12011-59,Palombo's Med-Rite Pharmacy,Palombos Med-Rite Pharmacy,None,None,Provider of pharmacy services. The company off...,"ancillary management, care, consultancy, healt...",Formerly PE-Backed,01/01/2006,NaN,...,NaN,01/01/2006,Completed,NaN,None,None,None,https://my.pitchbook.com?c=12011-59,None,01/30/2023

In [50]:
df10_vc_deals = pd.read_excel(file.dp_sp070_15__vc_related_deals__n2Final__xl)
dfa = df10_vc_deals.copy()

msk = df_pb_comp[var.comp_id].isin(dfa[var.comp_id])

df_comp_vc = df_pb_comp[msk]
df_comp_vc

,CompanyID,CompanyName,CompanyAlsoKnownAs,CompanyFormerName,CompanyLegalName,Description,Keywords,CompanyFinancingStatus,CompanyFinancingStatusDate,TotalRaised,...,LastFinancingDebtSize,LastFinancingDebtDate,LastFinancingStatus,LastInvestmentInvestorOwnership,FacebookProfileURL,TwitterProfileURL,LinkedInProfileURL,PitchBookProfileLink,MorningstarID,LastUpdated
228,10056-07,CodeCorrect,None,None,"CodeCorrect, LLC",Provider of web-based coding tools designed to...,"online medical coding, online medical coding s...",Formerly PE-Backed,01/23/2006,3.000000,...,NaN,01/23/2006,Completed,NaN,None,None,None,https://my.pitchbook.com?c=10056-07,None,01/30/2023
270,10070-74,Health Dialog Services,None,None,None,Provider of care management and analytic servi...,"analytics services, care management, disease m...",Formerly PE-Backed,04/02/2014,364.460000,...,NaN,04/02/2014,Completed,NaN,https://www.facebook.com/158723507477525,https://twitter.com/healthdialog,https://www.linkedin.com/company/health-dialog,https://my.pitchbook.com?c=10070-74,None,01/30/2023
389,188036-92,Calix Biopharma,None,None,"Calix Biopharma, Inc.",Developer of an exosome-based technology inten...,"biologics based therapy, exosomes technology, ...",Formerly VC-backed,07/18/2018,4.000000,...,NaN,07/18/2018,Completed,NaN,None,None,None,https://my.pitchbook.com?c=188036-92,None,05/06/2023
1752,10366-39,Nereus Pharmaceuticals,None,None,"Nereus Pharmaceuticals, Inc.",Operator of a drug discovery and development c...,"cancer treatment, cancer treatment drug develo...",Formerly VC-backed,12/01/2012,145.264290,...,NaN,12/01/2012,Completed,NaN,None,None,None,https://my.pitchbook.com?c=10366-39,None,01/30/2023
1780,10372-24,Heptares,Heptares Therapeutics,None,Heptares Therapeutics Ltd.,Developer of a novel drug designed to target G...,"clinical stage company, migraine treatment, ph...",Formerly VC-backed,05/18/2017,5.000000,...,NaN,05/18/2017,Completed,NaN,None,None,None,https://my.pitchbook.com?c=10372-24,None,01/30/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945758,12869-11,Amphora Discovery,None,None,None,Provider of pathway-based drug discovery servi...,"compound profiling, microfluidic, vitro assay ...",Formerly VC-backed,10/21/2008,81.870002,...,NaN,10/21/2008,Completed,NaN,None,https://twitter.com/www,https://www.linkedin.com/company/amphora-disco...,https://my.pitchbook.com?c=12869-11,None,04/26/2023
945782,12871-18,Crystal IS,Crystal Innovative Semiconductors,None,"Crystal IS, Inc.",Manufacturer of ultraviolet light emitting dio...,"ain substrates technology, air purification, b...",Formerly VC-backed,01/11/2012,24.002785,...,NaN,01/11/2012,Completed,NaN,https://www.facebook.com/cisuvc,https://twitter.com/cisuvc,https://www.linkedin.com/company/crystal-is,https://my.pitchbook.com?c=12871-18,None,04/26/2023
945938,12882-79,NeoGuide,None,None,"NeoGuide Systems, Inc.",Developer of robotic endoscopic technology for...,"colonoscopy, robotics endoscopic technology, t...",Formerly VC-backed,06/01/2009,63.798033,...,NaN,06/01/2009,Completed,NaN,None,None,https://www.linkedin.com/company/neoguide-systems,https://my.pitchbook.com?c=12882-79,None,04/26/2023
946228,13128-13,Cequent Pharmaceuticals,None,Cequent,"Cequent Pharmaceuticals, Inc.",Developer of RNAi-based therapies based in Cam...,"biopharmaceutical, cancer prevention, inflamma...",Formerly VC-backed,04/01/2010,17.503536,...,NaN,04/01/2010,Completed,NaN,None,None,None,https://my.pitchbook.com?c=13128-13,None,04/26/2023
946236,13129-39,Stereotaxis,None,None,"Stereotaxis, Inc.",Stereotaxis Inc is engaged in robotic technolo...,"cardiological instruments, cardiology instrume...",Formerly VC-backed,05/25/2020,227.938527,...,NaN,05/25/2020,Completed,NaN,https://www.facebook.com/Stereotaxis,https://twitter.com/stereotaxis,https://www.linkedin.com/company/stereotaxis,https://my.pitchbook.com?c=13129-39,0C00000CDX,05/15/2023

In [51]:
_fp = file.dp_sp070_25__companies_in_vc_deals__xl
df_comp_vc.to_excel(_fp, index = False)
_fp

PosixPath('/sharedata/camm/c_projects/i100_g7__VC_arms/g10_data_processed/dp_sp070_25__companies_in_vc_deals.xlsx')